// Centralized locale-aware location, medicine, and date/time formatting system for MediBridge.

const LOCALE_MAP = {
  en: "en-IN",
  hi: "hi-IN",
  ta: "ta-IN",
  te: "te-IN",
  ml: "ml-IN",
  kn: "kn-IN",
};

const LOCATION_MAPS = {
  ta: {
    "Sri Shakthi Hostel": "ஸ்ரீ சக்தி ஹாஸ்டல்",
    "Sri Shakthi Nagar": "ஸ்ரீ சக்தி நகர்",
    "Race Course Road": "ரேஸ் கோர்ஸ் சாலை",
    "Gandhipuram": "காந்திபுரம்",
    "RS Puram": "ஆர்.எஸ். புரம்",
    "Peelamedu": "பீளமேடு",
    "Saibaba Colony": "சாய்பாபா காலனி",
    "Sitra": "சித்ரா",
    "Trichy Road": "திருச்சி சாலை",
    "Mettupalayam Road": "மேட்டுப்பாளையம் சாலை",
    "Avinashi Road": "அவிநாசி சாலை",
    "Coimbatore": "கோயம்பத்தூர்",
    "Tamil Nadu": "தமிழ்நாடு",
    "TamilNadu": "தமிழ்நாடு",
    "TN": "தமிழ்நாடு",
    "India": "இந்தியா",
    "Near": "அருகில்",
    "Road": "சாலை",
    "Street": "தெரு",
    "Nagar": "நகர்",
    "Hostel": "ஹாஸ்டல்",
    "Colony": "காலனி",
  },
  hi: {
    "Sri Shakthi Hostel": "श्री शक्ति हॉस्टल",
    "Sri Shakthi Nagar": "श्री शक्ति नगर",
    "Race Course Road": "रेस कोर्स रोड",
    "Gandhipuram": "गांधीपुरम",
    "RS Puram": "आरएस पुरम",
    "Peelamedu": "पीलामेडू",
    "Saibaba Colony": "साईबाबा कॉलोनी",
    "Sitra": "सिट्रा",
    "Trichy Road": "त्रिची रोड",
    "Mettupalayam Road": "मेट्टुपलायम रोड",
    "Avinashi Road": "अविनाशी रोड",
    "Coimbatore": "कोयंबटूर",
    "Tamil Nadu": "तमिलनाडु",
    "TamilNadu": "तमिलनाडु",
    "TN": "तमिलनाडु",
    "India": "भारत",
    "Near": "पास",
    "Road": "रोड",
    "Street": "स्ट्रीट",
    "Nagar": "नगर",
    "Hostel": "हॉस्टल",
    "Colony": "कॉलोनी",
  },
  te: {
    "Sri Shakthi Hostel": "శ్రీ శక్తి హాస్టల్",
    "Sri Shakthi Nagar": "శ్రీ శక్తి నగర్",
    "Race Course Road": "రేస్ కోర్స్ రోడ్",
    "Gandhipuram": "గాంధీపురం",
    "RS Puram": "ఆర్‌ఎస్ పురం",
    "Peelamedu": "పీలమేడు",
    "Saibaba Colony": "సాయిబాబా కాలనీ",
    "Sitra": "సిత్రా",
    "Trichy Road": "త్రిచీ రోడ్",
    "Mettupalayam Road": "మెట్టుపాళయం రోడ్",
    "Avinashi Road": "అవినాశి రోడ్",
    "Coimbatore": "కోయంబత్తూర్",
    "Tamil Nadu": "తమిళనాడు",
    "TamilNadu": "తమిళనాడు",
    "TN": "తమిళనాడు",
    "India": "భారతదేశం",
    "Near": "సమీపంలో",
    "Road": "రోడ్",
    "Street": "వీధి",
    "Nagar": "నగర్",
  },
  ml: {
    "Sri Shakthi Hostel": "ശ്രീ ശക്തി ഹോസ്റ്റൽ",
    "Sri Shakthi Nagar": "ശ്രീ ശക്തി നഗർ",
    "Race Course Road": "റേസ് കോഴ്സ് റോഡ്",
    "Gandhipuram": "ഗാന്ധിപുരം",
    "RS Puram": "ആർഎസ് പുരം",
    "Peelamedu": "പീളമേട്",
    "Saibaba Colony": "സായിബാബ കോളനി",
    "Sitra": "സിത്ര",
    "Trichy Road": "ട്രിച്ചി റോഡ്",
    "Mettupalayam Road": "മേട്ടുപ്പാളയം റോഡ്",
    "Avinashi Road": "അവിനാശി റോഡ്",
    "Coimbatore": "കോയമ്പത്തൂർ",
    "Tamil Nadu": "തമിഴ്‌നാട്",
    "India": "ഇന്ത്യ",
  },
  kn: {
    "Sri Shakthi Hostel": "ಶ್ರೀ ಶಕ್ತಿ ಹಾಸ್ಟೆಲ್",
    "Sri Shakthi Nagar": "ಶ್ರೀ ಶಕ್ತಿ ನಗರ",
    "Race Course Road": "ರೇಸ್ ಕೋರ್ಸ್ ರಸ್ತೆ",
    "Gandhipuram": "ಗಾಂಧಿಪುರಂ",
    "RS Puram": "ಆರ್‌എസ് ಪುರಂ",
    "Peelamedu": "ಪೀಳಮೇಡು",
    "Saibaba Colony": "ಸಾಯಿಬಾಬಾ ಕಾಲೋನಿ",
    "Sitra": "ಸಿತ್ರಾ",
    "Trichy Road": "ಟ್ರಿಚಿ ರಸ್ತೆ",
    "Mettupalayam Road": "ಮೆಟ್ಟುಪಾಳಯಂ ರಸ್ತೆ",
    "Avinashi Road": "ಅವಿನಾಶಿ ರಸ್ತೆ",
    "Coimbatore": "ಕೊಯಮತ್ತೂರು",
    "Tamil Nadu": "ತಮಿಳುನಾಡು",
    "India": "ಭಾರತ",
  },
};

const MEDICINE_BRAND_MAPS = {
  ta: {
    "Crocin 500": "க்ரோசின் 500",
    "Crocin Advance": "க்ரோசின் அட்வான்ஸ்",
    "Crocin 650": "க்ரோசின் 650",
    "Crocin Drops": "க்ரோசின் சொட்டு மருந்து",
    "Crocin 240 Suspension": "க்ரோசின் 240 சஸ்பென்ஷன்",
    "Crocin": "க்ரோசின்",
    "Dolo 650": "டோலோ 650",
    "Dolo 500": "டோலோ 500",
    "Dolo Drops": "டோலோ சொட்டு மருந்து",
    "Dolo 250 Suspension": "டோலோ 250 சஸ்பென்ஷன்",
    "Dolo 120 Suspension": "டோலோ 120 சஸ்பென்ஷன்",
    "Dolo": "டோலோ",
    "Calpol 500": "கால்போல் 500",
    "Calpol 650": "கால்போல் 650",
    "Calpol 250 Pead": "கால்போல் 250 பீட்",
    "Calpol 120 Suspension": "கால்போல் 120 சஸ்பென்ஷன்",
    "Calpol": "கால்போல்",
    "Pacimol 500": "பாசிமால் 500",
    "Pacimol 650": "பாசிமால் 650",
    "Pacimol Suspension": "பாசிமால் சஸ்பென்ஷன்",
    "Pacimol MF Suspension": "பாசிமால் எம்எஃப் சஸ்பென்ஷன்",
    "Pacimol": "பாசிமால்",
    "Pyrigesic 500": "பைரிஜெசிக் 500",
    "Pyrigesic 650": "பைரிஜெசிக் 650",
    "Pyrigesic Drops": "பைரிஜெசிக் சொட்டு மருந்து",
    "Pyrigesic": "பைரிஜெசிக்",
    "Paracip 500": "பாரசிப் 500",
    "Paracip 650": "பாரசிப் 650",
    "Paracip Drops": "பாரசிப் சொட்டு மருந்து",
    "Paracip Syrup": "பாரசிப் சிரப்",
    "Paracip": "பாரசிப்",
    "Paracetamol Tablets": "பாரசிட்டமால் மாத்திரைகள்",
    "P-650": "பி-650",
    "P-500": "பி-500",
    "P-250 Suspension": "பி-250 சஸ்பென்ஷன்",
    "Sumo L 650": "சுமோ எல் 650",
    "Sumo L 500": "சுமோ எல் 500",
    "Sumo L Drops": "சுமோ எல் சொட்டு மருந்து",
    "Sumo L 250 Suspension": "சுமோ எல் 250 சஸ்பென்ஷன்",
    "Sumo L": "சுமோ எல்",
    "T-98 650": "டி-98 650",
    "T-98 Drops": "டி-98 சொட்டு மருந்து",
    "T-98 Suspension": "டி-98 சஸ்பென்ஷன்",
    "T-98": "டி-98",
    "Combiflam": "காம்பைஃப்ளாம்",
    "Combiflam Plus": "காம்பைஃப்ளாம் பிளஸ்",
    "Combiflam Suspension": "காம்பைஃப்ளாம் சஸ்பென்ஷன்",
    "Brufen 400": "புரூஃபென் 400",
    "Brufen 200": "புரூஃபென் 200",
    "Brufen Plus": "புரூஃபென் பிளஸ்",
    "Brufen Junior": "புரூஃபென் ஜூனியர்",
    "Brufen": "புரூஃபென்",
    "Ibugesic Plus": "ஐபூஜெசிக் பிளஸ்",
    "Ibugesic Plus Suspension": "ஐபூஜெசிக் பிளஸ் சஸ்பென்ஷன்",
    "Ibugesic 400": "ஐபூஜெசிக் 400",
    "Ibugesic": "ஐபூஜெசிக்",
    "Flexon": "ஃபிளெக்ஸான்",
    "Flexon Suspension": "ஃபிளெக்ஸான் சஸ்பென்ஷன்",
    "Mafin Plus": "மாஃபின் பிளஸ்",
    "Zerodol-P": "ஜெரோடால்-பி",
    "Zerodol-SP": "ஜெரோடால்-எஸ்பி",
    "Zerodol-TH 4": "ஜெரோடால்-டிஹெச் 4",
    "Zerodol-TH 8": "ஜெரோடால்-டிஹெச் 8",
    "Zerodol": "ஜெரோடால்",
    "Hifenac-P": "ஹைஃபெனாக்-பி",
    "Hifenac-SP": "ஹைஃபெனாக்-எஸ்பி",
    "Hifenac-TH 4": "ஹைஃபெனாக்-டிஹெச் 4",
    "Hifenac-TH 8": "ஹைஃபெனாக்-டிஹெச் 8",
    "Hifenac": "ஹைஃபெனாக்",
    "Aceclo Plus": "அசெக்லோ பிளஸ்",
    "Dolokind Plus": "டோலோகைண்ட் பிளஸ்",
    "Dolokind-AA": "டோலோகைண்ட்-ஏஏ",
    "Dolokind-MR": "டோலோகைண்ட்-எம்ஆர்",
    "Dolokind": "டோலோகைண்ட்",
    "Movace-P": "மோவேஸ்-பி",
    "Aldigesic-P": "ஆல்டிஜெசிக்-பி",
    "Aldigesic-SP": "ஆல்டிஜெசிக்-எஸ்பி",
    "Arofec-P": "அரோஃபெக்-பி",
    "Canef-P": "கேனெஃப்-பி",
    "Signoflam": "சிக்னோஃப்ளாம்",
    "Flozen-AA": "ஃப்ளோஜென்-ஏஏ",
    "Microflam-SP": "மைக்ரோஃப்ளாம்-எஸ்பி",
    "Aeroz-SP": "ஏரோஸ்-எஸ்பி",
    "Meftal-Spas": "மெஃப்டால்-ஸ்பாஸ்",
    "Meftal-Spas Drops": "மெஃப்டால்-ஸ்பாஸ் சொட்டு மருந்து",
    "Meftal-Spas Suspension": "மெஃப்டால்-ஸ்பாஸ் சஸ்பென்ஷன்",
    "Meftal 500": "மெஃப்டால் 500",
    "Meftal 250": "மெஃப்டால் 250",
    "Meftal": "மெஃப்டால்",
    "Spasmo-Proxyvon Plus": "ஸ்பாஸ்மோ-ப்ராக்ஸிவான் பிளஸ்",
    "Cyclopam": "சைக்ளோபாம்",
    "Cyclopam Drops": "சைக்ளோபாம் சொட்டு மருந்து",
    "Cyclopam Suspension": "சைக்ளோபாம் சஸ்பென்ஷன்",
    "Colimex": "கோலிமெக்ஸ்",
    "Colimex Drops": "கோலிமெக்ஸ் சொட்டு மருந்து",
    "Baralgan-M": "பரால்கன்-எம்",
    "Voveran 50": "வோவெரான் 50",
    "Voveran SR 75": "வோவெரான் எஸ்ஆர் 75",
    "Voveran SR 100": "வோவெரான் எஸ்ஆர் 100",
    "Voveran": "வோவெரான்",
    "Dynapar AQ Injection": "டைனாபார் ஏக்யூ இன்ஜெக்ஷன்",
    "Dynapar 50": "டைனாபார் 50",
    "Dynapar": "டைனாபார்",
    "Diclogesic": "டைக்ளோஜெசிக்",
    "Volini Gel": "வோலினி ஜெல்",
    "Volini Maxx Spray": "வோலினி மேக்ஸ் ஸ்ப்ரே",
    "Volini": "வோலினி",
    "Moov Pain Relief Cream": "மூவ் வலி நிவாரணி கிரீம்",
    "Moov Pain Relief Spray": "மூவ் வலி நிவாரணி ஸ்ப்ரே",
    "Moov": "மூவ்",
    "Omnigel": "ஆம்னிஜெல்",
    "Omnigel Spray": "ஆம்னிஜெல் ஸ்ப்ரே",
    "Amrutanjan Strong Pain Balm": "அம்ருதாஞ்சன் ஸ்ட்ராங் பாம்",
    "Amrutanjan Joint Muscle Spray": "அம்ருதாஞ்சன் ஜாயிண்ட் மசூல் ஸ்ப்ரே",
    "Amrutanjan": "அம்ருதாஞ்சன்",
    "Zandu Balm": "சந்து பாம்",
    "Zandu Ultra Power Balm": "சந்து அல்ட்ரா பவர் பாம்",
    "Zandu": "சந்து",
    "Tiger Balm Red": "டைகர் பாம் ரெட்",
    "Tiger Balm White": "டைகர் பாம் வொயிட்",
    "Tiger Balm": "டைகர் பாம்",
    "Relispray": "ரிலிஸ்ப்ரே",
    "Iodex Ultra Gel": "அயோடெக்ஸ் அல்ட்ரா ஜெல்",
    "Iodex Balm": "அயோடெக்ஸ் பாம்",
    "Iodex": "அயோடெக்ஸ்",
    "Fast Relief Herbal Ointment": "ஃபாஸ்ட் ரிலீஃப் ஹெர்பல் ஒயின்ட்மென்ட்",
    "Nucoxia 90": "நியூகாசியா 90",
    "Nucoxia 60": "நியூகாசியா 60",
    "Nucoxia 120": "நியூகாசியா 120",
    "Nucoxia-P": "நியூகாசியா-பி",
    "Nucoxia": "நியூகாசியா",
    "Arcoxia 90": "ஆர்காசியா 90",
    "Arcoxia 60": "ஆர்காசியா 60",
    "Etoford 90": "எடோஃபோர்டு 90",
    "Etoshine 90": "எடோஷைன் 90",
    "Etoshine 60": "எடோஷைன் 60",
    "Etoshine": "எடோஷைன்",
    "Kingcox 90": "கிங்கோக்ஸ் 90",
    "Brutaflam 90": "ப்ரூடாஃபிளாம் 90",
    "Thiospas 4": "தியோஸ்பாஸ் 4",
    "Thiospas 8": "தியோஸ்பாஸ் 8",
    "Thioquest 4": "தியோக்வெஸ்ட் 4",
    "Chymoral Forte": "கைமோரால் ஃபோர்ட்",
    "Chymoral Plus": "கைமோரால் பிளஸ்",
    "Chymoral AP": "கைமோரால் ஏபி",
    "Chymoral": "கைமோரால்",
    "Chymoheal": "கைமோஹீல்",
    "Enzomac": "என்சோமேக்",
    "Chymomark": "கைமோமார்க்",
    "Cetzine 10": "செட்சைன் 10",
    "Cetzine Syrup": "செட்சைன் சிரப்",
    "Cetzine": "செட்சைன்",
    "Okacet 10": "ஒகாசெட் 10",
    "Okacet Syrup": "ஒகாசெட் சிரப்",
    "Okacet Cold": "ஒகாசெட் கோல்ட்",
    "Okacet": "ஒகாசெட்",
    "Zyrtec 10": "ஸைர்டெக் 10",
    "Alerid 10": "அலெரிட் 10",
    "Alerid-D": "அலெரிட்-டி",
    "Alerid": "அலெரிட்",
    "Cetcip 10": "செட்சிப் 10",
    "Incid-L 10": "இன்சிட்-எல் 10",
    "Levocet 5": "லெவோசெட் 5",
    "Levocet Syrup": "லெவோசெட் சிரப்",
    "Levocet": "லெவோசெட்",
    "1-AL 5": "1-ஏஎல் 5",
    "1-AL Syrup": "1-ஏஎல் சிரப்",
    "1-AL Total": "1-ஏஎல் டோட்டல்",
    "1-AL": "1-ஏஎல்",
    "Teczine 5": "டெக்சைன் 5",
    "Teczine 10": "டெக்சைன் 10",
    "Teczine Syrup": "டெக்சைன் சிரப்",
    "Teczine": "டெக்சைன்",
    "Vozet 5": "வோஸெட் 5",
    "Lupicet 5": "லூபிசெட் 5",
    "Hatric-3": "ஹாட்ரிக்-3",
    "Montair-LC": "மாண்டேர்-எல்சி",
    "Montair-LC Kid": "மாண்டேர்-எல்சி கிட்",
    "Montair-LC Syrup": "மாண்டேர்-எல்சி சிரப்",
    "Montair": "மாண்டேர்",
    "Montek-LC": "மான்டெக்-எல்சி",
    "Montek-LC Kid": "மான்டெக்-எல்சி கிட்",
    "Montek": "மான்டெக்",
    "Telekast-L": "டெலிகாஸ்ட்-எல்",
    "Telekast-L Kid": "டெலிகாஸ்ட்-எல் கிட்",
    "Levolin-M": "லெவோலின்-எம்",
    "Romilast-L": "ரோமிலாஸ்ட்-எல்",
    "Monticope": "மான்டிகோப்",
    "Monticope Suspension": "மான்டிகோப் சஸ்பென்ஷன்",
    "Odimont-LC": "ஓடிமான்ட்-எல்சி",
    "Allegra 120": "அலெக்ரா 120",
    "Allegra 180": "அலெக்ரா 180",
    "Allegra 30 Pead": "அலெக்ரா 30 பீட்",
    "Allegra-M": "அலெக்ரா-எம்",
    "Allegra": "அலெக்ரா",
    "Fexova 120": "ஃபெக்சோவா 120",
    "Fexova 180": "ஃபெக்சோவா 180",
    "Fexigra 120": "ஃபெக்சிகிரா 120",
    "Histafree 120": "ஹிஸ்டாஃப்ரீ 120",
    "Histafree-M": "ஹிஸ்டாஃப்ரீ-எம்",
    "Fexocet 120": "ஃபெக்சோசெட் 120",
    "Benadryl DR Cough Syrup": "பெனாட்ரில் டிஆர் இருமல் சிரப்",
    "Benadryl Cough Formula": "பெனாட்ரில் இருமல் ஃபார்முலா",
    "Benadryl": "பெனாட்ரில்",
    "Alex Syrup": "அலெக்ஸ் சிரப்",
    "Alex Junior Syrup": "அலெக்ஸ் ஜூனியர் சிரப்",
    "Alex": "அலெக்ஸ்",
    "Chericof Syrup": "செரிகாஃப் சிரப்",
    "Ascoril-D Plus": "அஸ்கோரில்-டி பிளஸ்",
    "TusQ-DX": "டஸ்க்-டிஎக்ஸ்",
    "Zedex Cough Syrup": "ஜெடெக்ஸ் இருமல் சிரப்",
    "Corex-DX Syrup": "கோரெக்ஸ்-டிஎக்ஸ் சிரப்",
    "Phensedyl DX": "ஃபென்செடில் டிஎக்ஸ்",
    "Ascoril LS Syrup": "அஸ்கோரில் எல்எஸ் சிரப்",
    "Ascoril LS Drops": "அஸ்கோரில் எல்எஸ் சொட்டு மருந்து",
    "Ascoril LS Junior": "அஸ்கோரில் எல்எஸ் ஜூனியர்",
    "Ascoril LS": "அஸ்கோரில் எல்எஸ்",
    "Ascoril": "அஸ்கோரில்",
    "Bro-Zedex LS": "ப்ரோ-ஜெடெக்ஸ் எல்எஸ்",
    "Asthalin Expectorant": "அஸ்தாலின் எக்ஸ்பெக்டரண்ட்",
    "Macbery-LS": "மேக்பெரி-எல்எஸ்",
    "Ambrodil-LX": "அம்ப்ரோடில்-எல்எக்ஸ்",
    "Levolin Plus Syrup": "லெவோலின் பிளஸ் சிரப்",
    "Kofarest-LS": "கோஃப்பாரெஸ்ட்-எல்எஸ்",
    "Grilinctus-LS": "கிரிலின்க்டஸ்-எல்எஸ்",
    "Sinarest": "சினாரெஸ்ட்",
    "Sinarest Syrup": "சினாரெஸ்ட் சிரப்",
    "Sinarest Drops": "சினாரெஸ்ட் சொட்டு மருந்து",
    "Cheston Cold": "செஸ்டான் கோல்ட்",
    "Cheston Cold Total": "செஸ்டான் கோல்ட் டோட்டல்",
    "Wikoryl": "விகோரில்",
    "Wikoryl AF Syrup": "விகோரில் ஏஎஃப் சிரப்",
    "D-Cold Total": "டி-கோல்ட் டோட்டல்",
    "Febrex Plus": "ஃபெப்ரெக்ஸ் பிளஸ்",
    "Solvin Cold": "சோல்வின் கோல்ட்",
    "Flucold": "ஃபுளுகோல்ட்",
    "Otrivin Adult Nasal Spray": "ஒட்ரிவின் அடல்ட் நாசி ஸ்ப்ரே",
    "Otrivin Oxy Fast Relief": "ஒட்ரிவின் ஆக்ஸி ஃபாஸ்ட் ரிலீஃப்",
    "Otrivin Pediatric Nasal Drops": "ஒட்ரிவின் பீடியாட்ரிக் நாசி சொட்டு மருந்து",
    "Otrivin": "ஒட்ரிவின்",
    "Nasivion Adult Nasal Drops": "நாசிவியான் அடல்ட் நாசி சொட்டு மருந்து",
    "Nasivion Classic Spray": "நாசிவியான் கிளாசிக் ஸ்ப்ரே",
    "Nasivion Mini Drops": "நாசிவியான் மினி சொட்டு மருந்து",
    "Nasivion": "நாசிவியான்",
    "Clearnose Nasal Drops": "கிளியர்நோஸ் நாசி சொட்டு மருந்து",
    "Xylomist Nasal Drops": "சைலோமிஸ்ட் நாசி சொட்டு மருந்து",
    "Omez 20": "ஓமெஸ் 20",
    "Omez 40": "ஓமெஸ் 40",
    "Omez-D": "ஓமெஸ்-டி",
    "Omez": "ஓமெஸ்",
    "Omee 20": "ஓமீ 20",
    "Omezol 20": "ஓமெசோல் 20",
    "Omecip 20": "ஓமிசிப் 20",
    "Prilosec 20": "பிரிலோசெக் 20",
    "Ocid 20": "ஓசிட் 20",
    "Ocid-D": "ஓசிட்-டி",
    "Nexpro 40": "நெக்ஸ்ப்ரோ 40",
    "Nexpro 20": "நெக்ஸ்ப்ரோ 20",
    "Nexpro-RD 40": "நெக்ஸ்ப்ரோ-ஆர்டி 40",
    "Nexpro": "நெக்ஸ்ப்ரோ",
    "Sompraz 40": "சோம்ப்ராஸ் 40",
    "Sompraz 20": "சோம்ப்ராஸ் 20",
    "Sompraz-D 40": "சோம்ப்ராஸ்-டி 40",
    "Sompraz": "சோம்ப்ராஸ்",
    "Esomac 40": "எசோமேக் 40",
    "Pan 40": "பேன் 40",
    "Pan 20": "பேன் 20",
    "Pan-D": "பேன்-டி",
    "Pan": "பேன்",
    "Pantocid 40": "பேன்டோசிட் 40",
    "Pantocid 20": "பேன்டோசிட் 20",
    "Pantocid-DSR": "பேன்டோசிட்-டிஎஸ்ஆர்",
    "Pantocid": "பேன்டோசிட்",
    "Pantodac 40": "பேன்டோடாக் 40",
    "Pantodac-DSR": "பேன்டோடாக்-டிஎஸ்ஆர்",
    "Pantodac": "பேன்டோடாக்",
    "Pantosec 40": "பேன்டோசெக் 40",
    "Nupenta 40": "நுபெண்டா 40",
    "Nupenta-D": "நுபெண்டா-டி",
    "Protera 40": "புரோடேரா 40",
    "Protera-D": "புரோடேரா-டி",
    "Pantocar 40": "பேன்டோகார் 40",
    "Pantocar-DSR": "பேன்டோகார்-டிஎஸ்ஆர்",
    "Zipant 40": "ஜிபேன்ட் 40",
    "Dompan-SR": "டாம்டேன்-எஸ்ஆர்",
    "Gaspas-D": "காஸ்பாஸ்-டி",
    "Razo-D": "ராஸோ-டி",
    "Rablet-D": "ராப்லெட்-டி",
    "Happi-D": "ஹேப்பி-டி",
    "Rabium-DSR": "ராபியம்-டிஎஸ்ஆர்",
    "Cyra-D": "சைரா-டி",
    "Rabonik-DSR": "ராபோனிக்-டிஎஸ்ஆர்",
    "Veloz-D": "வெலோஸ்-டி",
    "Digene Gel Mint": "டைஜீன் ஜெல் மின்ட்",
    "Digene Gel Orange": "டைஜீன் ஜெல் ஆரஞ்சு",
    "Digene Gel Mixed Fruit": "டைஜீன் ஜெல் மிக்ஸ்டு ஃப்ரூட்",
    "Digene Chewable Tablets Mint": "டைஜீன் மெல்லும் மாத்திரைகள் மின்ட்",
    "Digene Chewable Tablets Orange": "டைஜீன் மெல்லும் மாத்திரைகள் ஆரஞ்சு",
    "Digene": "டைஜீன்",
    "Gelusil MPS Liquid": "கெலுசில் எம்பிஎஸ் திரவம்",
    "Gelusil MPS Tablets": "கெலுசில் எம்பிஎஸ் மாத்திரைகள்",
    "Gelusil": "கெலுசில்",
    "Mucaine Gel": "மியூகேன் ஜெல்",
    "Eno Fruit Salt Regular": "ஈனோ ஃப்ரூட் சால்ட் ரெகுலர்",
    "Eno Fruit Salt Lemon": "ஈனோ ஃப்ரூட் சால்ட் லெமன்",
    "Eno Fruit Salt Orange": "ஈனோ ஃப்ரூட் சால்ட் ஆரஞ்சு",
    "Eno": "ஈனோ",
    "Gas-O-Fast Active": "கேஸ்-ஓ-ஃபாஸ்ட் ஆக்டிவ்",
    "Electral Powder": "எலக்ட்ரால் பவுடர்",
    "Electral Orange": "எலக்ட்ரால் ஆரஞ்சு",
    "Electral RTD Liquid": "எலக்ட்ரால் ஆர்டிடி திரவம்",
    "Electral": "எலக்ட்ரால்",
    "Electrobion": "எலக்ட்ரோபயான்",
    "Enerzal Powder Orange": "எனர்ஜால் பவுடர் ஆரஞ்சு",
    "Enerzal Powder Apple": "எனர்ஜால் பவுடர் ஆப்பிள்",
    "Enerzal": "எனர்ஜால்",
    "ORSL Ready Drink Apple": "ஓஆர்எஸ்எல் ரெடி டிரிங்க் ஆப்பிள்",
    "ORSL Ready Drink Orange": "ஓஆர்எஸ்எல் ரெடி டிரிங்க் ஆரஞ்சு",
    "ORSL Plus Rehydrate Lemon": "ஓஆர்எஸ்எல் பிளஸ் ரீஹைட்ரேட் லெமன்",
    "ORSL": "ஓஆர்எஸ்எல்",
    "Walyte ORS": "வாலிட் ஓஆர்எஸ்",
    "Duphalac Syrup": "டுஃபாலாக் சிரப்",
    "Duphalac Fiber": "டுஃபாலாக் ஃபைபர்",
    "Duphalac": "டுஃபாலாக்",
    "Cremaffin Plus": "கிரீமாஃபின் பிளஸ்",
    "Cremaffin Plain": "கிரீமாஃபின் பிளேன்",
    "Cremaffin": "கிரீமாஃபின்",
    "Softovac Bowel Regulator": "சாஃப்டோவேக் பவுல் ரெகுலேட்டர்",
    "Softovac": "சாஃப்டோவேக்",
    "Kayam Churna": "காயம் சூர்ணா",
    "Kayam Tablets": "காயம் மாத்திரைகள்",
    "Kayam": "காயம்",
    "Nature Care Isabgol": "நேச்சர் கேர் இசப்கோல்",
    "Dulcolax 5": "டல்கோலக்ஸ் 5",
    "Dulcolax": "டல்கோலக்ஸ்",
    "Looz Syrup": "லூஸ் சிரப்",
    "Emeset 4": "எமிசெட் 4",
    "Emeset 8": "எமிசெட் 8",
    "Emeset Syrup": "எமிசெட் சிரப்",
    "Emeset Injection": "எமிசெட் இன்ஜெக்ஷன்",
    "Emeset": "எமிசெட்",
    "Vomikind 4": "வாமிகைண்ட் 4",
    "Vomikind-MD 4": "வாமிகைண்ட்-எம்டி 4",
    "Vomikind Syrup": "வாமிகைண்ட் சிரப்",
    "Vomikind": "வாமிகைண்ட்",
    "Ondem 4": "ஆன்டெம் 4",
    "Ondem-MD 4": "ஆன்டெம்-எம்டி 4",
    "Ondem Syrup": "ஆன்டெம் சிரப்",
    "Ondem": "ஆன்டெம்",
    "Zofran 4": "சோஃப்ரான் 4",
    "Cetrizine-D": "செட்ரிசின்-டி",
    "Limcee": "லிம்சி",
    "Novamox": "நோவாமாக்ஸ்",
    "Glycomet": "கிளைகோமெட்",
    "Betadine": "பெட்டாடின்",
    "Clavam": "க்ளவாம்",
    "Augmentin": "ஆக்மென்டின்",
    "Moxikind": "மாக்சிகைண்ட்",
    "Dettol": "டெட்டால்",
    "Ecosprin": "ஈகோஸ்ப்ரின்",
    "Azithral": "அசித்ரால்",
  },
  hi: {
    "Sinarest": "सिनारेस्ट",
    "Sinarest Syrup": "सिनारेस्ट सिरप",
    "Sinarest Drops": "सिनारेस्ट ड्रॉप्स",
    "Otrivin": "ओट्रिविन",
    "Nasivion": "नासीवियन",
    "Omez 20": "ओमेज़ 20",
    "Omez": "ओमेज़",
    "Pan 40": "पैन 40",
    "Pan-D": "पैन-डी",
    "Pantocid 40": "पेंटोसिड 40",
    "Pantocid": "पेंटोसिड",
    "Nexpro 40": "नेक्सप्रो 40",
    "Nexpro": "नेक्सप्रो",
    "Sompraz 40": "सोमप्राज़ 40",
    "Sompraz": "सोमप्राज़",
    "Razo-D": "रेज़ो-डी",
    "Digene Gel Mint": "डाइजीन जेल मिंट",
    "Digene": "डाइजीन",
    "Gelusil MPS Liquid": "जेलुसिल एमपीएस लिक्विड",
    "Gelusil": "जेलुसिल",
    "Volini Gel": "वोलिनी जेल",
    "Volini": "वोलिनी",
    "Meftal-Spas": "मेफ्टाल-स्पास",
    "Meftal": "मेफ्टाल",
    "Zerodol-SP": "ज़ेरोडोल-एसपी",
    "Zerodol-P": "ज़ेरोडोल-पी",
    "Zerodol": "ज़ेरोडोल",
    "Hifenac-P": "हाइफेनैक-पी",
    "Hifenac-SP": "हाइफेनैक-एसपी",
    "Chymoral Forte": "काइमोराल फोर्ट",
    "Benadryl": "बेनाड्रिल",
    "Ascoril LS": "एस्कॉरिल एलएस",
    "Montair-LC": "मोंटेयर-एलसी",
    "Allegra 120": "एलेग्रा 120",
    "Allegra 180": "एलेग्रा 180",
    "Allegra": "एलेग्रा",
    "Cetzine 10": "सेटज़िन 10",
    "Cetzine": "सेटज़िन",
    "Okacet 10": "ओकेसेट 10",
    "Okacet": "ओकेसेट",
    "Duphalac Syrup": "डुफालैक सिरप",
    "Duphalac": "डुफालैक",
    "Emeset 4": "एमेसेट 4",
    "Emeset": "एमेसेट",
    "Vomikind 4": "वोमीकाइंड 4",
    "Vomikind": "वोमीकाइंड",
    "Ondem 4": "ओंढम 4",
    "Ondem": "ओंढम",
    "Limcee": "लिमसी",
    "Novamox": "नोवामॉक्स",
    "Glycomet": "ग्लाइकोमेट",
    "Cheston Cold": "चेस्टन कोल्ड",
    "Wikoryl": "विकोरिल",
    "D-Cold Total": "डी-कोल्ड टोटल",
    "Febrex Plus": "फेबरेक्स प्लस",
    "Solvin Cold": "सोल्विन कोल्ड",
    "Cremaffin": "क्रीमफिन",
    "Softovac": "सॉफ्टोवैक",
    "Kayam": "कायम",
    "Dulcolax": "डल्कोलैक्स",
    "Voveran 50": "वोवेरान 50",
    "Voveran": "वोवेरान",
    "Dynapar 50": "डायनापार 50",
    "Dynapar": "डायनापार",
    "Amrutanjan": "अमृतांजन",
    "Zandu Balm": "झंडू बाम",
    "Zandu": "झंडू",
    "Tiger Balm": "टाइगर बाम",
    "Relispray": "रेलिस्प्रे",
    "Iodex": "आयोडेक्स",
    "Nucoxia 90": "न्यूकॉक्सिया 90",
    "Nucoxia": "न्यूकॉक्सिया",
    "Arcoxia 90": "आर्कोक्सिया 90",
    "Etoshine 90": "एटोशाइन 90",
    "Electral Powder": "इलेक्ट्रल पाउडर",
    "Electral Orange": "इलेक्ट्रल ऑरेंज",
    "Electral": "इलेक्ट्रल",
    "Eno Fruit Salt Lemon": "ईनो फ्रूट साल्ट लेमन",
    "Eno Fruit Salt Regular": "ईनो फ्रूट साल्ट रेगुलर",
    "Eno": "ईनो",
    "Evion 400": "एवियन 400",
    "Evion": "एवियन",
    "Foracort 200 Inhaler": "फोराकोर्ट 200 इनहेलर",
    "Foracort": "फोराकोर्ट",
    "Glycomet-SR 500": "ग्लाइकोमेट-एसआर 500",
    "Moov Pain Relief Cream": "मूव पेन रिलीफ क्रीम",
    "Moov": "मूव",
    "Neurobion Forte": "न्यूरोबियन फोर्ट",
    "Neurobion": "न्यूरोबियन",
    "Becosules Capsules": "बीकोसूल्स कैप्सूल",
    "Becosules Z": "बीकोसूल्स जेड",
    "Becosules": "बीकोसूल्स",
    "Betadine 5% Ointment": "बिटाडिन 5% ऑइंटमेंट",
    "Betadine": "बिटाडिन",
    "Crocin 500": "क्रोसिन 500",
    "Crocin": "क्रोसिन",
    "Dolo 650": "डोलो 650",
    "Dolo": "डोलो",
    "Calpol 500": "कालपोल 500",
    "Calpol": "कालपोल",
    "Azithral": "अजिथ्राल",
    "Dettol Antiseptic Liquid": "डेटोल एंटीसेप्टिक लिक्विड",
    "Dettol": "डेटोल",
    "Ecosprin 75": "इकोस्पिरिन 75",
    "Ecosprin": "इकोस्पिरिन",
    "Combiflam": "कॉम्बीफ्लाम",
    "Clavam 625": "क्लैवम 625",
    "Clavam 375": "क्लैवम 375",
    "Clavam Dry Syrup": "क्लैवम ड्राई सिरप",
    "Clavam": "क्लैवम",
    "Augmentin 625 Duo": "ऑगमेंटिन 625 डुओ",
    "Augmentin 1000 Duo": "ऑगमेंटिन 1000 डुओ",
    "Augmentin DDS Syrup": "ऑगमेंटिन डीडीएस सिरप",
    "Augmentin": "ऑगमेंटिन",
    "Moxikind-CV 625": "मोक्सीकाइंड-सीवी 625",
    "Moxikind-CV Dry Syrup": "मोक्सीकाइंड-सीवी ड्राई सिरप",
    "Moxikind": "मोक्सीकाइंड",
  },
  te: {
    "Sinarest": "సినారెస్ట్",
    "Otrivin": "ఓట్రివిన్",
    "Nasivion": "నాసివియాన్",
    "Omez": "ఒమేజ్",
    "Pan 40": "ప్యాన్ 40",
    "Pan-D": "ప్యాన్-డి",
    "Pantocid": "పాంటోసిడ్",
    "Nexpro": "నెక్స్‌ప్రో",
    "Sompraz": "సోంప్రాజ్",
    "Razo-D": "రాజో-డి",
    "Digene": "డైజీన్",
    "Gelusil": "గెలుసిల్",
    "Volini": "వోలిని",
    "Meftal-Spas": "మెఫ్టాల్-స్పాస్",
    "Meftal": "మెఫ్టాల్",
    "Zerodol-SP": "జెరోడోల్-ఎస్పి",
    "Zerodol-P": "జెరోడోల్-పి",
    "Zerodol": "జెరోడోల్",
    "Chymoral Forte": "కైమోరాల్ ఫోర్ట్",
    "Benadryl": "బెనాడ్రిల్",
    "Ascoril LS": "అస్కోరిల్ ఎల్‌ఎస్",
    "Montair-LC": "మోంటైర్-ఎల్సి",
    "Allegra": "అల్లెగ్రా",
    "Cetzine": "సెట్జిన్",
    "Okacet": "ఒకాసెట్",
    "Duphalac": "డుఫాలాక్",
    "Emeset": "ఎమిసెట్",
    "Vomikind": "వోమికైండ్",
    "Ondem": "ఆండెమ్",
    "Limcee": "లిమ్సీ",
    "Novamox": "నోవామాక్స్",
    "Glycomet": "గ్లైకోమెట్",
    "Cremaffin": "క్రీమాఫిన్",
    "Softovac": "సాఫ్టోవాక్",
    "Kayam": "కాయమ్",
    "Dulcolax": "డల్కోలాక్స్",
    "Voveran": "వోవెరాన్",
    "Dynapar": "డైనాపార్",
    "Amrutanjan": "అమృతాంజన్",
    "Zandu": "ఝాండు",
    "Tiger Balm": "టైగర్ బామ్",
    "Iodex": "అయోడెక్స్",
    "Electral Powder": "ఎలక్ట్రాల్ పౌడర్",
    "Electral": "ఎలక్ట్రాల్",
    "Eno Fruit Salt Lemon": "ఈనో ఫ్రూట్ సాల్ట్ లెమన్",
    "Eno Fruit Salt Regular": "ఈనో ఫ్రూట్ సాల్ట్ రెగ్యులర్",
    "Eno": "ఈనో",
    "Evion 400": "ఎవియాన్ 400",
    "Evion": "ఎవియాన్",
    "Foracort 200 Inhaler": "ఫోరాకార్ట్ 200 ఇన్హేలర్",
    "Foracort": "ఫోరాకార్ట్",
    "Glycomet-SR 500": "గ్లైకోమెట్-ఎస్‌ఆర్ 500",
    "Moov Pain Relief Cream": "మూవ్ పెయిన్ రిలీఫ్ క్రీమ్",
    "Moov": "మూవ్",
    "Neurobion Forte": "న్యూరోబియాన్ ఫోర్ట్",
    "Neurobion": "న్యూరోబియాన్",
    "Becosules Capsules": "బెకోసల్స్ క్యాప్సూల్స్",
    "Becosules": "బెకోసల్స్",
    "Betadine": "బెటాడిన్",
    "Crocin 500": "క్రోసిన్ 500",
    "Crocin": "క్రోసిన్",
    "Dolo 650": "డోలో 650",
    "Dolo": "డోలో",
    "Calpol 500": "కాల్పోల్ 500",
    "Calpol": "కాల్పోల్",
    "Dettol Antiseptic Liquid": "డెట్టాల్ యాంటీసెప్టిక్ లిక్విడ్",
    "Dettol": "డెట్టాల్",
    "Ecosprin 75": "ఈకోస్ప్రిన్ 75",
    "Ecosprin": "ఈకోస్ప్రిన్",
    "Clavam 625": "క్లావమ్ 625",
    "Clavam 375": "క్లావమ్ 375",
    "Clavam Dry Syrup": "క్లావమ్ డ్రై సిరప్",
    "Clavam": "క్లావమ్",
    "Augmentin 625 Duo": "ఆగ్మెంటిన్ 625 డుఓ",
    "Augmentin 1000 Duo": "ఆగ్మెంటిన్ 1000 డుఓ",
    "Augmentin DDS Syrup": "ఆగ్మెంటిన్ డిడిఎస్ సిరప్",
    "Augmentin": "ఆగ్మెంటిన్",
    "Moxikind-CV 625": "మోక్సికైండ్-సివి 625",
    "Moxikind-CV Dry Syrup": "మోక్సికైండ్-సివి డ్రై సిరప్",
    "Moxikind": "మోక్సికైండ్",
  },
  ml: {
    "Crocin 500": "ക്രോസിൻ 500",
    "Crocin": "ക്രോസിൻ",
    "Dolo 650": "ഡോളോ 650",
    "Dolo 500": "ഡോളോ 500",
    "Dolo": "ഡോളോ",
    "Calpol 500": "കാൽപോൾ 500",
    "Calpol 650": "കാൽപോൾ 650",
    "Calpol": "കാൽപോൾ",
    "Sinarest": "സിനാറെസ്റ്റ്",
    "Otrivin": "ഒട്രിവിൻ",
    "Nasivion": "നാസിവിയോൺ",
    "Omez": "ഒമെസ്",
    "Pan 40": "പാൻ 40",
    "Pan-D": "പാൻ-ഡി",
    "Pantocid": "പന്റോസിഡ്",
    "Nexpro": "നെക്സ്പ്രോ",
    "Sompraz": "സോംപ്രാസ്",
    "Razo-D": "റാസോ-ഡി",
    "Digene": "ഡൈജീൻ",
    "Gelusil": "ഗെലുസിൽ",
    "Volini": "വോളിനി",
    "Meftal-Spas": "മെഫ്റ്റാൽ-സ്പാസ്",
    "Meftal": "മെഫ്റ്റാൽ",
    "Zerodol-SP": "സെറോഡോൾ-എസ്പി",
    "Zerodol-P": "സെറോഡോൾ-പി",
    "Zerodol": "സെറോഡോൾ",
    "Chymoral Forte": "കൈമോറാൽ ഫോർട്ട്",
    "Benadryl": "ബെനാഡ്രിൽ",
    "Ascoril LS": "അസ്കോരിൽ എൽഎസ്",
    "Montair-LC": "മോണ്ടെയർ-എൽസി",
    "Allegra": "അലെഗ്ര",
    "Cetzine": "സെറ്റ്സിൻ",
    "Okacet": "ഒകാസെറ്റ്",
    "Duphalac": "ഡ്വാഫലാക്",
    "Emeset": "എമിസെറ്റ്",
    "Vomikind": "വോമികൈൻഡ്",
    "Ondem": "ഓണ്ടെം",
    "Limcee": "ലിംസി",
    "Novamox": "നോവാമോക്സ്",
    "Glycomet": "ഗ്ലൈക്കോമെറ്റ്",
    "Cremaffin": "ക്രീമാഫിൻ",
    "Softovac": "സോഫ്റ്റോവാക്",
    "Kayam": "കായം",
    "Dulcolax": "ഡൾക്കോളാക്സ്",
    "Voveran": "വോവെറാൻ",
    "Dynapar": "ഡൈനാപാർ",
    "Amrutanjan": "അമൃതാംജൻ",
    "Zandu": "ഝാണ്ടു",
    "Tiger Balm": "ടൈഗർ ബാം",
    "Iodex": "അയോഡെക്സ്",
    "Electral Powder": "ഇലക്ട്രൽ പൗഡർ",
    "Electral": "ഇലക്ട്രൽ",
    "Eno Fruit Salt Lemon": "ഈനോ ഫ്രൂട്ട് സാൾട്ട് ലെമൺ",
    "Eno Fruit Salt Regular": "ഈനോ ഫ്രൂട്ട് സാൾട്ട് റെഗുലർ",
    "Eno": "ഈനോ",
    "Evion 400": "എവിയോൺ 400",
    "Evion": "എവിയോൺ",
    "Foracort 200 Inhaler": "ഫോറാകോർട്ട് 200 ഇൻഹേലർ",
    "Foracort": "ഫോറാകോർട്ട്",
    "Glycomet-SR 500": "ഗ്ലൈക്കോമെറ്റ്-എസ്ആർ 500",
    "Clavam 625": "ക്ലാവം 625",
    "Clavam 375": "ക്ലാവം 375",
    "Clavam Dry Syrup": "ക്ലാവം ഡ്രൈ സിറപ്പ്",
    "Clavam": "ക്ലാവം",
    "Augmentin 625 Duo": "ഓഗ്മെന്റിൻ 625 ഡ്യുവോ",
    "Augmentin 1000 Duo": "ഓഗ്മെന്റിൻ 1000 ഡ്യുവോ",
    "Augmentin DDS Syrup": "ഓഗ്മെന്റിൻ ഡിഡിഎസ് സിറപ്പ്",
    "Augmentin": "ഓഗ്മെന്റിൻ",
    "Moxikind-CV 625": "മോക്സികൈൻഡ്-സിവി 625",
    "Moxikind-CV Dry Syrup": "മോക്സികൈൻഡ്-സിവി ഡ്രൈ സിറപ്പ്",
    "Moxikind": "മോക്സികൈൻഡ്",
  },
  kn: {
    "Crocin 500": "ಕ್ರೋಸಿನ್ 500",
    "Crocin": "ಕ್ರೋಸಿನ್",
    "Dolo 650": "ಡೋಲೋ 650",
    "Dolo 500": "ಡೋಲೋ 500",
    "Dolo": "ಡೋಲೋ",
    "Calpol 500": "ಕಾಲ್ಪೋಲ್ 500",
    "Calpol 650": "ಕಾಲ್ಪೋಲ್ 650",
    "Calpol": "ಕಾಲ್ಪೋಲ್",
    "Sinarest": "ಸಿನಾರೆಸ್ಟ್",
    "Otrivin": "ಒಟ್ರಿವಿನ್",
    "Nasivion": "ನಾಸಿಬಿಯಾನ್",
    "Omez": "ಒಮೆಜ್",
    "Pan 40": "ಪ್ಯಾನ್ 40",
    "Pan-D": "ಪ್ಯಾನ್-ಡಿ",
    "Pantocid": "ಪ್ಯಾಂಟೋಸಿಡ್",
    "Nexpro": "ನೆಕ್ಸ್ಪ್ರೋ",
    "Sompraz": "સોમ્પ್ರಾಜ್",
    "Razo-D": "ರಾಝೋ-ಡಿ",
    "Digene": "ಡೈಜೀನ್",
    "Gelusil": "ಗೆಲುಸಿಲ್",
    "Volini": "ವೊಲಿನಿ",
    "Meftal-Spas": "ಮೆಫ್ಟಾಲ್-ಸ್ಪಾಸ್",
    "Meftal": "ಮೆಫ್ಟಾಲ್",
    "Zerodol-SP": "ಝೆರೋಡಾಲ್-ಎಸ್ಪಿ",
    "Zerodol-P": "ಝೆರೋಡಾಲ್-ಎಸ್ಪಿ",
    "Zerodol": "ಝೆರೋಡಾಲ್",
    "Chymoral Forte": "ಕೈಮೋರಾಲ್ ಫೋರ್ಟ್",
    "Benadryl": "ಬೆನಾಡ್ರಿಲ್",
    "Ascoril LS": "ಅಸ್ಕೋರಿಲ್ ಎಲ್‌ಎಸ್",
    "Montair-LC": "ಮಾಂಟೇರ್-ಎಲ್‌ಸಿ",
    "Allegra": "ಅಲೆಗ್ರಾ",
    "Cetzine": "ಸೆಟ್ಜಿನ್",
    "Okacet": "ಒಕಾಸೆಟ್",
    "Duphalac": "ಡುಫಾಲಾಕ್",
    "Emeset": "ಎಮಿಸೆಟ್",
    "Vomikind": "ವೊಮಿಕೈಂಡ್",
    "Ondem": "ಒಂಡೆಮ್",
    "Limcee": "ಲಿಮ್ಸಿ",
    "Novamox": "ನೋವಾಮಾಕ್ಸ್",
    "Glycomet": "ಗ್ಲೈಕೋಮೆಟ್",
    "Cremaffin": "ಕ್ರೀಮಾಫಿನ್",
    "Softovac": "ಸಾಫ್ಟೋವಾಕ್",
    "Kayam": "ಕಾಯಮ್",
    "Dulcolax": "ಡಲ್ಕೋಲ್ಯಾಕ್ಸ್",
    "Voveran": "ವೋವೆರಾನ್",
    "Dynapar": "ಡೈನಾಪಾರ್",
    "Amrutanjan": "ಅಮೃತಾಂಜನ್",
    "Zandu": "ಝಾಂಡು",
    "Tiger Balm": "ಟೈಗರ್ ಬಾಮ್",
    "Iodex": "ಅಯೋಡೆಕ್ಸ್",
    "Electral Powder": "ಎಲೆಕ್ಟ್ರಾಲ್ ಪೌಡರ್",
    "Electral": "ಎಲೆಕ್ಟ್ರಾಲ್",
    "Eno Fruit Salt Lemon": "ಇನೋ ಫ್ರೂಟ್ ಸಾಲ್ಟ್ ಲೆಮನ್",
    "Eno Fruit Salt Regular": "ಇನೋ ಫ್ರೂಟ್ ಸಾಲ್ಟ್ ರೆಗ್ಯುಲರ್",
    "Eno": "ಇನೋ",
    "Evion 400": "ಎವಿಯಾನ್ 400",
    "Evion": "ಎವಿಯಾನ್",
    "Foracort 200 Inhaler": "ಫೊರಾಕಾರ್ಟ್ 200 ಇನ್ಹೇಲರ್",
    "Foracort": "ಫೊರಾಕಾರ್ಟ್",
    "Glycomet-SR 500": "ಗ್ಲೈಕೋಮೆಟ್-ಎಸ್ಆರ್ 500",
    "Glycomet": "ಗ್ಲೈಕೋಮೆಟ್",
    "Clavam 625": "ಕ್ಲಾವಮ್ 625",
    "Clavam 375": "ಕ್ಲಾವಮ್ 375",
    "Clavam Dry Syrup": "ಕ್ಲಾವಮ್ ಡ್ರೈ ಸಿಲಪ್",
    "Clavam": "ಕ್ಲಾವಮ್",
    "Augmentin 625 Duo": "ಆಗ್ಮೆಂಟಿನ್ 625 ಡ್ಯುಯೊ",
    "Augmentin 1000 Duo": "ಆಗ್ಮೆಂಟಿನ್ 1000 ಡ್ಯುಯೊ",
    "Augmentin DDS Syrup": "ಆಗ್ಮೆಂಟಿನ್ ಡಿಡಿಎಸ್ ಸಿರೆಪ್",
    "Augmentin": "ಆಗ್ಮೆಂಟಿನ್",
    "Moxikind-CV 625": "ಮೊಕ್ಸಿಕೈಂಡ್-ಸಿವಿ 625",
    "Moxikind-CV Dry Syrup": "ಮೊಕ್ಸಿಕೈಂಡ್-ಸಿವಿ ಡ್ರೈ ಸಿರೆಪ್",
    "Moxikind": "ಮೊಕ್ಸಿಕೈಂಡ್",
  },
};

const GENERIC_NAME_MAPS = {
  ta: {
    "Paracetamol": "பாரசிட்டமால்",
    "Ibuprofen + Paracetamol": "ஐபூபுரோஃபென் + பாரசிட்டமால்",
    "Aceclofenac + Paracetamol": "அசெக்லோஃபெனாக் + பாரசிட்டமால்",
    "Aceclofenac + Paracetamol + Serratiopeptidase": "அசெக்லோஃபெனாக் + பாரசிட்டமால் + செரேஷியோபெப்டிடேஸ்",
    "Mefenamic Acid + Dicyclomine": "மெஃபெனமிக் அமிலம் + டைசைக்ளோமைன்",
    "Diclofenac Sodium / Potassium": "டைக்ளோஃபெனாக் சோடியம் / பொட்டாசியம்",
    "Etoricoxib": "எடோரிகாக்சிப்",
    "Thiocolchicoside + Aceclofenac + Paracetamol": "தியோகால்சிகோசைடு + அசெக்லோஃபெனாக் + பாரசிட்டமால்",
    "Trypsin + Chymotrypsin": "டிரிப்சின் + கைமோடிரிப்சின்",
    "Cetirizine Hydrochloride": "செட்ரிசின் ஹைட்ரோகுளோரைடு",
    "Cetirizine": "செட்ரிசின்",
    "Levocetirizine": "லெவோசெட்ரிசின்",
    "Montelukast + Levocetirizine": "மாண்டெலூகாஸ்ட் + லெவோசெட்ரிசின்",
    "Fexofenadine": "ஃபெக்சோஃபெனடைன்",
    "Dextromethorphan + Chlorpheniramine + Phenylephrine": "டெக்ஸ்ட்ரோமெதோர்பான் + குளோர்பெனிரமைன் + ஃபெனிலெஃப்ரின்",
    "Ambroxol + Levosalbutamol + Guaifenesin": "அம்ப்ராக்சால் + லெவோசல்பியூடமால் + குவைஃபெனசின்",
    "Paracetamol + Phenylephrine + Chlorpheniramine": "பாரசிட்டமால் + ஃபெனிலெஃப்ரின் + குளோர்பெனிரமைன்",
    "Xylometazoline Hydrochloride": "சைலோமெடசோலின் ஹைட்ரோகுளோரைடு",
    "Omeprazole": "ஓமிபிரசோல்",
    "Esomeprazole": "எஸோமிபிரசோல்",
    "Pantoprazole": "பேன்டோபிரசோல்",
    "Pantoprazole + Domperidone": "பேன்டோபிரசோல் + டாம்பரிடோன்",
    "Rabeprazole + Domperidone": "ராபிபிரசோல் + டாம்பரிடோன்",
    "Magaldrate + Simethicone": "மகால்ட்ரேட் + சிமெதிகோன்",
    "Oral Rehydration Salts (WHO Formula)": "வாய்வழி நீர்சத்து உப்புகள் (WHO ஃபார்முலா)",
    "Oral Rehydration Salts": "வாய்வழி நீர்சத்து உப்புகள்",
    "ORS (Oral Rehydration Salts)": "ஓஆர்எஸ் (வாய்வழி நீர்சத்து உப்புகள்)",
    "Lactulose": "லாக்டுலோஸ்",
    "Ondansetron": "ஆன்டன்செட்ரான்",
    "Amoxicillin + Clavulanic Acid": "அமோக்சிசிலின் + க்ளவுலானிக் அமிலம்",
    "Amoxicillin and Potassium Clavulanate Tablets IP": "அமோக்சிசிலின் மற்றும் பொட்டாசியம் க்ளவுலானேட் மாத்திரைகள் IP",
    "Amoxicillin and Potassium Clavulanate": "அமோக்சிசிலின் மற்றும் பொட்டாசியம் க்ளவுலானேட்",
    "Amoxicillin": "அமோக்சிசிலின்",
    "Metformin Hydrochloride": "மெட்ஃபோர்மின் ஹைட்ரோகுளோரைடு",
    "Metformin": "மெட்ஃபோர்மின்",
    "Povidone Iodine": "போவிடோன் அயோடின்",
    "Chloroxylenol": "குளோராக்சிலீனால்",
    "Aspirin": "ஆஸ்பிரின்",
    "Vitamin C (Ascorbic Acid)": "வைட்டமின் C (அஸ்கார்பிக் அமிலம்)",
    "Vitamin E (Tocopheryl Acetate)": "வைட்டமின் E (டோகோஃபெரைல் அசிட்டேட்)",
    "Formoterol + Budesonide": "ஃபார்மோடேரால் + புடசோனைடு",
    "Turpentine Oil + Nilgiri Oil + Wintergreen Oil": "டர்பன்டைன் எண்ணெய் + நீலகிரி எண்ணெய் + வின்டர்கிரீன் எண்ணெய்",
    "Vitamin B-Complex + Cyanocobalamin": "வைட்டமின் பி-காம்பளக்ஸ் + சயனோகோபாலமின்",
    "Vitamin B-Complex + Zinc": "வைட்டமின் பி-காம்பளக்ஸ் + துத்தநாகம்",
  },
  hi: {
    "Paracetamol": "पैरासिटामोल",
    "Ibuprofen + Paracetamol": "इबूप्रोफेन + पैरासिटामोल",
    "Aceclofenac + Paracetamol": "एक्लोफेनाक + पैरासिटामोल",
    "Aceclofenac + Paracetamol + Serratiopeptidase": "एक्लोफेनाक + पैरासिटामोल + सेराटियोपेप्टिडेज",
    "Mefenamic Acid + Dicyclomine": "मेफेनामिक एसिड + डाइसाइक्लोमाइन",
    "Diclofenac Sodium / Potassium": "डिक्लोफेनाक सोडियम / पोटेशियम",
    "Etoricoxib": "इटोरिकोक्सिब",
    "Thiocolchicoside + Aceclofenac + Paracetamol": "थियोकोल्चिकोसाइड + एक्लोफेनाक + पैरासिटामोल",
    "Trypsin + Chymotrypsin": "ट्रिप्सिन + काइमोट्रिप्सिन",
    "Cetirizine Hydrochloride": "सेटिरिजिन हाइड्रोक्लोराइड",
    "Cetirizine": "सेटिरिजिन",
    "Levocetirizine": "लेवोसेटिरिजिन",
    "Montelukast + Levocetirizine": "मोंटेलुकास्ट + लेवोसेटिरिजिन",
    "Fexofenadine": "फेक्सोफेनाडाइन",
    "Dextromethorphan + Chlorpheniramine + Phenylephrine": "डेक्सट्रोमेथॉर्फन + क्लोरफेनिरामाइन + फेनिलफ्रीन",
    "Ambroxol + Levosalbutamol + Guaifenesin": "एम्ब्रॉक्सोल + लेवोसालबुटामोल + गुआइफेनेसिन",
    "Paracetamol + Phenylephrine + Chlorpheniramine": "पैरासिटामोल + फेनिलफ्रीन + क्लोरफेनिरामाइन",
    "Xylometazoline Hydrochloride": "जाइलोमेटाजोलिन हाइड्रोक्लोराइड",
    "Omeprazole": "ओमेप्राजोल",
    "Esomeprazole": "इसोमेप्राजोल",
    "Pantoprazole": "पेंटोप्राजोल",
    "Pantoprazole + Domperidone": "पेंटोप्राजोल + डोमपेरिडोन",
    "Rabeprazole + Domperidone": "रेबेप्राजोल + डोमपेरिडोन",
    "Magaldrate + Simethicone": "मगालड्रेट + सिमेथिकोन",
    "Oral Rehydration Salts (WHO Formula)": "ओरल रीहाइड्रेशन साल्ट्स (WHO फार्मूला)",
    "Oral Rehydration Salts": "ओरल रीहाइड्रेशन साल्ट्स",
    "Lactulose": "लक्टुलोज",
    "Ondansetron": "ओंडांसेट्रॉन",
    "Amoxicillin + Clavulanic Acid": "अमोक्सीसिलिन + क्लैवुलेनिक एसिड",
    "Amoxicillin and Potassium Clavulanate Tablets IP": "अमोक्सीसिलिन और पोटेशियम क्लावुलानेट टैबलेट्स आईपी",
    "Amoxicillin and Potassium Clavulanate": "अमोक्सीसिलिन और पोटेशियम क्लावुलानेट",
    "Amoxicillin": "अमोक्सीसिलिन",
    "Metformin Hydrochloride": "मेटफॉर्मिन हाइड्रोक्लोराइड",
    "Metformin": "मेटफॉर्मिन",
    "Povidone Iodine": "पोविडोन आयोडीन",
    "Chloroxylenol": "क्लोरोक्सीलेनॉल",
    "Aspirin": "एस्पिरिन",
    "Vitamin C (Ascorbic Acid)": "विटामिन C (एस्कॉर्बिक एसिड)",
    "Vitamin E (Tocopheryl Acetate)": "विटामिन E (टोकोफेरिल एसीटेट)",
    "Formoterol + Budesonide": "फॉर्मोटेरोल + बुडेसोनाइड",
    "Turpentine Oil + Nilgiri Oil + Wintergreen Oil": "तारपीन का तेल + नीलगिरी का तेल + विंटरग्रीन तेल",
    "Vitamin B-Complex + Cyanocobalamin": "विटामिन बी-कॉम्प्लेक्स + सायनोकोबालामिन",
    "Vitamin B-Complex + Zinc": "विटामिन बी-कॉम्प्लेक्स + जिंक",
  },
  te: {
    "Paracetamol": "పారాసిటమాల్",
    "Ibuprofen + Paracetamol": "ఐబుప్రోఫెన్ + పారాసిటమాల్",
    "Aceclofenac + Paracetamol": "ఎస్‌క్లోఫెనాక్ + పారాసిటమాల్",
    "Aceclofenac + Paracetamol + Serratiopeptidase": "ఎస్‌క్లోఫెనాక్ + పారాసిటమాల్ + సెరాటియోపెప్టిడేస్",
    "Mefenamic Acid + Dicyclomine": "మెఫెనామిక్ యాసిడ్ + డైసైక్లోమైన్",
    "Diclofenac": "డిక్లోఫెనాక్",
    "Etoricoxib": "ఎటోరికోక్సిబ్",
    "Cetirizine": "సెటిరిజైన్",
    "Levocetirizine": "లెవోసెటిరిజైన్",
    "Montelukast + Levocetirizine": "మోంటెల్యూకాస్ట్ + లెవోసెటిరిజైన్",
    "Fexofenadine": "ఫెక్సోఫెనాడైన్",
    "Omeprazole": "ఒమెప్రాజోల్",
    "Pantoprazole": "పాంటోప్రాజోల్",
    "Magaldrate + Simethicone": "మగాల్డ్రేట్ + సిమెథికోన్",
    "Oral Rehydration Salts (WHO Formula)": "ఓరల్ రీహైడ్రేషన్ సాల్ట్స్ (WHO ఫార్ములా)",
    "Oral Rehydration Salts": "ఓరల్ రీహైడ్రేషన్ సాల్ట్స్",
    "Ondansetron": "ఒండన్‌సెట్రాన్",
    "Amoxicillin and Potassium Clavulanate Tablets IP": "అమోక్సిసిలిన్ మరియు పొటాషియం క్లావులనేట్ టాబ్లెట్లు IP",
    "Amoxicillin and Potassium Clavulanate": "అమోక్సిసిలిన్ మరియు పొటాషియం క్లావులనేట్",
    "Amoxicillin + Clavulanic Acid": "అమోక్సిసిలిన్ + క్లావులనిక్ యాసిడ్",
    "Amoxicillin": "అమోక్సిసిలిన్",
    "Metformin Hydrochloride": "మెట్‌ఫార్మిన్ హైడ్రోక్లోరైడ్",
    "Metformin": "మెట్‌ఫార్మిన్",
  },
  ml: {
    "Paracetamol": "പാരസിറ്റമോൾ",
    "Ibuprofen + Paracetamol": "ഐബുപ്രോഫെൻ + പാരസിറ്റമോൾ",
    "Aceclofenac + Paracetamol": "അസെക്ലോഫെനാക് + പാരസിറ്റമോൾ",
    "Mefenamic Acid + Dicyclomine": "മെഫെനാമിക് ആസിഡ് + ഡൈസൈക്ലോമൈൻ",
    "Cetirizine": "സെറ്റിരിസിൻ",
    "Levocetirizine": "ലെവോസെറ്റിരിസിൻ",
    "Montelukast + Levocetirizine": "മോണ്ടെലൂക്കാസ്റ്റ് + ലെവോസെറ്റിരിസിൻ",
    "Fexofenadine": "ഫെക്സോഫെനാഡിൻ",
    "Omeprazole": "ഒമേപ്രാസോൾ",
    "Pantoprazole": "പന്റോപ്രാസോൾ",
    "Magaldrate + Simethicone": "മഗാൽഡ്രേറ്റ് + സിമെത്തിക്കോൺ",
    "Oral Rehydration Salts (WHO Formula)": "ഓറൽ റീഹൈഡ്രേഷൻ സാൾട്ട്സ് (WHO ഫോർമുല)",
    "Oral Rehydration Salts": "ഓറൽ റീഹൈഡ്രേഷൻ സാൾട്ട്സ്",
    "Ondansetron": "ഒൻഡാൻസെട്രോൺ",
    "Amoxicillin and Potassium Clavulanate Tablets IP": "അമോക്സിസിലിൻ ഒപ്പം പൊട്ടാസ്യം ക്ലാവുലനേറ്റ് ഗുളികകൾ IP",
    "Amoxicillin and Potassium Clavulanate": "അമോക്സിസിലിൻ ഒപ്പം പൊട്ടാസ്യം ക്ലാവുലനേറ്റ്",
    "Amoxicillin + Clavulanic Acid": "അമോക്സിസിലിൻ + ക്ലാവുലനിക് ആസിഡ്",
    "Amoxicillin": "അമോക്സിസിലിൻ",
    "Metformin Hydrochloride": "മെറ്റ്ഫോർമിൻ ഹൈഡ്രോക്ലോറൈഡ്",
    "Metformin": "മെറ്റ്ഫോർമിൻ",
  },
  kn: {
    "Paracetamol": "ಪ್ಯಾರಾಸಿಟಮಾಲ್",
    "Ibuprofen + Paracetamol": "ಐಬುಪ್ರೊಫೆನ್ + ಪ್ಯಾರಾಸಿಟಮಾಲ್",
    "Aceclofenac + Paracetamol": "ಅಸೆಕ್ಲೋಫೆನಾಕ್ + ಪ್ಯಾರಾಸಿಟಮಾಲ್",
    "Mefenamic Acid + Dicyclomine": "ಮೆಫೆನಾಮಿಕ್ ಆಸಿಡ್ + ಡೈಸೈಕ್ಲೋಮೈನ್",
    "Cetirizine": "ಸೆಟಿರಿಜಿನ್",
    "Levocetirizine": "ಲೆವೋಸೆಟಿರಿಜಿನ್",
    "Montelukast + Levocetirizine": "ಮಾಂಟೆಲುಕಾಸ್ಟ್ + ಲೆವೋಸೆಟಿರಿಜಿನ್",
    "Fexofenadine": "ಫೆಕ್ಸೋಫೆನಾಡೈನ್",
    "Omeprazole": "ಒಮೆಪ್ರಾಜೋಲ್",
    "Pantoprazole": "ಪ್ಯಾಂಟೋಪ್ರಾಜೋಲ್",
    "Magaldrate + Simethicone": "ಮಗಾಲ್ಡ್ರೇಟ್ + ಸಿಮೆಥಿಕೋನ್",
    "Oral Rehydration Salts (WHO Formula)": "ಓರಲ್ ರೀಹೈಡ್ರೇಷನ್ ಸಾಲ್ಟ್ಸ್ (WHO ಫಾರ್ಮುಲಾ)",
    "Oral Rehydration Salts": "ಓರಲ್ ರೀಹೈಡ್ರೇಷನ್ ಸಾಲ್ಟ್ಸ್",
    "Ondansetron": "ಒಂಡಾನ್ಸೆಟ್ರಾನ್",
    "Amoxicillin and Potassium Clavulanate Tablets IP": "ಅಮೊಕ್ಸಿಸಿಲಿನ್ ಮತ್ತು ಪೊಟ್ಯಾಸಿಯಮ್ ಕ್ಲಾವ್ಯುಲನೇಟ್ ಮಾತ್ರೆಗಳು IP",
    "Amoxicillin and Potassium Clavulanate": "ಅಮೊಕ್ಸಿಸಿಲಿನ್ ಮತ್ತು ಪೊಟ್ಯಾಸಿಯಮ್ ಕ್ಲಾವ್ಯುಲನೇಟ್",
    "Amoxicillin + Clavulanic Acid": "ಅಮೊಕ್ಸಿಸಿಲಿನ್ + ಕ್ಲಾವ್ಯುಲನಿಕ್ ಆಸಿಡ್",
    "Amoxicillin": "ಅಮೊಕ್ಸಿಸಿಲಿನ್",
    "Metformin Hydrochloride": "ಮೆಟ್‌ಫಾರ್ಮಿನ್ ಹೈಡ್ರೋಕ್ಲೋರೈಡ್",
    "Metformin": "ಮೆಟ್‌ಫಾರ್ಮಿನ್",
  },
};

const MANUFACTURER_MAPS = {
  ta: {
    "Micro Labs": "மைக்ரோ லேப்ஸ்",
    "Sanofi India": "சனோஃபி இந்தியா",
    "Sanofi": "சனோஃபி",
    "Abbott": "அபாட்",
    "Ipca Laboratories": "இப்கா லேபரட்டரீஸ்",
    "Ipca": "இப்கா",
    "Blue Cross Laboratories": "ப்ளூ க்ராஸ் லேபரட்டரீஸ்",
    "Blue Cross": "ப்ளூ க்ராஸ்",
    "Wockhardt": "வோக்ஹார்ட்",
    "Indoco Remedies": "இண்டோகோ ரெமிடிஸ்",
    "Wallace Pharmaceuticals": "வாலஸ் பார்மாசிட்டிகல்ஸ்",
    "Novartis": "நோவார்டிஸ்",
    "Troikaa Pharmaceuticals": "டிரோய்கா பார்மாசிட்டிகல்ஸ்",
    "Torrent Pharmaceuticals": "டொரண்ட் பார்மாசிட்டிகல்ஸ்",
    "Torrent": "டொரண்ட்",
    "Amrutanjan Healthcare": "அம்ருதாஞ்சன் ஹெல்த்கேர்",
    "Amrutanjan": "அம்ருதாஞ்சன்",
    "Emami": "இமாமி",
    "Haw Par": "ஹா பார்",
    "Midas Care": "மிடாஸ் கேர்",
    "Zydus Cadila": "சைடஸ் கடிலா",
    "Zydus": "சைடஸ்",
    "Intas Pharmaceuticals": "இண்டாஸ் பார்மாசிட்டிகல்ஸ்",
    "Intas": "இண்டாஸ்",
    "Corona Remedies": "கொரோனா ரெமிடிஸ்",
    "Macleods Pharmaceuticals": "மெக்லியாட்ஸ் பார்மாசிட்டிகல்ஸ்",
    "Macleods": "மெக்லியாட்ஸ்",
    "Glenmark": "கிளென்மார்க்",
    "Hetero Healthcare": "ஹெடிரோ ஹெல்த்கேர்",
    "Hetero": "ஹெடிரோ",
    "Bayer": "பேயர்",
    "Johnson & Johnson": "ஜான்சன் & ஜான்சன்",
    "Centaur Pharmaceuticals": "சென்டார் பார்மாசிட்டிகல்ஸ்",
    "Centaur": "சென்டார்",
    "Alembic Pharmaceuticals": "அலெம்பிக் பார்மாசிட்டிகல்ஸ்",
    "Alembic": "அலெம்பிக்",
    "Procter & Gamble": "பி&ஜி ஹெல்த்",
    "P&G Health": "பி&ஜி ஹெல்த்",
    "P&G": "பி&ஜி",
    "German Remedies": "ஜெர்மன் ரெமிடிஸ்",
    "AstraZeneca": "அஸ்ட்ராஜெனகா",
    "Systopic Laboratories": "சிஸ்டோபிக் லேபரட்டரீஸ்",
    "Sheth Brothers": "சேத் பிரதர்ஸ்",
    "Dabur": "டாபர்",
    "Paras Pharmaceuticals": "பாராரஸ் பார்மாசிட்டிகல்ஸ்",
    "Alkem Laboratories": "அல்கெம் லேபரட்டரீஸ்",
    "Alkem Laboratories Ltd": "அல்கெம் லேபரட்டரீஸ் லிமிடெட்",
    "Alkem": "அல்கெம்",
    "FDC Limited": "எஃப்டிசி லிமிடெட்",
    "FDC Ltd": "எஃப்டிசி லிமிடெட்",
    "FDC": "எஃப்டிசி",
    "GSK": "ஜிஎஸ்கே",
    "GlaxoSmithKline": "கிளாக்சோஸ்மித்க்லைன்",
    "Merck / P&G Health": "மெர்க் / பி&ஜி ஹெல்த்",
    "Merck": "மெர்க்",
    "Cipla": "சிப்ளா",
    "Cipla Ltd": "சிப்ளா லிமிடெட்",
    "USV Private Limited": "யுஎஸ்வி பிரைவேட் லிமிடெட்",
    "USV Ltd": "யுஎஸ்வி லிமிடெட்",
    "USV": "யுஎஸ்வி",
    "Reckitt Benckiser": "ரெக்கிட் பென்கிசர்",
    "Pfizer": "ஃபைசர்",
    "Win-Medicare": "வின்-மெடிகேர்",
    "Sun Pharma": "சன் ஃபார்மா",
    "Dr. Reddy's": "டாக்டர் ரெட்டீஸ்",
    "Lupin": "லூபின்",
    "Mankind": "மேன்கைண்ட்",
    "Mankind Pharma": "மேன்கைண்ட் பார்மா",
  },
  hi: {
    "Micro Labs": "माइक्रो लैब्स",
    "Sanofi India": "सनोफी इंडिया",
    "Sanofi": "सनोफी",
    "Abbott": "एबॉट",
    "Ipca Laboratories": "इप्का लेबोरेटरीज",
    "Ipca": "इप्का",
    "Blue Cross Laboratories": "ब्लू क्रॉस लेबोरेटरीज",
    "Blue Cross": "ब्लू क्रॉस",
    "Wockhardt": "वोकहार्ड",
    "Indoco Remedies": "इंडोको रेमेडीज",
    "Wallace Pharmaceuticals": "वालेस फार्मास्युटिकल्स",
    "Novartis": "नोवार्टिस",
    "Troikaa Pharmaceuticals": "ट्रोइका फार्मास्युटिकल्स",
    "Torrent Pharmaceuticals": "टोरेंट फार्मास्युटिकल्स",
    "Torrent": "टोरेंट",
    "Amrutanjan Healthcare": "अमृतांजन हेल्थकेयर",
    "Amrutanjan": "अमृतांजन",
    "Emami": "इमामी",
    "Haw Par": "हॉ पार",
    "Midas Care": "मिडास केयर",
    "Zydus Cadila": "जाइडस कैडिला",
    "Zydus": "जाइडस",
    "Intas Pharmaceuticals": "इंटास फार्मास्युटिकल्स",
    "Intas": "इंटास",
    "Corona Remedies": "कोरोना रेमेडीज",
    "Macleods Pharmaceuticals": "मैकलेऑड्स फार्मास्युटिकल्स",
    "Macleods": "मैकलेऑड्स",
    "Glenmark": "ग्लेनमार्क",
    "Hetero Healthcare": "हेटेरो हेल्थकेयर",
    "Hetero": "हेटेरो",
    "Bayer": "बायर",
    "Johnson & Johnson": "जॉनसन एंड जॉनसन",
    "Centaur Pharmaceuticals": "सेंटौर फार्मास्युटिकल्स",
    "Centaur": "सेंटौर",
    "Alembic Pharmaceuticals": "अलेम्बिक फार्मास्युटिकल्स",
    "Alembic": "अलेम्बिक",
    "Procter & Gamble": "पीएंडजी हेल्थ",
    "P&G Health": "पीएंडजी हेल्थ",
    "P&G": "पीएंडजी",
    "German Remedies": "जर्मन रेमेडीज",
    "AstraZeneca": "एस्ट्राजेनेका",
    "Systopic Laboratories": "सिस्टोपिक लेबोरेटरीज",
    "Sheth Brothers": "सेठ ब्रदर्स",
    "Dabur": "डाबर",
    "Paras Pharmaceuticals": "पारस फार्मास्युटिकल्स",
    "Alkem Laboratories": "अल्केम लेबोरेटरीज",
    "Alkem Laboratories Ltd": "अल्केम लेबोरेटरीज लिमिटेड",
    "Alkem": "अल्केम",
    "FDC Limited": "एफडीसी लिमिटेड",
    "GSK": "जीएसके",
    "GlaxoSmithKline": "ग्लेक्सोस्मिथक्लाइन",
    "Merck / P&G Health": "मर्क / पीएंडजी हेल्थ",
    "P&G Health": "पीएंडजी हेल्थ",
    "Cipla": "सिप्ला",
    "USV Private Limited": "यूएसवी प्राइवेट लिमिटेड",
    "Reckitt Benckiser": "रेकिट बेंकिजर",
    "Pfizer": "फाइजर",
    "Win-Medicare": "विन-मेडीकेयर",
    "Sun Pharma": "सन फार्मा",
    "Dr. Reddy's": "डॉ. रेड्डीज",
    "Lupin": "लुपिन",
    "Mankind": "मैनकाइंड",
    "Mankind Pharma": "मैनकाइंड फार्मा",
  },
  te: {
    "Micro Labs": "మైక్రో ల్యాబ్స్",
    "Sanofi India": "సనోఫీ ఇండియా",
    "Sanofi": "సనోఫీ",
    "Abbott": "అబాట్",
    "Ipca Laboratories": "ఇప్కా ల్యాబొరేటరీస్",
    "Blue Cross Laboratories": "బ్లూ క్రాస్ ల్యాబొరేటరీస్",
    "Wockhardt": "వోకార్డ్",
    "Torrent Pharmaceuticals": "టోరెంట్ ఫార్మాస్యూటికల్స్",
    "Zydus Cadila": "జైడస్ కాడిలా",
    "Intas Pharmaceuticals": "ఇంటాస్ ఫార్మాస్యూటికల్స్",
    "Glenmark": "గ్లెన్‌మార్క్",
    "Hetero Healthcare": "హెటెరో హెల్త్‌కేర్",
    "Johnson & Johnson": "జాన్సన్ & జాన్సన్",
    "Centaur Pharmaceuticals": "సెంటార్ ఫార్మాస్యూటికల్స్",
    "Centaur": "సెంటార్",
    "Alkem Laboratories": "అల్కెమ్ ల్యాబొరేటరీస్",
    "Alkem": "అల్కెమ్",
    "FDC Limited": "ఎఫ్‌డిసి లిమిటెడ్",
    "GSK": "జీఎస్‌కే",
    "GlaxoSmithKline": "గ్లాక్సోస్మిత్‌క్లైన్",
    "Cipla": "సిప్లా",
    "USV Private Limited": "యుఎస్‌వి ప్రైవేట్ లిమిటెడ్",
    "Reckitt Benckiser": "రెకిట్ బెంకిజర్",
    "Pfizer": "ఫైజర్",
    "Alembic": "అలెంబిక్",
    "Mankind": "మ్యాన్‌కైండ్",
  },
  ml: {
    "Micro Labs": "മൈക്രോ ലാബ്സ്",
    "Sanofi India": "സനോഫി ഇന്ത്യ",
    "Abbott": "ആബട്ട്",
    "Ipca Laboratories": "ഇപ്ക ലബോറട്ടറീസ്",
    "Blue Cross Laboratories": "ബ്ലൂ ക്രോസ് ലബോറട്ടറീസ്",
    "Wockhardt": "വോക്കാർഡ്",
    "Torrent Pharmaceuticals": "ടോറന്റ് ഫാർമസ്യൂട്ടിക്കൽസ്",
    "Zydus Cadila": "സൈഡസ് കാഡില",
    "Intas Pharmaceuticals": "ഇന്റാസ് ഫാർമസ്യൂട്ടിക്കൽസ്",
    "Glenmark": "ഗ്ലെൻമാർക്ക്",
    "Hetero Healthcare": "ഹെറ്ററോ ഹെൽത്ത്കെയർ",
    "Johnson & Johnson": "ജോൺസൺ & ജോൺസൺ",
    "Centaur Pharmaceuticals": "സെന്റോർ ഫാർമസ്യൂട്ടിക്കൽസ്",
    "Centaur": "സെന്റോർ",
    "Alkem Laboratories": "അൽകെം ലബോറട്ടറീസ്",
    "Alkem": "അൽകെം",
    "FDC Limited": "എഫ്ഡിസി ലിമിറ്റഡ്",
    "GSK": "ജിഎസ്കെ",
    "GlaxoSmithKline": "ഗ്ലാക്സോസ്മിത്ത്ക്ലൈൻ",
    "Cipla": "സിപ്ല",
    "USV Private Limited": "യുഎസ്വി പ്രൈവറ്റ് ലിമിറ്റഡ്",
    "Reckitt Benckiser": "റെക്കിറ്റ് ബെൻകിസർ",
    "Pfizer": "ഫൈസർ",
    "Alembic": "അലെംബിക്",
    "Mankind": "മാൻകൈൻഡ്",
  },
  kn: {
    "Micro Labs": "ಮೈಕ್ರೋ ಲ್ಯಾಬ್ಸ್",
    "Sanofi India": "ಸನೋಫಿ ಇಂಡಿಯಾ",
    "Abbott": "ಅಬಾಟ್",
    "Ipca Laboratories": "ಇಪ್ಕಾ ಲ್ಯಾಬೊರೇಟರೀಸ್",
    "Blue Cross Laboratories": "ಬ್ಲೂ ಕ್ರಾಸ್ ಲ್ಯಾಬೊರೇಟರೀಸ್",
    "Wockhardt": "ವೋಕಾರ್ಡ್",
    "Torrent Pharmaceuticals": "ಟೊರೆಂಟ್ ಫಾರ್ಮಾಸ್ಯೂಟಿಕಲ್ಸ್",
    "Zydus Cadila": "ಜೈಡಸ್ ಕ್ಯಾಡಿಲಾ",
    "Intas Pharmaceuticals": "ಇಂಟಾಸ್ ಫಾರ್ಮಾಸ್ಯೂಟಿಕಲ್ಸ್",
    "Glenmark": "ಗ್ಲೆನ್‌ಮಾರ್ಕ್",
    "Hetero Healthcare": "ಹೆಟೆರೋ ಹೆಲ್ತ್‌ಕೇರ್",
    "Johnson & Johnson": "ಜಾನ್ಸನ್ & ಜಾನ್ಸನ್",
    "Centaur Pharmaceuticals": "ಸೆಂಟಾರ್ ಫಾರ್ಮಾಸ್ಯೂಟಿಕಲ್ಸ್",
    "Centaur": "ಸೆಂಟಾರ್",
    "Alkem Laboratories": "ಅಲ್ಕೆಮ್ ಲ್ಯಾಬೊರೇಟರೀಸ್",
    "Alkem": "ಅಲ್ಕೆಮ್",
    "FDC Limited": "ಎಫ್‌ಡಿಸಿ ಲಿಮಿಟೆಡ್",
    "GSK": "ಜಿಎಸ್‌ಕೆ",
    "GlaxoSmithKline": "ಗ್ಲಾಕ್ಸೋಸ್ಮಿತ್‌ಕ್ಲೈನ್",
    "Cipla": "ಸಿಪ್ಲಾ",
    "USV Private Limited": "ಯುಎಸ್ವಿ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್",
    "Reckitt Benckiser": "ರೆಕಿಟ್ ಬೆಂಕಿಸರ್",
    "Pfizer": "ಫೈಜರ್",
    "Alembic": "ಅಲೆಂಬಿಕ್",
    "Mankind": "ಮ್ಯಾನ್‌ಕೈಂಡ್",
  },
};

const STRENGTH_MAPS = {
  ta: {
    "21.8g sachet": "21.8 கிராம் பாக்கெட்",
    "5g sachet": "5 கிராம் பாக்கெட்",
    "400mg": "400 மி.கி",
    "200mcg": "200 மைக்ரோகிராம்",
    "500mg": "500 மி.கி",
    "650mg": "650 மி.கி",
    "625mg": "625 மி.கி",
    "1000mg": "1000 மி.கி",
    "10mg": "10 மி.கி",
    "5mg": "5 மி.கி",
    "20mg": "20 மி.கி",
    "40mg": "40 மி.கி",
    "50g tube": "50 கிராம் டியூப்",
    "30g tube": "30 கிராம் டியூப்",
    "20g tube": "20 கிராம் டியூப்",
    "Standard": "தரநிலையானது",
    "Standard Strength": "தரமான அளவு",
    "5% w/w": "5% w/w",
    "1.16% w/w": "1.16% w/w",
    "4.8% w/v": "4.8% w/v",
  },
  hi: {
    "21.8g sachet": "21.8 ग्राम पाउच",
    "5g sachet": "5 ग्राम पाउच",
    "400mg": "400 मिग्रा",
    "200mcg": "200 एमसीजी",
    "500mg": "500 मिग्रा",
    "650mg": "650 मिग्रा",
    "625mg": "625 मिग्रा",
    "1000mg": "1000 मिग्रा",
    "10mg": "10 मिग्रा",
    "5mg": "5 मिग्रा",
    "50g tube": "50 ग्राम ट्यूब",
    "Standard": "मानक",
    "Standard Strength": "मानक शक्ति",
    "5% w/w": "5% w/w",
  },
  te: {
    "21.8g sachet": "21.8గ్రా ప్యాకెట్",
    "5g sachet": "5గ్రా ప్యాకెట్",
    "400mg": "400మి.గ్రా",
    "200mcg": "200మైక్రోగ్రామ్",
    "500mg": "500మి.గ్రా",
    "650mg": "650మి.గ్రా",
    "625mg": "625మి.గ్రా",
    "1000mg": "1000మి.గ్రా",
    "50g tube": "50గ్రా ట్యూబ్",
    "Standard": "ప్రామాణికం",
    "Standard Strength": "ప్రామాణిక బలం",
    "5% w/w": "5% w/w",
  },
  ml: {
    "21.8g sachet": "21.8 ഗ്രാം പാക്കറ്റ്",
    "5g sachet": "5 ഗ്രാം പാക്കറ്റ്",
    "400mg": "400 മി.ഗ്രാം",
    "200mcg": "200 മൈക്രോ ഗ്രാം",
    "500mg": "500 മി.ഗ്രാം",
    "650mg": "650 മി.ഗ്രാം",
    "625mg": "625 മി.ഗ്രാം",
    "1000mg": "1000 മി.ഗ്രാം",
    "50g tube": "50 ഗ്രാം ട്യൂബ്",
    "Standard": "സ്റ്റാൻഡേർഡ്",
    "Standard Strength": "സ്റ്റാൻഡേർഡ് അളവ്",
    "5% w/w": "5% w/w",
  },
  kn: {
    "21.8g sachet": "21.8 ಗ್ರಾಂ ಸ್ಯಾಚೆಟ್",
    "5g sachet": "5 ಗ್ರಾಂ ಸ್ಯಾಚೆಟ್",
    "400mg": "400 ಮಿ.ಗ್ರಾಂ",
    "200mcg": "200 ಮೈಕ್ರೋಗ್ರಾಂ",
    "500mg": "500 ಮಿ.ಗ್ರಾಂ",
    "650mg": "650 ಮಿ.ಗ್ರಾಂ",
    "625mg": "625 ಮಿ.ಗ್ರಾಂ",
    "1000mg": "1000 ಮಿ.ಗ್ರಾಂ",
    "50g tube": "50 ಗ್ರಾಂ ಟ್ಯೂಬ್",
    "Standard": "ಸ್ಟ್ಯಾಂಡರ್ಡ್",
    "Standard Strength": "ಸ್ಟ್ಯಾಂಡರ್ಡ್ ಶಕ್ತಿ",
    "5% w/w": "5% w/w",
  },
};

const PACK_SIZE_MAPS = {
  ta: {
    "Strip of 10 tablets": "10 மாத்திரைகள் கொண்ட அட்டை",
    "Strip of 15 tablets": "15 மாத்திரைகள் கொண்ட அட்டை",
    "Strip of 20 tablets": "20 மாத்திரைகள் கொண்ட அட்டை",
    "Strip of 14 tablets": "14 மாத்திரைகள் கொண்ட அட்டை",
    "Strip of 10 capsules": "10 கேப்சூல்கள் கொண்ட அட்டை",
    "Strip of 15 capsules": "15 கேப்சூல்கள் கொண்ட அட்டை",
    "Strip of 20 capsules": "20 கேப்சூல்கள் கொண்ட அட்டை",
    "Strip of 8 capsules": "8 கேப்சூல்கள் கொண்ட அட்டை",
    "Bottle of 100ml": "100மி.லி பாட்டில்",
    "Bottle of 60ml": "60மி.லி பாட்டில்",
    "Bottle of 15ml": "15மி.லி பாட்டில்",
    "Bottle of 30ml": "30மி.லி பாட்டில்",
    "Bottle of 150ml": "150மி.லி பாட்டில்",
    "Bottle of 200ml": "200மி.லி பாட்டில்",
    "Bottle of 225ml": "225மி.லி பாட்டில்",
    "Box of 10 sachets": "10 பாக்கெட்டுகள் கொண்ட பெட்டி",
    "Box of 30 sachets": "30 பாக்கெட்டுகள் கொண்ட பெட்டி",
    "Pack of 5 sachets": "5 பாக்கெட்டுகள் கொண்ட பேக்",
    "20g tube": "20 கிராம் டியூப்",
    "30g tube": "30 கிராம் டியூப்",
    "50g tube": "50 கிராம் டியூப்",
    "Tube of 30g": "30 கிராம் டியூப்",
    "Can of 55g": "55 கிராம் கேன்",
    "Can of 50g": "50 கிராம் கேன்",
    "Jar of 50g": "50 கிராம் ஜார்",
    "Jar of 25ml": "25மி.லி ஜார்",
    "Jar of 21ml": "21மி.லி ஜார்",
    "Pack of 100g": "100 கிராம் பேக்",
    "Pack of 200ml": "200மி.லி பேக்",
    "Ampoule of 1ml": "1மி.லி ஆம்ப்யூல்",
    "Ampoule of 2ml": "2மி.லி ஆம்ப்யூல்",
  },
  hi: {
    "Strip of 10 tablets": "10 गोलियों की स्ट्रिप",
    "Strip of 15 tablets": "15 गोलियों की स्ट्रिप",
    "Strip of 20 tablets": "20 गोलियों की स्ट्रिप",
    "Strip of 14 tablets": "14 गोलियों की स्ट्रिप",
    "Strip of 10 capsules": "10 कैप्सूल की स्ट्रिप",
    "Strip of 15 capsules": "15 कैप्सूल की स्ट्रिप",
    "Strip of 20 capsules": "20 कैप्सूल की स्ट्रिप",
    "Strip of 8 capsules": "8 कैप्सूल की स्ट्रिप",
    "Bottle of 100ml": "100 मि.ली. की बोतल",
    "Bottle of 60ml": "60 मि.ली. की बोतल",
    "Bottle of 15ml": "15 मि.ली. की बोतल",
    "Bottle of 30ml": "30 मि.ली. की बोतल",
    "Bottle of 150ml": "150 मि.ली. की बोतल",
    "Bottle of 200ml": "200 मि.ली. की बोतल",
    "Bottle of 225ml": "225 मि.ली. की बोतल",
    "Box of 10 sachets": "10 पाउच का बॉक्स",
    "Box of 30 sachets": "30 पाउच का बॉक्स",
    "Pack of 5 sachets": "5 पाउच का पैक",
  },
  te: {
    "Strip of 10 tablets": "10 మాత్రల స్ట్రిప్",
    "Strip of 15 tablets": "15 మాత్రల స్ట్రిప్",
    "Strip of 20 tablets": "20 మాత్రల స్ట్రిప్",
    "Strip of 10 capsules": "10 క్యాప్సూల్స్ స్ట్రిప్",
    "Bottle of 100ml": "100మి.లీ సీసా",
    "Bottle of 60ml": "60మి.లీ సీసా",
  },
  ml: {
    "Strip of 10 tablets": "10 ഗുളികകളുടെ സ്ട്രിപ്പ്",
    "Strip of 15 tablets": "15 ഗുളികകളുടെ സ്ട്രിപ്പ്",
    "Strip of 10 capsules": "10 ക്യാപ്സൂളുകളുടെ സ്ട്രിപ്പ്",
    "Bottle of 100ml": "100 മില്ലി കുപ്പി",
    "Bottle of 60ml": "60 മില്ലി കുപ്പി",
  },
  kn: {
    "Strip of 10 tablets": "10 ಮಾತ್ರೆಗಳ ಸ್ಟ್ರಿಪ್",
    "Strip of 15 tablets": "15 ಮಾತ್ರೆಗಳ ಸ್ಟ್ರಿಪ್",
    "Strip of 10 capsules": "10 ಕ್ಯಾಪ್ಸೂಲ್ಗಳ ಸ್ಟ್ರಿಪ್",
    "Bottle of 100ml": "100ಮಿ.ಲೀ ಬಾಟಲ್",
    "Bottle of 60ml": "60ಮಿ.ಲೀ ಬಾಟಲ್",
  },
};

const DOSAGE_FORM_MAPS = {
  ta: {
    Powder: "பவுடர்",
    Capsule: "கேப்சூல்",
    Capsules: "கேப்சூல்கள்",
    Tablet: "மாத்திரை",
    Tablets: "மாத்திரைகள்",
    Inhaler: "இன்ஹேலர்",
    Cream: "கிரீம்",
    Ointment: "ஒயின்ட்மென்ட்",
    Syrup: "சிரப்",
    Suspension: "சஸ்பென்ஷன்",
    "Dry Syrup": "உலர் சிரப்",
    "Oral Drops": "சொட்டு மருந்து",
    Drops: "சொட்டு மருந்து",
    Gel: "ஜெல்",
    Injection: "ஊசி",
    Spray: "ஸ்ப்ரே",
    Balm: "பாம்",
    Liquid: "திரவம்",
    "Nasal Drops": "நாசி சொட்டு மருந்து",
    "Nasal Spray": "நாசி ஸ்ப்ரே",
    "Dispersible Tablet": "கரைக்கக்கூடிய மாத்திரை",
    "Mouth Dissolving Tablet": "வாயில் கரையும் மாத்திரை",
    "Chewable Tablet": "மெல்லும் மாத்திரை",
  },
  hi: {
    Powder: "पाउडर",
    Capsule: "कैप्सूल",
    Capsules: "कैप्सूल",
    Tablet: "टैबलेट",
    Tablets: "टैबलेट्स",
    Inhaler: "इनहेलर",
    Cream: "क्रीम",
    Ointment: "ऑइंटमेंट",
    Syrup: "सिरप",
    Suspension: "सस्पेंशन",
    "Dry Syrup": "ड्राई सिरप",
    "Oral Drops": "ओरल ड्रॉप्स",
    Drops: "ड्रॉप्स",
    Gel: "जेल",
    Injection: "इंजेक्शन",
    Spray: "स्प्रे",
    Balm: "बाम",
    Liquid: "लिक्विड",
  },
  te: {
    Powder: "పౌడర్",
    Capsule: "క్యాప్సూల్",
    Tablet: "మాత్ర",
    Inhaler: "ఇన్హేలర్",
    Cream: "క్రీమ్",
    Ointment: "ఆయింట్మెంట్",
    Syrup: "సిరప్",
    Suspension: "సస్పెన్షన్",
    "Dry Syrup": "డ్రై సిరప్",
    Drops: "డ్రాప్స్",
    Gel: "జెల్",
    Injection: "ఇంజెక్షన్",
  },
  ml: {
    Powder: "പൗഡർ",
    Capsule: "ക്യാപ്സൂൾ",
    Tablet: "ഗുളിക",
    Inhaler: "ഇൻഹേലർ",
    Cream: "ക്രീം",
    Ointment: "ഒയിന്റ്മെന്റ്",
    Syrup: "സിറപ്പ്",
    Suspension: "സസ്പെൻഷൻ",
    "Dry Syrup": "ഡ്രൈ സിറപ്പ്",
    Drops: "ഡ്രോപ്സ്",
    Gel: "ജെൽ",
    Injection: "ഇഞ്ചക്ഷൻ",
  },
  kn: {
    Powder: "ಪೌಡರ್",
    Capsule: "ಕ್ಯಾಪ್ಸೂಲ್",
    Tablet: "ಮಾತ್ರೆ",
    Inhaler: "ಇನ್ಹೇಲರ್",
    Cream: "ಕ್ರೀಮ್",
    Ointment: "ಆಯಿಂಟ್‌ಮೆಂಟ್",
    Syrup: "ಸಿರಪ್",
    Suspension: "ಸಸ್ಪೆನ್ಷನ್",
    "Dry Syrup": "ಡ್ರೈ ಸಿರಪ್",
    Drops: "ಡ್ರಾಪ್ಸ್",
    Gel: "ಜೆಲ್",
    Injection: "ಇಂಜೆಕ್ಷನ್",
  },
};

const COMPOSITION_TERM_MAPS = {
  ta: {
    Amoxicillin: "அமோக்சிசிலின்",
    "Clavulanic Acid": "க்ளவுலானிக் அமிலம்",
    "Potassium Clavulanate": "பொட்டாசியம் க்ளவுலானேட்",
    Paracetamol: "பாரசிட்டமால்",
    Azithromycin: "அசித்ரோமைசின்",
    Metformin: "மெட்ஃபோர்மின்",
    Hydrochloride: "ஹைட்ரோகுளோரைடு",
    Tablets: "மாத்திரைகள்",
    Tablet: "மாத்திரை",
    Capsules: "கேப்சூல்கள்",
    Capsule: "கேப்சூல்",
    Syrup: "சிரப்",
    Suspension: "சஸ்பென்ஷன்",
    Powder: "பவுடர்",
    Cream: "கிரீம்",
    Ointment: "ஒயின்ட்மென்ட்",
    Inhaler: "இன்ஹேலர்",
    Aceclofenac: "அசெக்லோஃபெனாக்",
    Serratiopeptidase: "செரேஷியோபெப்டிடேஸ்",
    "Mefenamic Acid": "மெஃபெனமிக் அமிலம்",
    Dicyclomine: "டைசைக்ளோமைன்",
    Diclofenac: "டைக்ளோஃபெனாக்",
    Sodium: "சோடியம்",
    Potassium: "பொட்டாசியம்",
    Etoricoxib: "எடோரிகாக்சிப்",
    Thiocolchicoside: "தியோகால்சிகோசைடு",
    Trypsin: "டிரிப்சின்",
    Chymotrypsin: "கைமோடிரிப்சின்",
    Cetirizine: "செட்ரிசின்",
    Levocetirizine: "லெவோசெட்ரிசின்",
    Montelukast: "மாண்டெலூகாஸ்ட்",
    Fexofenadine: "ஃபெக்சோஃபெனடைன்",
    Dextromethorphan: "டெக்ஸ்ட்ரோமெதோர்பான்",
    Chlorpheniramine: "குளோர்பெனிரமைன்",
    Phenylephrine: "ஃபெனிலெஃப்ரின்",
    Ambroxol: "அம்ப்ராக்சால்",
    Levosalbutamol: "லெவோசல்பியூடமால்",
    Guaifenesin: "குவைஃபெனசின்",
    Xylometazoline: "சைலோமெடசோலின்",
    Omeprazole: "ஓமிபிரசோல்",
    Esomeprazole: "எஸோமிபிரசோல்",
    Pantoprazole: "பேன்டோபிரசோல்",
    Domperidone: "டாம்பரிடோன்",
    Rabeprazole: "ராபிபிரசோல்",
    Magaldrate: "மகால்ட்ரேட்",
    Simethicone: "சிமெதிகோன்",
    "Aluminium Hydroxide": "அலுமினியம் ஹைட்ராக்சைடு",
    "Magnesium Hydroxide": "மெக்னீசியம் ஹைட்ராக்சைடு",
    "Oral Rehydration Salts": "வாய்வழி நீர்சத்து உப்புகள்",
    ORS: "ஓஆர்எஸ்",
    Lactulose: "லாக்டுலோஸ்",
    "Liquid Paraffin": "திரவ பேராஃபின்",
    "Milk of Magnesia": "மில்க் ஆஃப் மெக்னீசியா",
    Bisacodyl: "பிஸாகோடில்",
    Ondansetron: "ஆன்டன்செட்ரான்",
    Povidone: "போவிடோன்",
    Iodine: "போவிடோன் அயோடின்",
    Chloroxylenol: "குளோராக்சிலீனால்",
    Aspirin: "ஆஸ்பிரின்",
    Ascorbic: "அஸ்கார்பிக்",
    Acid: "அமிலம்",
    Ibuprofen: "ஐபூபுரோஃபென்",
    Caffeine: "கேஃபின்",
    Zinc: "துத்தநாகம்",
    Vitamin: "வைட்டமின்",
    Complex: "காம்பளக்ஸ்",
    "Linseed Oil": "ஆளி விதை எண்ணெய்",
    "Wintergreen Oil": "வின்டர்கிரீன் எண்ணெய்",
    "Nilgiri Oil": "நீலகிரி எண்ணெய்",
    "Turpentine Oil": "டர்பன்டைன் எண்ணெய்",
    Menthol: "மெந்தால்",
    Adult: "அடல்ட்",
    Nasal: "நாசி",
    Spray: "ஸ்ப்ரே",
    "Fast Action": "வேகமான செயல்பாடு",
    "Plus": "பிளஸ்",
    "Advance": "அட்வான்ஸ்",
    "Junior": "ஜூனியர்",
    "Pead": "பீட்",
    "Drops": "சொட்டு மருந்து",
    "Oral": "வாய்வழி",
    "Dry": "உலர்",
    "Total": "டோட்டல்",
    "Formula": "ஃபார்முலா",
    "Regular": "ரெகுலர்",
    "Lemon": "லெமன்",
    "Orange": "ஆரஞ்சு",
    "Apple": "ஆப்பிள்",
    "Mint": "மின்ட்",
    "Fruit": "ஃப்ரூட்",
    "Salt": "சால்ட்",
    "Liquid": "திரவம்",
    "Gel": "ஜெல்",
    "Balm": "பாம்",
    "Strip": "அட்டை",
    "Bottle": "பாட்டில்",
    "Box": "பெட்டி",
    "Pack": "பேக்",
    "Can": "கேன்",
    "Jar": "ஜார்",
    "Tube": "டியூப்",
    "sachet": "பாக்கெட்",
    "sachets": "பாக்கெட்டுகள்",
    "tablets": "மாத்திரைகள்",
    "capsules": "கேப்சூல்கள்",
    "and": "மற்றும்",
    IP: "IP",
    BP: "BP",
    USP: "USP",
  },
  hi: {
    Amoxicillin: "अमोक्सीसिलिन",
    "Clavulanic Acid": "क्लैवुलेनिक एसिड",
    "Potassium Clavulanate": "पोटेशियम क्लावुलानेट",
    Paracetamol: "पैरासिटामोल",
    Azithromycin: "अजिथ्रोमाइसिन",
    Metformin: "मेटफॉर्मिन",
    Hydrochloride: "हाइड्रोक्लोराइड",
    Tablets: "टैबलेट्स",
    Tablet: "टैबलेट",
    Capsules: "कैप्सूल",
    Capsule: "कैप्सूल",
    Syrup: "सिरप",
    Suspension: "सस्पेंशन",
    Powder: "पाउडर",
    Cream: "क्रीम",
    Ointment: "ऑइंटमेंट",
    Inhaler: "इनहेलर",
    Aceclofenac: "एक्लोफेनाक",
    Serratiopeptidase: "सेराटियोपेप्टिडेज",
    "Mefenamic Acid": "मेफेनामिक एसिड",
    Dicyclomine: "डाइसाइक्लोमाइन",
    Diclofenac: "डिक्लोफेनाक",
    Etoricoxib: "इटोरिकोक्सिब",
    Thiocolchicoside: "थियोकोल्चिकोसाइड",
    Trypsin: "ट्रिप्सिन",
    Chymotrypsin: "काइमोट्रिप्सिन",
    Cetirizine: "सेटिरिजिन",
    Levocetirizine: "लेवोसेटिरिजिन",
    Montelukast: "मोंटेलुकास्ट",
    Fexofenadine: "फेक्सोफेनाडाइन",
    Dextromethorphan: "डेक्सट्रोमेथॉर्फन",
    Chlorpheniramine: "क्लोरफेनिरामाइन",
    Phenylephrine: "फेनिलफ्रीन",
    Ambroxol: "एम्ब्रॉक्सोल",
    Levosalbutamol: "लेवोसालबुटामोल",
    Guaifenesin: "गुआइफेनेसिन",
    Xylometazoline: "जाइलोमेटाजोलिन",
    Omeprazole: "ओमेप्राजोल",
    Esomeprazole: "इसोमेप्राजोल",
    Pantoprazole: "पेंटोप्राजोल",
    Domperidone: "डोमपेरिडोन",
    Rabeprazole: "रेबेप्राजोल",
    Magaldrate: "मगालड्रेट",
    Simethicone: "सिमेथिकोन",
    "Oral Rehydration Salts": "ओरल रीहाइड्रेशन साल्ट्स",
    Lactulose: "लक्टुलोज",
    Ondansetron: "ओंडांसेट्रॉन",
    Ibuprofen: "इबूप्रोफेन",
    Caffeine: "कैफीन",
    Adult: "एडल्ट",
    Nasal: "नेजल",
    Spray: "स्प्रे",
    and: "और",
    IP: "IP",
    BP: "BP",
    USP: "USP",
  },
  te: {
    Amoxicillin: "అమోక్సిసిలిన్",
    "Clavulanic Acid": "క్లావులనిక్ యాసిడ్",
    "Potassium Clavulanate": "పొటాషియం క్లావులనేట్",
    Paracetamol: "పారాసిటమాల్",
    Azithromycin: "అజిత్రోమైసిన్",
    Metformin: "మెట్‌ఫార్మిన్",
    Hydrochloride: "హైడ్రోక్లోరైడ్",
    Tablets: "మాత్రలు",
    Tablet: "మాత్ర",
    Capsules: "క్యాప్సూల్స్",
    Capsule: "క్యాప్సూల్",
    Syrup: "సిరప్",
    Suspension: "సస్పెన్షన్",
    Powder: "పౌడర్",
    Cream: "క్రీమ్",
    Ointment: "ఆయింట్మెంట్",
    Inhaler: "ఇన్హేలర్",
    Aceclofenac: "ఎస్‌క్లోఫెనాక్",
    Serratiopeptidase: "సెరాటియోపెప్టిడేస్",
    Mefenamic: "మెఫెనామిక్",
    Dicyclomine: "డైసైక్లోమైన్",
    Diclofenac: "డిక్లోఫెనాక్",
    Cetirizine: "సెటిరిజైన్",
    Levocetirizine: "లెవోసెటిരിజైన్",
    Montelukast: "మోంటెల్యూకాస్ట్",
    Phenylephrine: "ఫెనిలెఫ్రిన్",
    Chlorpheniramine: "క్లోర్‌ఫెనిరమైన్",
    Xylometazoline: "జైలోమెటాజోలిన్",
    Adult: "అడల్ట్",
    Nasal: "నాసికా",
    Spray: "స్ప్రే",
    Omeprazole: "ఒమెప్రాజోల్",
    Pantoprazole: "పాంటోప్రాజోల్",
    Domperidone: "డోమ్‌పెరిడోన్",
    Ondansetron: "ఒండన్‌సెట్రాన్",
    and: "మరియు",
    IP: "IP",
    BP: "BP",
    USP: "USP",
  },
  ml: {
    Amoxicillin: "അമോക്സിസിലിൻ",
    "Clavulanic Acid": "ക്ലാവുലനിക് ആസിഡ്",
    "Potassium Clavulanate": "പൊട്ടാസ്യം ക്ലാവുലനേറ്റ്",
    Paracetamol: "പാരസിറ്റമോൾ",
    Azithromycin: "അസിത്രോമൈസിൻ",
    Metformin: "മെറ്റ്ഫോർമിൻ",
    Hydrochloride: "ഹൈഡ്രോക്ലോറൈഡ്",
    Tablets: "ഗുളികകൾ",
    Tablet: "ഗുളിക",
    Capsules: "ക്യാപ്സൂളുകൾ",
    Capsule: "ക്യാപ്സൂൾ",
    Syrup: "സിറപ്പ്",
    Suspension: "സസ്പെൻഷൻ",
    Powder: "പൗഡർ",
    Cream: "ക്രീം",
    Ointment: "ഒയിന്റ്മെന്റ്",
    Inhaler: "ഇൻഹേലർ",
    Aceclofenac: "അസെക്ലോഫെനാക്",
    Serratiopeptidase: "സെറേഷ്യോപെപ്റ്റിഡേസ്",
    Mefenamic: "മെഫെനാമിക്",
    Dicyclomine: "ഡൈസൈക്ലോമൈൻ",
    Diclofenac: "ഡിക്ലോഫെനാക്",
    Cetirizine: "സെറ്റിരിസിൻ",
    Levocetirizine: "ലെവോസെറ്റിരിസിൻ",
    Montelukast: "മോണ്ടെലൂക്കാസ്റ്റ്",
    Phenylephrine: "ഫെനിലൈഫ്രിൻ",
    Chlorpheniramine: "ക്ലോർഫെനിരാമൈൻ",
    Xylometazoline: "സൈലോമെറ്റാസോളിൻ",
    Adult: "അഡൽറ്റ്",
    Nasal: "നാസൽ",
    Spray: "സ്പ്രേ",
    Omeprazole: "ഒമേപ്രാസോൾ",
    Pantoprazole: "പന്റോപ്രാസോൾ",
    Domperidone: "ഡോംപെരിഡോൺ",
    Ondansetron: "ഒൻഡാൻസെട്രോൺ",
    and: "ഒപ്പം",
    IP: "IP",
    BP: "BP",
    USP: "USP",
  },
  kn: {
    Amoxicillin: "ಅಮೊಕ್ಸಿಸಿಲಿನ್",
    "Clavulanic Acid": "ಕ್ಲಾವ್ಯುಲನಿಕ್ ಆಸಿಡ್",
    "Potassium Clavulanate": "ಪೊಟ್ಯಾಸಿಯಮ್ ಕ್ಲಾವ್ಯುಲನೇಟ್",
    Paracetamol: "ಪ್ಯಾರಾಸಿಟಮಾಲ್",
    Azithromycin: "ಅಜಿತ್ರೋಮೈಸಿನ್",
    Metformin: "ಮೆಟ್‌ಫಾರ್ಮಿನ್",
    Hydrochloride: "ಹೈಡ್ರೋಕ್ಲೋರೈಡ್",
    Tablets: "ಮಾತ್ರೆಗಳು",
    Tablet: "ಮಾತ್ರೆ",
    Capsules: "ಕ್ಯಾಪ್ಸೂಲ್ಗಳು",
    Capsule: "ಕ್ಯಾಪ್ಸೂಲ್",
    Syrup: "ಸಿರಪ್",
    Suspension: "ಸಸ್ಪೆನ್ಷನ್",
    Powder: "ಪೌಡರ್",
    Cream: "ಕ್ರೀಮ್",
    Ointment: "ಆಯಿಂಟ್‌ಮೆಂಟ್",
    Inhaler: "ಇನ್ಹೇಲರ್",
    Aceclofenac: "ಅಸೆಕ್ಲೋಫೆನಾಕ್",
    Serratiopeptidase: "ಸೆರಾಟಿಯೋಪೆಪ್ಟಿಡೇಸ್",
    Mefenamic: "ಮೆಫೆನಾಮಿಕ್",
    Dicyclomine: "ಡೈಸೈಕ್ಲೋಮೈನ್",
    Diclofenac: "ಡಿಕ್ಲೋಫೆನಾಕ್",
    Cetirizine: "ಸೆಟಿರಿಜಿನ್",
    Levocetirizine: "ಲೆವೋಸೆಟಿರಿಜಿನ್",
    Montelukast: "ಮಾಂಟೆಲುಕಾಸ್ಟ್",
    Phenylephrine: "ಫೆನಿಲೆಫ್ರಿನ್",
    Chlorpheniramine: "ಕ್ಲೋರ್‌ಫೆನಿರಾಮೈನ್",
    Xylometazoline: "ಝೈಲೋಮೆಟಾಜೋಲಿನ್",
    Adult: "ಅಡಲ್ಟ್",
    Nasal: "ನಾಸಲ್",
    Spray: "ಸ್ಪ್ರೇ",
    Omeprazole: "ಒಮೆಪ್ರಾಜೋಲ್",
    Pantoprazole: "ಪ್ಯಾಂಟೋಪ್ರಾಜೋಲ್",
    Domperidone: "ಡೋಮ್ಪೆರಿಡೋನ್",
    Ondansetron: "ಒಂಡಾನ್ಸೆಟ್ರಾನ್",
    and: "ಮತ್ತು",
    IP: "IP",
    BP: "BP",
    USP: "USP",
  },
};

const SENTENCE_MAPS = {};

export function formatCompositionPhrase(phrase, langCode = "en") {
  if (!phrase || langCode === "en") return phrase || "";
  const map = COMPOSITION_TERM_MAPS[langCode];
  if (!map) return phrase;

  if (map[phrase]) return map[phrase];

  let result = String(phrase);

  // Split composite delimiters
  if (result.includes("+")) {
    return result.split("+").map((p) => formatCompositionPhrase(p.trim(), langCode)).join(" + ");
  }
  if (result.includes("/")) {
    return result.split("/").map((p) => formatCompositionPhrase(p.trim(), langCode)).join(" / ");
  }
  if (result.includes(" and ")) {
    const andTrans = map["and"] || "மற்றும்";
    return result.split(" and ").map((p) => formatCompositionPhrase(p.trim(), langCode)).join(` ${andTrans} `);
  }
  if (result.includes(" & ")) {
    return result.split(" & ").map((p) => formatCompositionPhrase(p.trim(), langCode)).join(" & ");
  }

  const sortedKeys = Object.keys(map).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    if (result.includes(key)) {
      const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`\\b${escapedKey}\\b`, "gi");
      result = result.replace(regex, map[key]);
    }
  }

  return result;
}

export function formatDate(dateVal, languageCode = "en") {
  if (!dateVal) return "";
  try {
    const date = new Date(dateVal);
    if (isNaN(date.getTime())) return String(dateVal);
    const locale = LOCALE_MAP[languageCode] || "en-IN";
    return new Intl.DateTimeFormat(locale, {
      day: "numeric",
      month: "short",
      year: "numeric",
    }).format(date);
  } catch (e) {
    return String(dateVal);
  }
}

export function formatDateTime(dateVal, languageCode = "en") {
  if (!dateVal) return "";
  try {
    const date = new Date(dateVal);
    if (isNaN(date.getTime())) return String(dateVal);
    const locale = LOCALE_MAP[languageCode] || "en-IN";
    return new Intl.DateTimeFormat(locale, {
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    }).format(date);
  } catch (e) {
    return String(dateVal);
  }
}

export function formatTravelTime(travelTime, t) {
  if (!travelTime) return "";
  if (typeof travelTime === "object") {
    const drive = travelTime.drive ? formatTravelTime(travelTime.drive, t) : "";
    const walk = travelTime.walk ? formatTravelTime(travelTime.walk, t) : "";
    return { drive, walk };
  }

  const str = String(travelTime);
  const match = str.match(/(\d+)\s*min\s*(drive|walk)/i);
  if (match) {
    const count = match[1];
    const mode = match[2].toLowerCase();
    if (mode === "drive") {
      return t("pharmacy.driveTime", { count });
    }
    if (mode === "walk") {
      return t("pharmacy.walkTime", { count });
    }
  }
  return str;
}

export function formatAddress(addressText, tOrLang, t) {
  if (!addressText) return "";
  let lang = typeof tOrLang === "string" ? tOrLang : "en";
  if (typeof tOrLang === "function" && !t) {
    t = tOrLang;
  }

  let result = String(addressText);

  if (t && typeof t === "function") {
    const key = `address.${result}`;
    const translated = t(key);
    if (translated && translated !== key) {
      return translated;
    }
  }

  const map = LOCATION_MAPS[lang];
  if (map) {
    Object.keys(map).forEach((term) => {
      const regex = new RegExp(`\\b${term}\\b`, "gi");
      result = result.replace(regex, map[term]);
    });
  }

  return result;
}

export function formatCityName(city, languageCode = "en") {
  if (!city) return "";
  const map = LOCATION_MAPS[languageCode];
  return map?.[city] || city;
}

export function formatStateName(state, languageCode = "en") {
  if (!state) return "";
  const map = LOCATION_MAPS[languageCode];
  return map?.[state] || state;
}

export function formatLocationName(name, languageCode = "en") {
  if (!name) return "";
  const map = LOCATION_MAPS[languageCode];
  return map?.[name] || name;
}

export function formatInstitutionName(name, t) {
  if (!name) return "";
  if (t && typeof t === "function") {
    const key = `hospital.name.${name}`;
    const translated = t(key);
    if (translated && translated !== key) return translated;
  }
  return name;
}

export function formatPharmacyName(name, t) {
  if (!name) return "";
  if (t && typeof t === "function") {
    const key = `pharmacy.name.${name}`;
    const translated = t(key);
    if (translated && translated !== key) return translated;
  }
  return name;
}

export function formatHospitalName(name, t) {
  return formatInstitutionName(name, t);
}

export function formatBrandName(brandName, langCode = "en") {
  if (!brandName || langCode === "en") return brandName || "";
  const map = MEDICINE_BRAND_MAPS[langCode];
  if (!map) return brandName;
  if (map[brandName]) return map[brandName];

  const lowerBrand = String(brandName).toLowerCase();
  const exactKey = Object.keys(map).find((k) => k.toLowerCase() === lowerBrand);
  if (exactKey) return map[exactKey];

  let result = String(brandName);
  const sortedKeys = Object.keys(map).sort((a, b) => b.length - a.length);
  let matched = false;
  for (const key of sortedKeys) {
    if (result.toLowerCase().includes(key.toLowerCase())) {
      const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`\\b${escapedKey}\\b`, "gi");
      result = result.replace(regex, map[key]);
      matched = true;
    }
  }

  if (matched) {
    return formatCompositionPhrase(result, langCode);
  }

  return formatCompositionPhrase(brandName, langCode);
}

export function formatGenericName(genericName, langCode = "en") {
  if (!genericName || langCode === "en") return genericName || "";
  const map = GENERIC_NAME_MAPS[langCode];
  if (map && map[genericName]) return map[genericName];

  const lowerGen = String(genericName).toLowerCase();
  const exactKey = map ? Object.keys(map).find((k) => k.toLowerCase() === lowerGen) : null;
  if (exactKey) return map[exactKey];

  return formatCompositionPhrase(genericName, langCode);
}

export function formatManufacturer(mfg, langCode = "en") {
  if (!mfg || langCode === "en") return mfg || "";
  const map = MANUFACTURER_MAPS[langCode];
  if (!map) return mfg;
  if (map[mfg]) return map[mfg];

  const lowerMfg = String(mfg).toLowerCase();
  const exactKey = Object.keys(map).find((k) => k.toLowerCase() === lowerMfg);
  if (exactKey) return map[exactKey];

  let result = String(mfg);
  const sortedKeys = Object.keys(map).sort((a, b) => b.length - a.length);
  let matched = false;
  for (const key of sortedKeys) {
    if (result.toLowerCase().includes(key.toLowerCase())) {
      const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const regex = new RegExp(`\\b${escapedKey}\\b`, "gi");
      result = result.replace(regex, map[key]);
      matched = true;
    }
  }

  return formatCompositionPhrase(result, langCode);
}

export function formatStrength(strength, langCode = "en") {
  if (!strength || langCode === "en") return strength || "";
  const map = STRENGTH_MAPS[langCode];
  if (map && map[strength]) return map[strength];
  return formatCompositionPhrase(strength, langCode);
}

export function formatPackSize(packSize, langCode = "en") {
  if (!packSize || langCode === "en") return packSize || "";
  const map = PACK_SIZE_MAPS[langCode];
  if (map && map[packSize]) return map[packSize];
  return formatCompositionPhrase(packSize, langCode);
}

export function formatDosageForm(form, langCode = "en") {
  if (!form || langCode === "en") return form || "";
  const map = DOSAGE_FORM_MAPS[langCode];
  if (map && map[form]) return map[form];
  if (map) {
    const key = Object.keys(map).find(
      (k) => k.toLowerCase() === String(form).trim().toLowerCase()
    );
    if (key) return map[key];
  }
  return formatCompositionPhrase(form, langCode);
}

export function formatMedicineText(text, langCode = "en") {
  if (!text) return "";
  if (Array.isArray(text)) {
    return text.map((item) => formatMedicineText(item, langCode));
  }
  if (langCode === "en") return text;
  const map = SENTENCE_MAPS[langCode];
  if (map && map[text]) return map[text];
  return text;
}
