// Central medicine dataset + helper functions.
// Swap getAllMedicines() for a real API call once your backend exposes one.

export const CATEGORIES = [
  "Pain Relief",
  "Fever",
  "Antibiotics",
  "Diabetes",
  "Vitamins",
  "Cold & Cough",
  "Digestive Care",
  "Skin Care",
];

export const MEDICINES = [
  {
    id: "crocin-500",
    brand: "Crocin",
    genericName: "Paracetamol",
    strength: "500mg",
    manufacturer: "GSK",
    price: 18,
    packSize: "Strip of 15 tablets",
    otc: true,
    category: "Pain Relief",
    rating: 4.5,
    popularity: 95,
    description:
      "Paracetamol is a widely used pain reliever and fever reducer, suitable for mild to moderate pain and fever in adults and children.",
    uses: ["Fever", "Headache", "Body ache", "Toothache", "Cold-related pain"],
    dosage: {
      adults: "1–2 tablets (500–1000mg) every 4–6 hours. Do not exceed 4g/day.",
      children: "As advised by a pediatrician based on body weight.",
      missedDose: "Take as soon as you remember. Skip if it's almost time for the next dose.",
      overdose: "Seek emergency medical attention immediately — overdose can cause liver damage.",
    },
    sideEffects: {
      common: ["Nausea", "Stomach upset"],
      rare: ["Skin rash", "Allergic reaction", "Liver damage (with overdose)"],
    },
    warnings: {
      pregnancy: "Considered safe at recommended doses — consult your doctor.",
      breastfeeding: "Generally considered safe.",
      kidneyDisease: "Use with caution; consult your doctor.",
      liverDisease: "Avoid or use only under medical supervision.",
      alcohol: "Avoid regular alcohol use — increases liver damage risk.",
      driving: "Does not typically impair driving ability.",
    },
    interactions: ["Warfarin", "Alcohol", "Other paracetamol-containing products"],
    foodInteractions: {
      beforeFood: "Can be taken before or after food.",
      afterFood: "Preferred if you have a sensitive stomach.",
      avoid: ["Alcohol"],
    },
    storage: "Store below 30°C in a dry place, away from direct sunlight.",
    alternatives: ["dolo-650", "calpol-500"],
    badges: { bestSeller: true, topRated: true, lowestPrice: true },
  },
  {
    id: "dolo-650",
    brand: "Dolo",
    genericName: "Paracetamol",
    strength: "650mg",
    manufacturer: "Micro Labs",
    price: 35,
    packSize: "Strip of 15 tablets",
    otc: true,
    category: "Fever",
    rating: 4.3,
    popularity: 90,
    description: "A higher-strength paracetamol formulation commonly used for fever and moderate pain relief.",
    uses: ["Fever", "Body ache", "Headache"],
    dosage: {
      adults: "1 tablet (650mg) every 6–8 hours. Do not exceed 3 tablets/day.",
      children: "Not recommended below 12 years without medical advice.",
      missedDose: "Take as soon as you remember; skip if close to the next dose.",
      overdose: "Seek emergency medical attention immediately.",
    },
    sideEffects: {
      common: ["Nausea"],
      rare: ["Skin rash", "Liver damage (with overdose)"],
    },
    warnings: {
      pregnancy: "Consult your doctor before use.",
      breastfeeding: "Generally considered safe.",
      kidneyDisease: "Use with caution.",
      liverDisease: "Avoid or use only under medical supervision.",
      alcohol: "Avoid regular alcohol use.",
      driving: "Does not typically impair driving ability.",
    },
    interactions: ["Warfarin", "Alcohol"],
    foodInteractions: { beforeFood: "Either.", afterFood: "Preferred for sensitive stomachs.", avoid: ["Alcohol"] },
    storage: "Store below 30°C, away from moisture and sunlight.",
    alternatives: ["crocin-500", "calpol-500"],
    badges: { bestSeller: true, topRated: false, lowestPrice: false },
  },
  {
    id: "calpol-500",
    brand: "Calpol",
    genericName: "Paracetamol",
    strength: "500mg",
    manufacturer: "GSK",
    price: 20,
    packSize: "Strip of 15 tablets",
    otc: true,
    category: "Fever",
    rating: 4.2,
    popularity: 70,
    description: "A trusted paracetamol brand for fever and pain relief, available in tablet and syrup forms.",
    uses: ["Fever", "Mild pain", "Headache"],
    dosage: {
      adults: "1–2 tablets every 4–6 hours. Max 4g/day.",
      children: "Pediatric syrup dosage as per body weight — consult a doctor.",
      missedDose: "Take as soon as remembered.",
      overdose: "Seek emergency medical attention immediately.",
    },
    sideEffects: { common: ["Nausea"], rare: ["Rash", "Liver damage (overdose)"] },
    warnings: {
      pregnancy: "Considered safe at recommended doses.",
      breastfeeding: "Generally safe.",
      kidneyDisease: "Use with caution.",
      liverDisease: "Avoid without medical supervision.",
      alcohol: "Avoid regular use.",
      driving: "No typical impairment.",
    },
    interactions: ["Warfarin", "Alcohol"],
    foodInteractions: { beforeFood: "Either.", afterFood: "Preferred.", avoid: ["Alcohol"] },
    storage: "Store in a cool, dry place below 30°C.",
    alternatives: ["crocin-500", "dolo-650"],
    badges: { bestSeller: false, topRated: false, lowestPrice: false },
  },
  {
    id: "cetrizine-d",
    brand: "Cetrizine-D",
    genericName: "Cetirizine",
    strength: "10mg",
    manufacturer: "Cipla",
    price: 22,
    packSize: "Strip of 10 tablets",
    otc: true,
    category: "Cold & Cough",
    rating: 4.0,
    popularity: 60,
    description: "An antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes.",
    uses: ["Allergic rhinitis", "Sneezing", "Runny nose", "Itchy/watery eyes"],
    dosage: {
      adults: "1 tablet (10mg) once daily.",
      children: "Half dose for children 6–12 years, under medical advice.",
      missedDose: "Take as soon as remembered; skip if close to next dose.",
      overdose: "May cause drowsiness or restlessness — consult a doctor.",
    },
    sideEffects: { common: ["Drowsiness", "Dry mouth"], rare: ["Blurred vision", "Rapid heartbeat"] },
    warnings: {
      pregnancy: "Use only if advised by a doctor.",
      breastfeeding: "Consult your doctor.",
      kidneyDisease: "Dose adjustment may be needed.",
      liverDisease: "Use with caution.",
      alcohol: "Avoid — may increase drowsiness.",
      driving: "May cause drowsiness — avoid driving until you know how it affects you.",
    },
    interactions: ["Alcohol", "Sedatives", "Theophylline"],
    foodInteractions: { beforeFood: "Either.", afterFood: "Either.", avoid: [] },
    storage: "Store below 25°C, protect from light.",
    alternatives: [],
    badges: { bestSeller: false, topRated: false, lowestPrice: false },
  },
  {
    id: "electral-ors",
    brand: "Electral",
    genericName: "ORS (Oral Rehydration Salts)",
    strength: "21.8g sachet",
    manufacturer: "FDC",
    price: 25,
    packSize: "Box of 10 sachets",
    otc: true,
    category: "Digestive Care",
    rating: 4.6,
    popularity: 85,
    description: "Oral rehydration salts used to restore fluids and electrolytes lost due to dehydration, diarrhea, or vomiting.",
    uses: ["Dehydration", "Diarrhea", "Heat exhaustion", "Vomiting"],
    dosage: {
      adults: "1 sachet dissolved in 1 liter of clean water; sip throughout the day.",
      children: "As advised by a pediatrician based on dehydration severity.",
      missedDose: "Not applicable — take as needed.",
      overdose: "Excess intake may cause electrolyte imbalance — consult a doctor if unwell.",
    },
    sideEffects: { common: ["Mild bloating"], rare: ["Vomiting if taken too concentrated"] },
    warnings: {
      pregnancy: "Safe to use.",
      breastfeeding: "Safe to use.",
      kidneyDisease: "Use with medical guidance.",
      liverDisease: "Generally safe.",
      alcohol: "No known interaction.",
      driving: "No impairment.",
    },
    interactions: [],
    foodInteractions: { beforeFood: "Either.", afterFood: "Either.", avoid: [] },
    storage: "Store the prepared solution in a fridge and discard after 24 hours.",
    alternatives: [],
    badges: { bestSeller: true, topRated: true, lowestPrice: false },
  },
  {
    id: "limcee-vitc",
    brand: "Limcee",
    genericName: "Vitamin C (Ascorbic Acid)",
    strength: "500mg",
    manufacturer: "Abbott",
    price: 30,
    packSize: "Strip of 15 chewable tablets",
    otc: true,
    category: "Vitamins",
    rating: 4.1,
    popularity: 55,
    description: "A chewable Vitamin C supplement that supports immunity and skin health.",
    uses: ["Vitamin C deficiency", "Immunity support", "Antioxidant supplementation"],
    dosage: {
      adults: "1 tablet daily, or as directed by a physician.",
      children: "As advised by a pediatrician.",
      missedDose: "Take as soon as remembered.",
      overdose: "High doses may cause stomach upset or diarrhea.",
    },
    sideEffects: { common: ["Mild stomach upset"], rare: ["Kidney stones with prolonged high doses"] },
    warnings: {
      pregnancy: "Safe within recommended doses.",
      breastfeeding: "Safe within recommended doses.",
      kidneyDisease: "Use with caution — consult your doctor.",
      liverDisease: "Generally safe.",
      alcohol: "No known interaction.",
      driving: "No impairment.",
    },
    interactions: ["Iron supplements (increases absorption)"],
    foodInteractions: { beforeFood: "Either.", afterFood: "Either.", avoid: [] },
    storage: "Store in a cool, dry place.",
    alternatives: [],
    badges: { bestSeller: false, topRated: false, lowestPrice: false },
  },
  {
    id: "digene-antacid",
    brand: "Digene",
    genericName: "Antacid (Magaldrate + Simethicone)",
    strength: "10ml",
    manufacturer: "Abbott",
    price: 45,
    packSize: "170ml bottle",
    otc: true,
    category: "Digestive Care",
    rating: 3.9,
    popularity: 50,
    description: "An antacid gel that relieves acidity, heartburn, and gas.",
    uses: ["Acidity", "Heartburn", "Gas/bloating", "Indigestion"],
    dosage: {
      adults: "1–2 teaspoons (5–10ml) after meals and at bedtime.",
      children: "Not recommended without medical advice.",
      missedDose: "Take when needed; not a scheduled medication.",
      overdose: "Excess use may cause diarrhea or electrolyte imbalance.",
    },
    sideEffects: { common: ["Mild diarrhea"], rare: ["Constipation"] },
    warnings: {
      pregnancy: "Generally considered safe — consult your doctor.",
      breastfeeding: "Generally safe.",
      kidneyDisease: "Use with caution.",
      liverDisease: "Generally safe.",
      alcohol: "No major interaction.",
      driving: "No impairment.",
    },
    interactions: ["Tetracycline antibiotics", "Iron supplements"],
    foodInteractions: { beforeFood: "Not typical.", afterFood: "Take after meals.", avoid: [] },
    storage: "Store below 30°C. Shake well before use.",
    alternatives: ["gelusil-antacid"],
    badges: { bestSeller: false, topRated: false, lowestPrice: false },
  },
  {
    id: "gelusil-antacid",
    brand: "Gelusil",
    genericName: "Antacid (Aluminium + Magnesium Hydroxide)",
    strength: "10ml",
    manufacturer: "Zydus",
    price: 40,
    packSize: "170ml bottle",
    otc: true,
    category: "Digestive Care",
    rating: 3.8,
    popularity: 45,
    description: "An antacid suspension for fast relief from acidity and heartburn.",
    uses: ["Acidity", "Heartburn", "Indigestion"],
    dosage: {
      adults: "1–2 teaspoons after meals and at bedtime.",
      children: "Not recommended without medical advice.",
      missedDose: "Take when needed.",
      overdose: "Excess use may cause bowel disturbances.",
    },
    sideEffects: { common: ["Mild constipation"], rare: ["Diarrhea"] },
    warnings: {
      pregnancy: "Consult your doctor.",
      breastfeeding: "Generally safe.",
      kidneyDisease: "Use with caution.",
      liverDisease: "Generally safe.",
      alcohol: "No major interaction.",
      driving: "No impairment.",
    },
    interactions: ["Tetracycline antibiotics"],
    foodInteractions: { beforeFood: "Not typical.", afterFood: "Take after meals.", avoid: [] },
    storage: "Store below 30°C. Shake well before use.",
    alternatives: ["digene-antacid"],
    badges: { bestSeller: false, topRated: false, lowestPrice: false },
  },
  {
    id: "novamox-500",
    brand: "Novamox",
    genericName: "Amoxicillin",
    strength: "500mg",
    manufacturer: "Cipla",
    price: 85,
    packSize: "Strip of 10 capsules",
    otc: false,
    category: "Antibiotics",
    rating: 4.4,
    popularity: 65,
    description: "A penicillin-based antibiotic used to treat a wide range of bacterial infections. Requires a valid prescription.",
    uses: ["Bacterial infections", "Respiratory tract infections", "Urinary tract infections"],
    dosage: {
      adults: "As prescribed by your doctor — typically 500mg every 8 hours.",
      children: "Dose calculated by body weight — prescription only.",
      missedDose: "Take as soon as remembered; do not double dose.",
      overdose: "Seek medical attention immediately.",
    },
    sideEffects: { common: ["Nausea", "Diarrhea"], rare: ["Allergic reaction", "Rash"] },
    warnings: {
      pregnancy: "Use only if prescribed by your doctor.",
      breastfeeding: "Consult your doctor.",
      kidneyDisease: "Dose adjustment may be required.",
      liverDisease: "Use with caution.",
      alcohol: "Generally avoid during the course.",
      driving: "No typical impairment.",
    },
    interactions: ["Oral contraceptives", "Warfarin", "Methotrexate"],
    foodInteractions: { beforeFood: "Either.", afterFood: "Either.", avoid: [] },
    storage: "Store below 25°C in a dry place.",
    alternatives: [],
    badges: { bestSeller: false, topRated: true, lowestPrice: false },
  },
  {
    id: "glycomet-500",
    brand: "Glycomet",
    genericName: "Metformin",
    strength: "500mg",
    manufacturer: "USV",
    price: 40,
    packSize: "Strip of 20 tablets",
    otc: false,
    category: "Diabetes",
    rating: 4.3,
    popularity: 60,
    description: "An oral medication used to control blood sugar levels in type 2 diabetes. Requires a valid prescription.",
    uses: ["Type 2 diabetes management", "Blood sugar control"],
    dosage: {
      adults: "As prescribed — typically 500mg 1–2 times daily with meals.",
      children: "Prescription only, under specialist supervision.",
      missedDose: "Take with the next meal; do not double dose.",
      overdose: "Can cause dangerously low blood sugar — seek emergency help.",
    },
    sideEffects: { common: ["Nausea", "Stomach upset", "Diarrhea"], rare: ["Lactic acidosis (rare but serious)"] },
    warnings: {
      pregnancy: "Use only under specialist supervision.",
      breastfeeding: "Consult your doctor.",
      kidneyDisease: "Contraindicated in severe kidney disease.",
      liverDisease: "Use with caution.",
      alcohol: "Avoid — increases risk of lactic acidosis.",
      driving: "May cause low blood sugar — monitor before driving.",
    },
    interactions: ["Alcohol", "Contrast dye (imaging)", "Diuretics"],
    foodInteractions: { beforeFood: "Not typical.", afterFood: "Take with meals to reduce stomach upset.", avoid: ["Excess alcohol"] },
    storage: "Store below 30°C in a dry place.",
    alternatives: [],
    badges: { bestSeller: false, topRated: false, lowestPrice: false },
  },
  {
    id: "betadine-oint",
    brand: "Betadine",
    genericName: "Povidone Iodine",
    strength: "5% w/w",
    manufacturer: "Win-Medicare",
    price: 55,
    packSize: "20g tube",
    otc: true,
    category: "Skin Care",
    rating: 4.0,
    popularity: 40,
    description: "An antiseptic ointment used to prevent infection in minor cuts, wounds, and burns.",
    uses: ["Minor cuts", "Wounds", "Burns", "Skin infections"],
    dosage: {
      adults: "Apply a thin layer to the affected area 2–3 times daily.",
      children: "Apply sparingly; consult a doctor for infants.",
      missedDose: "Not applicable — apply as needed.",
      overdose: "Not applicable for topical use; avoid ingestion.",
    },
    sideEffects: { common: ["Mild skin irritation"], rare: ["Allergic contact dermatitis"] },
    warnings: {
      pregnancy: "Use with caution — consult your doctor for large areas.",
      breastfeeding: "Avoid applying near the breast area.",
      kidneyDisease: "Avoid prolonged use on large wounds.",
      liverDisease: "Generally safe for topical use.",
      alcohol: "No interaction.",
      driving: "No impairment.",
    },
    interactions: ["Other topical antiseptics (avoid combining)"],
    foodInteractions: { beforeFood: "Not applicable.", afterFood: "Not applicable.", avoid: [] },
    storage: "Store below 30°C. Keep the tube tightly closed.",
    alternatives: [],
    badges: { bestSeller: false, topRated: false, lowestPrice: false },
  },
];

export function getAllMedicines() {
  return MEDICINES;
}

export function getMedicineById(id) {
  return MEDICINES.find((m) => m.id === id) || null;
}

export function getAlternatives(medicine) {
  if (!medicine) return [];
  return medicine.alternatives.map((id) => getMedicineById(id)).filter(Boolean);
}

export function getRelatedMedicines(medicine, limit = 4) {
  if (!medicine) return [];
  return MEDICINES.filter((m) => m.category === medicine.category && m.id !== medicine.id).slice(0, limit);
}

export function getPopularMedicines(limit = 4) {
  return [...MEDICINES].sort((a, b) => b.popularity - a.popularity).slice(0, limit);
}

const RECENT_KEY = "medibridge_recently_viewed";

export function addRecentlyViewed(id) {
  const existing = JSON.parse(localStorage.getItem(RECENT_KEY) || "[]");
  const updated = [id, ...existing.filter((x) => x !== id)].slice(0, 6);
  localStorage.setItem(RECENT_KEY, JSON.stringify(updated));
}

export function getRecentlyViewed(limit = 4) {
  const ids = JSON.parse(localStorage.getItem(RECENT_KEY) || "[]");
  return ids.map((id) => getMedicineById(id)).filter(Boolean).slice(0, limit);
}