// Realistic pharmacy dataset for the Nearby Pharmacy page.
// Swap getNearbyPharmacies() for a real geolocation-based API call later.

export const NEARBY_PHARMACIES = [
  {
    id: "ph-1",
    name: "Apollo Pharmacy",
    medicineName: "Paracetamol",
    distance: "0.8 km",
    distanceKm: 0.8,
    travelTime: { drive: "3 min drive", walk: "10 min walk" },
    rating: 4.6,
    isOpen: true,
    closingTime: "10:00 PM",
    openingTime: "8:00 AM",
    availability: "in-stock",
    price: 18,
    phone: "+91 98765 43210",
    address: "Gandhipuram, Coimbatore",
    otc: true,
  },
  {
    id: "ph-2",
    name: "MedPlus",
    medicineName: "Paracetamol",
    distance: "1.4 km",
    distanceKm: 1.4,
    travelTime: { drive: "5 min drive", walk: "16 min walk" },
    rating: 4.5,
    isOpen: true,
    closingTime: "9:30 PM",
    openingTime: "8:30 AM",
    availability: "limited",
    price: 20,
    phone: "+91 98765 12345",
    address: "RS Puram, Coimbatore",
    otc: true,
  },
  {
    id: "ph-3",
    name: "Wellness Forever",
    medicineName: "Paracetamol",
    distance: "2.2 km",
    distanceKm: 2.2,
    travelTime: { drive: "7 min drive", walk: "26 min walk" },
    rating: 4.4,
    isOpen: false,
    closingTime: "9:00 PM",
    openingTime: "8:00 AM",
    availability: "in-stock",
    price: 19,
    phone: "+91 98765 56789",
    address: "Peelamedu, Coimbatore",
    otc: true,
  },
  {
    id: "ph-4",
    name: "Netmeds Pharmacy",
    medicineName: "Cetirizine",
    distance: "2.9 km",
    distanceKm: 2.9,
    travelTime: { drive: "9 min drive", walk: "34 min walk" },
    rating: 4.3,
    isOpen: true,
    closingTime: "11:00 PM",
    openingTime: "24 hours",
    availability: "out",
    price: 22,
    phone: "+91 98765 98765",
    address: "Saibaba Colony, Coimbatore",
    otc: true,
  },
  {
    id: "ph-5",
    name: "Sri Ramakrishna Pharmacy",
    medicineName: "Amoxicillin",
    distance: "3.5 km",
    distanceKm: 3.5,
    travelTime: { drive: "11 min drive", walk: "42 min walk" },
    rating: 4.2,
    isOpen: true,
    closingTime: "10:30 PM",
    openingTime: "7:00 AM",
    availability: "in-stock",
    price: 85,
    phone: "+91 98765 22334",
    address: "Sitra, Coimbatore",
    otc: false,
  },
];

export function getNearbyPharmacies() {
  return NEARBY_PHARMACIES;
}