import fs from "fs";

const pharmacyTranslations = {
  en: {
    "pharmacy.title": "Nearby Pharmacies",
    "pharmacy.subtitle": "Locate verified pharmacies near you with real-time stock and prices.",
    "pharmacy.open": "Open Now",
    "pharmacy.closed": "Closed",
    "pharmacy.inStock": "In Stock",
    "pharmacy.limitedStock": "Limited Stock",
    "pharmacy.outOfStock": "Out of Stock",
    "pharmacy.verifiedStock": "Verified Stock",
    "pharmacy.demoData": "Sample Data",
    "pharmacy.closesAt": "Closes at",
    "pharmacy.opensAt": "Opens at",
    "pharmacy.viewMap": "View Map",
    "pharmacy.getDirections": "Get Directions",
    "pharmacy.outOfStockOrderUnavailable": "Out of Stock - Order Unavailable",
    "pharmacy.noPharmacies": "No Nearby Pharmacies Found",
    "pharmacy.noPharmaciesDesc": "No active pharmacies match your current location or filter criteria.",
    "pharmacy.locating": "Finding nearby pharmacies...",
    "pharmacy.driveTime": "{count} min drive",
    "pharmacy.walkTime": "{count} min walk",
  },
  ta: {
    "pharmacy.title": "அருகிலுள்ள மருந்தகங்கள்",
    "pharmacy.subtitle": "நேரலை இருப்பு மற்றும் விலைகளுடன் அருகிலுள்ள மருந்தகங்களைக் கண்டறியவும்.",
    "pharmacy.open": "திறந்துள்ளது",
    "pharmacy.closed": "மூடப்பட்டுள்ளது",
    "pharmacy.inStock": "இருப்பில் உள்ளது",
    "pharmacy.limitedStock": "குறைந்த இருப்பு",
    "pharmacy.outOfStock": "இருப்பில் இல்லை",
    "pharmacy.verifiedStock": "சரிபார்க்கப்பட்ட இருப்பு",
    "pharmacy.demoData": "மாதிரித் தரவு",
    "pharmacy.closesAt": "மூடும் நேரம்",
    "pharmacy.opensAt": "திறக்கும் நேரம்",
    "pharmacy.viewMap": "வரைபடத்தைப் பார்",
    "pharmacy.getDirections": "வழித்தடத்தைப் பெறு",
    "pharmacy.outOfStockOrderUnavailable": "இருப்பில் இல்லை - ஆர்டர் செய்ய முடியாது",
    "pharmacy.noPharmacies": "அருகில் மருந்தகங்கள் எதுவும் இல்லை",
    "pharmacy.noPharmaciesDesc": "உங்கள் இருப்பிடத்திற்கு அருகில் எந்த மருந்தகமும் கிடைக்கவில்லை.",
    "pharmacy.locating": "அருகிலுள்ள மருந்தகங்களைத் தேடுகிறது...",
    "pharmacy.driveTime": "{count} நிமி ஓட்டம்",
    "pharmacy.walkTime": "{count} நிமி நடை",
  },
  hi: {
    "pharmacy.title": "निकटतम फार्मेसी",
    "pharmacy.subtitle": "वास्तविक स्टॉक और कीमतों के साथ अपने पास की सत्यापित फार्मेसी खोजें।",
    "pharmacy.open": "खुला है",
    "pharmacy.closed": "बंद है",
    "pharmacy.inStock": "स्टॉक में उपलब्ध",
    "pharmacy.limitedStock": "सीमित स्टॉक",
    "pharmacy.outOfStock": "स्टॉक में नहीं",
    "pharmacy.verifiedStock": "सत्यापित स्टॉक",
    "pharmacy.demoData": "नमूना डेटा",
    "pharmacy.closesAt": "बंद होने का समय",
    "pharmacy.opensAt": "खुलने का समय",
    "pharmacy.viewMap": "मानचित्र देखें",
    "pharmacy.getDirections": "दिशा-निर्देश प्राप्त करें",
    "pharmacy.outOfStockOrderUnavailable": "स्टॉक समाप्त - ऑर्डर अनुपलब्ध",
    "pharmacy.noPharmacies": "कोई निकटतम फार्मेसी नहीं मिली",
    "pharmacy.noPharmaciesDesc": "आपकी वर्तमान स्थिति के पास कोई फार्मेसी उपलब्ध नहीं है।",
    "pharmacy.locating": "पास की फार्मेसियों की खोज की जा रही है...",
    "pharmacy.driveTime": "{count} मिनट की ड्राइव",
    "pharmacy.walkTime": "{count} मिनट की पैदल दूरी",
  },
  te: {
    "pharmacy.title": "సమీప ఫార్మసీలు",
    "pharmacy.subtitle": "రియల్ టైమ్ స్టాక్ మరియు ధరలతో మీకు సమీపంలో ఉన్న ఫార్మసీలను కనుగొనండి.",
    "pharmacy.open": "తెరిచి ఉంది",
    "pharmacy.closed": "మూసివేయబడింది",
    "pharmacy.inStock": "స్టాక్ అందుబాటులో ఉంది",
    "pharmacy.limitedStock": "పరిమిత స్టాక్",
    "pharmacy.outOfStock": "స్టాక్ లేదు",
    "pharmacy.verifiedStock": "ధృవీకరించబడిన స్టాక్",
    "pharmacy.demoData": "నమూనా డేటా",
    "pharmacy.closesAt": "మూసివేసే సమయం",
    "pharmacy.opensAt": "తెరిచే సమయం",
    "pharmacy.viewMap": "మ్యాప్‌ను చూడండి",
    "pharmacy.getDirections": "దిశలను పొందండి",
    "pharmacy.outOfStockOrderUnavailable": "స్టాక్ లేదు - ఆర్డర్ లభించదు",
    "pharmacy.noPharmacies": "సమీపంలో ఫార్మసీలు కనుగొనబడలేదు",
    "pharmacy.noPharmaciesDesc": "మీ స్థానానికి సమీపంలో ఫార్మసీలు లభించలేదు.",
    "pharmacy.locating": "సమీప ఫార్మసీలను శోధిస్తోంది...",
    "pharmacy.driveTime": "{count} నిమి డ్రైవ్",
    "pharmacy.walkTime": "{count} నిమి నడక",
  },
  ml: {
    "pharmacy.title": "സമീപത്തെ ഫാർമസികൾ",
    "pharmacy.subtitle": "തത്സമയ സ്റ്റോക്കും വിലയും ഉപയോഗിച്ച് സമീപത്തെ ഫാർമസികൾ കണ്ടെത്തുക.",
    "pharmacy.open": "തുറന്നിരിക്കുന്നു",
    "pharmacy.closed": "അടച്ചിരിക്കുന്നു",
    "pharmacy.inStock": "സ്റ്റോക്കുണ്ട്",
    "pharmacy.limitedStock": "പരിമിതമായ സ്റ്റോക്ക്",
    "pharmacy.outOfStock": "സ്റ്റോക്കില്ല",
    "pharmacy.verifiedStock": "സ്ഥിരീകരിച്ച സ്റ്റോക്ക്",
    "pharmacy.demoData": "മാതൃകാ ഡാറ്റ",
    "pharmacy.closesAt": "അടയ്ക്കുന്ന സമയം",
    "pharmacy.opensAt": "തുറക്കുന്ന സമയം",
    "pharmacy.viewMap": "മാപ്പ് കാണുക",
    "pharmacy.getDirections": "വഴി കണ്ടെത്തുക",
    "pharmacy.outOfStockOrderUnavailable": "സ്റ്റോക്കില്ല - ഓർഡർ ലഭ്യമായിട്ടില്ല",
    "pharmacy.noPharmacies": "സമീപത്ത് ഫാർമസികളൊന്നും കണ്ടെത്തിയില്ല",
    "pharmacy.noPharmaciesDesc": "നിങ്ങളുടെ ലൊക്കേഷന് സമീപം ഫാർമസികളൊന്നും ലഭ്യമല്ല.",
    "pharmacy.locating": "സമീപത്തെ ഫാർമസികൾ തിരയുന്നു...",
    "pharmacy.driveTime": "{count} മിനിറ്റ് ഡ്രൈവ്",
    "pharmacy.walkTime": "{count} മിനിറ്റ് നടപ്പ്",
  },
  kn: {
    "pharmacy.title": "ಸಮೀಪದ ಫಾರ್ಮಸಿಗಳು",
    "pharmacy.subtitle": "ನೈಜ-ಸಮಯದ ಸ್ಟಾಕ್ ಮತ್ತು ಬೆಲೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಸಮೀಪದ ಫಾರ್ಮಸಿಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.",
    "pharmacy.open": "ತೆರೆದಿದೆ",
    "pharmacy.closed": "ಮುಚ್ಚಲಾಗಿದೆ",
    "pharmacy.inStock": "ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ",
    "pharmacy.limitedStock": "ಸೀಮಿತ ಸ್ಟಾಕ್",
    "pharmacy.outOfStock": "ಸ್ಟಾಕ್ ಇಲ್ಲ",
    "pharmacy.verifiedStock": "ಪರಿಶೀಲಿಸಿದ ಸ್ಟಾಕ್",
    "pharmacy.demoData": "ಮಾದರಿ ಡೇಟಾ",
    "pharmacy.closesAt": "ಮುಚ್ಚುವ ಸಮಯ",
    "pharmacy.opensAt": "ತೆರೆಯುವ ಸಮಯ",
    "pharmacy.viewMap": "ನಕ್ಷೆ ನೋಡಿ",
    "pharmacy.getDirections": "ದಾರಿ ಪಡೆಯಿರಿ",
    "pharmacy.outOfStockOrderUnavailable": "ಸ್ಟಾಕ್ ಇಲ್ಲ - ಆರ್ಡರ್ ಲಭ್ಯವಿಲ್ಲ",
    "pharmacy.noPharmacies": "ಸಮೀಪದಲ್ಲಿ ಯಾವುದೇ ಫಾರ್ಮಸಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    "pharmacy.noPharmaciesDesc": "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳದ ಹತ್ತಿರ ಯಾವುದೇ ಫಾರ್ಮಸಿ ಲಭ್ಯವಿಲ್ಲ.",
    "pharmacy.locating": "ಸಮೀಪದ ಫಾರ್ಮಸಿಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    "pharmacy.driveTime": "{count} ನಿಮಿಷ ಚಾಲನೆ",
    "pharmacy.walkTime": "{count} ನಿಮಿಷ ನಡಿಗೆ",
  },
};

const filePath = "client/src/i18n/translations.js";
let content = fs.readFileSync(filePath, "utf8");

Object.keys(pharmacyTranslations).forEach((lang) => {
  const dict = pharmacyTranslations[lang];
  const dictEntries = Object.entries(dict)
    .map(([k, v]) => `    "${k}": "${v.replace(/"/g, '\\"')}",`)
    .join("\n");

  const langTarget = `${lang}: {`;
  if (content.includes(langTarget)) {
    content = content.replace(langTarget, `${langTarget}\n${dictEntries}`);
  }
});

fs.writeFileSync(filePath, content);
console.log("Successfully inserted pharmacy translation keys into translations.js!");
