// Complete translations for all 175 medicine sentences across hi, ta, te, ml, kn

const ALL_SENTENCE_MAPS = {
  ta: {
    "Paracetamol is a widely used pain reliever and fever reducer, suitable for mild to moderate pain and fever in adults and children.": "பாராசிட்டமால் என்பது காய்ச்சல் மற்றும் மிதமான உடலை வதக்கும் வலிகளைக் குறைக்கும் பாதுகாப்பான மருந்தாகும்.",
    "Store below 30°C in a dry place, away from direct sunlight.": "நேரடி சூரிய ஒளியில் இருந்து விலகி, 30°C க்கு கீழே உலர்ந்த இடத்தில் சேமிக்கவும்.",
    "Fever": "காய்ச்சல்",
    "Headache": "தலைவலி",
    "Body ache": "உடல் வலி",
    "Toothache": "பல் வலி",
    "Cold-related pain": "சளி சார்ந்த வலி",
    "1–2 tablets (500–1000mg) every 4–6 hours. Do not exceed 4g/day.": "4-6 மணி நேரத்திற்கு ஒருமுறை 1-2 மாத்திரைகள் (500-1000 மிகி). ஒரு நாளில் 4 கிராமுக்கு மிகாமல் இருக்கவும்.",
    "As advised by a pediatrician based on body weight.": "குழந்தையின் உடல் எடைக் கேற்ப குழந்தைகள் மருத்துவரின் ஆலோசனைப்படி வழங்கவும்.",
    "Take as soon as you remember. Skip if it's almost time for the next dose.": "நினைவில் வரும்போது எடுத்துக்கொள்ளவும். அடுத்த வேளைக்கு நேரமாகிவிட்டால் தவிர்க்கவும்.",
    "Seek emergency medical attention immediately — overdose can cause liver damage.": "உடனடியாக அவசர மருத்துவ உதவியை நாடவும் — அதிகளவு உட்கொள்வது கல்லீரலை பாதிக்கும்.",
    "Nausea": "குமட்டல்",
    "Stomach upset": "வயிற்று உபாதை",
    "Skin rash": "தோல் தடிப்பு",
    "Allergic reaction": "ஒவ்வாமை எதிர்வினை",
    "Liver damage (with overdose)": "கல்லீரல் பாதிப்பு (அதிகளவு உட்கொண்டால்)",
    "Considered safe at recommended doses — consult your doctor.": "பரிந்துரைக்கப்பட்ட அளவுகளில் பாதுகாப்பானது — உங்கள் மருத்துவரை அணுகவும்.",
    "Generally considered safe.": "பொதுவாக பாதுகாப்பானதாக கருதப்படுகிறது.",
    "Use with caution; consult your doctor.": "எச்சரிக்கையுடன் பயன்படுத்தவும்; உங்கள் மருத்துவரை அணுகவும்.",
    "Avoid or use only under medical supervision.": "தவிர்க்கவும் அல்லது மருத்துவ மேற்பார்வையின் கீழ் மட்டுமே பயன்படுத்தவும்.",
    "Avoid regular alcohol use — increases liver damage risk.": "வழக்கமான மது அருந்துவதைத் தவிர்க்கவும் — கல்லீரல் பாதிப்பு ஆபத்தை அதிகரிக்கும்.",
    "Does not typically impair driving ability.": "பொதுவாக வாகனம் ஓட்டும் திறனை பாதிக்காது.",
    "Warfarin": "வார்ஃபரின்",
    "Alcohol": "மதுபானம்",
    "Other paracetamol-containing products": "பாராசிட்டமால் அடங்கிய பிற மருந்துகள்",
    "Can be taken before or after food.": "உணவுக்கு முன்போ அல்லது பின்போ எடுத்துக்கொள்ளலாம்.",
    "Preferred if you have a sensitive stomach.": "செரிமானப் பிரச்சனை இருந்தால் உணவுக்குப் பின் உட்கொள்வது சிறந்தது.",
    "A higher-strength paracetamol formulation commonly used for fever and moderate pain relief.": "காய்ச்சல் மற்றும் தீவிர வலி நிவாரணத்திற்கு பயன்படும் அதிக வீரியமுள்ள பாராசிட்டமால் மருந்து.",
    "Store below 30°C, away from moisture and sunlight.": "ஈரப்பதம் மற்றும் சூரிய ஒளியில் இருந்து விலகி 30°C க்கு கீழே சேமிக்கவும்.",
    "1 tablet (650mg) every 6–8 hours. Do not exceed 3 tablets/day.": "6-8 மணி நேரத்திற்கு 1 மாத்திரை (650 மிகி). ஒரு நாளில் 3 மாத்திரைகளுக்கு மிகாமல் இருக்கவும்.",
    "Not recommended below 12 years without medical advice.": "மருத்துவர் ஆலோசனையின்றி 12 வயதுக்குட்பட்ட குழந்தைகளுக்கு பரிந்துரைக்கப்படுவதில்லை.",
    "Take as soon as you remember; skip if close to the next dose.": "நினைவில் வந்தவுடன் உட்கொள்ளவும்; அடுத்த வேளை நெருங்கினால் தவிர்க்கவும்.",
    "Seek emergency medical attention immediately.": "உடனடியாக அவசர மருத்துவ உதவியைப் பெறவும்.",
    "Consult your doctor before use.": "பயன்படுத்துவதற்கு முன் உங்கள் மருத்துவரை அணுகவும்.",
    "Use with caution.": "எச்சரிக்கையுடன் பயன்படுத்தவும்.",
    "Avoid regular alcohol use.": "வழக்கமான மது அருந்துவதைத் தவிர்க்கவும்.",
    "Either.": "உணவுக்கு முன் அல்லது பின் எடுத்துக்கொள்ளலாம்.",
    "Preferred for sensitive stomachs.": "வயிற்று உபாதை உள்ளவர்களுக்கு உணவுக்கு பின் சிறந்தது.",
    "A trusted paracetamol brand for fever and pain relief, available in tablet and syrup forms.": "காய்ச்சல் மற்றும் வலி நிவாரணத்திற்கான நம்பகமான பாராசிட்டமால் பிராண்ட்.",
    "Store in a cool, dry place below 30°C.": "30°C க்கு கீழே குளிர்ந்த, உலர்ந்த இடத்தில் சேமிக்கவும்.",
    "Mild pain": "மிதமான வலி",
    "1–2 tablets every 4–6 hours. Max 4g/day.": "4-6 மணி நேரத்திற்கு 1-2 மாத்திரைகள். அதிகபட்சம் 4 கிராம்/நாள்.",
    "Pediatric syrup dosage as per body weight — consult a doctor.": "உடல் எடைக் கேற்ப குழந்தைகள் சிரப் அளவு — மருத்துவரை அணுகவும்.",
    "Take as soon as remembered.": "நினைவில் வரும்போது எடுத்துக்கொள்ளவும்.",
    "Rash": "தோல் தடிப்பு",
    "Liver damage (overdose)": "கல்லீரல் பாதிப்பு (அதிகளவு)",
    "Considered safe at recommended doses.": "பரிந்துரைக்கப்பட்ட அளவுகளில் பாதுகாப்பானது.",
    "Generally safe.": "பொதுவாக பாதுகாப்பானது.",
    "Avoid without medical supervision.": "மருத்துவ கண்காணிப்பு இல்லாமல் தவிர்க்கவும்.",
    "Avoid regular use.": "தொடர்ந்து பயன்படுத்துவதைத் தவிர்க்கவும்.",
    "No typical impairment.": "வாகனம் ஓட்டுவதில் பாதிப்பில்லை.",
    "Preferred.": "பரிந்துரைக்கப்படுகிறது.",
    "An antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes.": "தும்மல், மூக்கு ஒழுகுதல் மற்றும் அரிப்பு போன்ற ஒவ்வாமை அறிகுறிகளைப் போக்கும் ஆன்டிஹிஸ்டமைன் மருந்து.",
    "Store below 25°C, protect from light.": "ஒளியில் இருந்து பாதுகாத்து 25°C க்கு கீழே சேமிக்கவும்.",
    "Allergic rhinitis": "ஒவ்வாமை மூக்கடைப்பு",
    "Sneezing": "தும்மல்",
    "Runny nose": "மூக்கு ஒழுகுதல்",
    "Itchy/watery eyes": "அரிப்பு/நீர்வடியும் கண்கள்",
    "1 tablet (10mg) once daily.": "தினமும் ஒரு முறை 1 மாத்திரை (10 மிகி).",
    "Half dose for children 6–12 years, under medical advice.": "6-12 வயது குழந்தைகளுக்கு மருத்துவர் ஆலோசனையுடன் அரை அளவு கொடுக்கவும்.",
    "Take as soon as remembered; skip if close to next dose.": "நினைவில் வந்தவுடன் உட்கொள்ளவும்; அடுத்த வேளை நெருங்கினால் தவிர்க்கவும்.",
    "May cause drowsiness or restlessness — consult a doctor.": "தூக்க கலக்கம் அல்லது அமைதியின்மையை ஏற்படுத்தலாம் — மருத்துவரை அணுகவும்.",
    "Drowsiness": "தூக்க கலக்கம்",
    "Dry mouth": "வறண்ட வாய்",
    "Blurred vision": "மங்கலான பார்வை",
    "Rapid heartbeat": "வேகமான இதயத் துடிப்பு",
    "Use only if advised by a doctor.": "மருத்துவர் அறிவுறுத்தினால் மட்டுமே பயன்படுத்தவும்.",
    "Consult your doctor.": "உங்கள் மருத்துவரை அணுகவும்.",
    "Dose adjustment may be needed.": "அளவு மாற்றம் தேவைப்படலாம்.",
    "Avoid — may increase drowsiness.": "தவிர்க்கவும் — தூக்க கலக்கத்தை அதிகரிக்கும்.",
    "May cause drowsiness — avoid driving until you know how it affects you.": "தூக்க கலக்கத்தை ஏற்படுத்தலாம் — வாகனம் ஓட்டுவதைத் தவிர்க்கவும்.",
    "Sedatives": "மயக்க மருந்துகள்",
    "Theophylline": "தியோஃபிலின்",
    "Oral rehydration salts used to restore fluids and electrolytes lost due to dehydration, diarrhea, or vomiting.": "நீரிழப்பு மற்றும் வயிற்றுப்போக்கால் இழந்த நீரை மீட்டெடுக்க பயன்படும் ஓஆர்எஸ் கரைசல்.",
    "Store the prepared solution in a fridge and discard after 24 hours.": "தயாரிக்கப்பட்ட கரைசலை குளிர்சாதன பெட்டியில் வைத்து 24 மணி நேரத்திற்குப் பின் அகற்றவும்.",
    "Dehydration": "நீரிழப்பு",
    "Diarrhea": "வயிற்றுப்போக்கு",
    "Heat exhaustion": "வெப்ப சோர்வு",
    "Vomiting": "வாந்தி",
    "1 sachet dissolved in 1 liter of clean water; sip throughout the day.": "1 பாக்கெட்டை 1 லிட்டர் சுத்தமான தண்ணீரில் கரைத்து நாள் முழுவதும் பருகவும்.",
    "As advised by a pediatrician based on dehydration severity.": "நீரிழப்பு தீவிரத்தின் அடிப்படையில் குழந்தைகள் மருத்துவரின் ஆலோசனையின் படி வழங்கவும்.",
    "Not applicable — take as needed.": "தேவைக்கேற்ப உட்கொள்ளலாம்.",
    "Excess intake may cause electrolyte imbalance — consult a doctor if unwell.": "அதிகளவு உட்கொள்வது எலக்ட்ரோலைட் சமநிலையின்மையை ஏற்படுத்தலாம்.",
    "Mild bloating": "மிதமான வயிற்று உப்பசம்",
    "Vomiting if taken too concentrated": "அடர்த்தியாக உட்கொண்டால் வாந்தி ஏற்படலாம்",
    "Safe to use.": "பயன்படுத்த பாதுகாப்பானது.",
    "Use with medical guidance.": "மருத்துவ வழிகாட்டுதலுடன் பயன்படுத்தவும்.",
    "No known interaction.": "அறியப்பட்ட பக்க விளைவு இடைவினைகள் எதுவும் இல்லை.",
    "No impairment.": "பாதிப்பில்லை.",
    "A chewable Vitamin C supplement that supports immunity and skin health.": "நோய் எதிர்ப்பு சக்தி மற்றும் சரும ஆரோக்கியத்தை மேம்படுத்தும் வைட்டமின் சி மருந்து.",
    "Store in a cool, dry place.": "குளிர்ந்த, உலர்ந்த இடத்தில் சேமிக்கவும்.",
    "Vitamin C deficiency": "வைட்டமின் சி குறைபாடு",
    "Immunity support": "நோய் எதிர்ப்பு சக்தி ஆதரவு",
    "Antioxidant supplementation": "ஆன்டி-ஆக்ஸிடன்ட் சத்து",
    "1 tablet daily, or as directed by a physician.": "தினமும் 1 மாத்திரை, அல்லது மருத்துவரின் வழிகாட்டுதலின் படி.",
    "As advised by a pediatrician.": "குழந்தைகள் மருத்துவர் ஆலோசனைப்படி.",
    "High doses may cause stomach upset or diarrhea.": "அதிக அளவுகள் வயிற்று உபாதை அல்லது வயிற்றுப்போக்கை ஏற்படுத்தலாம்.",
    "Mild stomach upset": "மிதமான வயிற்று உபாதை",
    "Kidney stones with prolonged high doses": "நீண்ட காலம் அதிக அளவு உட்கொண்டால் சிறுநீரகக் கற்கள் வரலாம்",
    "Safe within recommended doses.": "பரிந்துரைக்கப்பட்ட அளவுகளில் பாதுகாப்பானது.",
    "Use with caution — consult your doctor.": "எச்சரிக்கையுடன் பயன்படுத்தவும் — உங்கள் மருத்துவரை அணுகவும்.",
    "Iron supplements (increases absorption)": "இரும்புச்சத்து மருந்துகள் (உறிஞ்சுதலை அதிகரிக்கும்)",
    "An antacid gel that relieves acidity, heartburn, and gas.": "அமிலத்தன்மை, நெஞ்செரிச்சல் மற்றும் வாயுத் தொல்லையை போக்கும் என்டாசிட் ஜெல்.",
    "Store below 30°C. Shake well before use.": "30°C க்கு கீழே சேமிக்கவும். பயன்படுத்துவதற்கு முன் நன்றாகக் குலுக்கவும்.",
    "Acidity": "அமிலத்தன்மை",
    "Heartburn": "நெஞ்செரிச்சல்",
    "Gas/bloating": "வாயு/வயிற்று உப்பசம்",
    "Indigestion": "செரியாமை",
    "1–2 teaspoons (5–10ml) after meals and at bedtime.": "உணவுக்குப் பிறகும் இரவிலும் 1-2 தேக்கரண்டி (5-10 மி.லி).",
    "Not recommended without medical advice.": "மருத்துவ ஆலோசனையின்றி பரிந்துரைக்கப்படுவதில்லை.",
    "Take when needed; not a scheduled medication.": "தேவைப்படும்போது உட்கொள்ளவும்.",
    "Excess use may cause diarrhea or electrolyte imbalance.": "அதிக பயன்பாடு வயிற்றுப்போக்கை ஏற்படுத்தலாம்.",
    "Mild diarrhea": "மிதமான வயிற்றுப்போக்கு",
    "Constipation": "மலச்சிக்கல்",
    "Generally considered safe — consult your doctor.": "பொதுவாக பாதுகாப்பானது — உங்கள் மருத்துவரை அணுகவும்.",
    "No major interaction.": "முக்கிய பக்க விளைவுகள் இல்லை.",
    "Tetracycline antibiotics": "டெட்ராசைக்ளின் ஆண்டிபயாடிக்ஸ்",
    "Iron supplements": "இரும்புச்சத்து மருந்துகள்",
    "Not typical.": "பாதிப்பில்லை.",
    "Take after meals.": "உணவுக்கு பின் உட்கொள்ளவும்.",
    "An antacid suspension for fast relief from acidity and heartburn.": "அமிலத்தன்மை மற்றும் நெஞ்செரிச்சலில் இருந்து விரைவான நிவாரணம் தரும் என்டாசிட் திரவம்.",
    "1–2 teaspoons after meals and at bedtime.": "உணவுக்குப் பிறகும் இரவிலும் 1-2 தேக்கரண்டி.",
    "Take when needed.": "தேவைப்படும்போது உட்கொள்ளவும்.",
    "Excess use may cause bowel disturbances.": "அதிக பயன்பாடு குடல் கோளாறுகளை ஏற்படுத்தலாம்.",
    "Mild constipation": "மிதமான மலச்சிக்கல்",
    "A penicillin-based antibiotic used to treat a wide range of bacterial infections. Requires a valid prescription.": "பாக்டீரியா தொற்றுகளுக்கு சிகிச்சையளிக்கும் ஆன்டிபயாடிக் மருந்து. மருத்துவ சீட்டு தேவை.",
    "Store below 25°C in a dry place.": "25°C க்கு கீழே உலர்ந்த இடத்தில் சேமிக்கவும்.",
    "Bacterial infections": "பாக்டீரியா தொற்றுகள்",
    "Respiratory tract infections": "சுவாசப்பாதை தொற்றுகள்",
    "Urinary tract infections": "சிறுநீரகப்பாதை தொற்றுகள்",
    "As prescribed by your doctor — typically 500mg every 8 hours.": "உங்கள் மருத்துவர் பரிந்துரைத்தபடி — பொதுவாக 8 மணி நேரத்திற்கு 500 மிகி.",
    "Dose calculated by body weight — prescription only.": "உடல் எடையைப் பொறுத்து அளவு கணக்கிடப்படுகிறது — மருத்துவ சீட்டு அவசியம்.",
    "Take as soon as remembered; do not double dose.": "நினைவில் வந்தவுடன் உட்கொள்ளவும்; இருமடங்கு அளவு எடுக்க வேண்டாம்.",
    "Seek medical attention immediately.": "உடனடியாக மருத்துவ உதவியை நாடவும்.",
    "Use only if prescribed by your doctor.": "மருத்துவர் பரிந்துரைத்தால் மட்டுமே பயன்படுத்தவும்.",
    "Dose adjustment may be required.": "அளவு மாற்றம் தேவைப்படலாம்.",
    "Generally avoid during the course.": "மருந்து உட்கொள்ளும் காலத்தில் மதுவைத் தவிர்க்கவும்.",
    "Oral contraceptives": "கருத்தடை மாத்திரைகள்",
    "Methotrexate": "மெத்தோட்ரெக்ஸேட்",
    "An oral medication used to control blood sugar levels in type 2 diabetes. Requires a valid prescription.": "டைப் 2 நீரிழிவு நோயில் ரத்த சர்க்கரை அளவைக் கட்டுப்படுத்தும் மருந்து. மருத்துவ சீட்டு தேவை.",
    "Store below 30°C in a dry place.": "30°C க்கு கீழே உலர்ந்த இடத்தில் சேமிக்கவும்.",
    "Type 2 diabetes management": "டைப் 2 நீரிழிவு மேலாண்மை",
    "Blood sugar control": "ரத்த சர்க்கரை கட்டுப்பாடு",
    "As prescribed — typically 500mg 1–2 times daily with meals.": "மருத்துவர் பரிந்துரைத்தபடி — தினமும் 1-2 முறை உணவோடு 500 மிகி.",
    "Prescription only, under specialist supervision.": "மருத்துவ சீட்டு மற்றும் நிபுணர் கண்காணிப்பில் மட்டுமே.",
    "Take with the next meal; do not double dose.": "அடுத்த உணவோடு உட்கொள்ளவும்; இருமடங்கு அளவு எடுக்க வேண்டாம்.",
    "Can cause dangerously low blood sugar — seek emergency help.": "சர்க்கரை அளவை ஆபத்தாகக் குறைக்கலாம் — அவசர உதவியை நாடவும்.",
    "Lactic acidosis (rare but serious)": "லாக்டிக் அசிடோசிஸ் (அபூர்வமானது ஆனால் தீவிரமானது)",
    "Use only under specialist supervision.": "சிறப்பு மருத்துவர் கண்காணிப்பில் மட்டுமே பயன்படுத்தவும்.",
    "Contraindicated in severe kidney disease.": "தீவிர சிறுநீரக நோயில் பயன்படுத்தக்கூடாது.",
    "Avoid — increases risk of lactic acidosis.": "தவிர்க்கவும் — லாக்டிக் அசிடோசிஸ் ஆபத்தை அதிகரிக்கும்.",
    "May cause low blood sugar — monitor before driving.": "ரத்த சர்க்கரையை குறைக்கலாம் — வாகனம் ஓட்டுவதற்கு முன் கவனிக்கவும்.",
    "Contrast dye (imaging)": "காண்ட்ராஸ்ட் டை",
    "Diuretics": "டயூரெடிக்ஸ்",
    "Take with meals to reduce stomach upset.": "வயிற்று உபாதையைக் குறைக்க உணவோடு உட்கொள்ளவும்.",
    "Excess alcohol": "அதிக மதுபானம்",
    "An antiseptic ointment used to prevent infection in minor cuts, wounds, and burns.": "சிறிய வெட்டுகள், காயங்கள் மற்றும் தீக்காயங்களில் தொற்று ஏற்படாமல் தடுக்கும் கிருமிநாசினி களிம்பு.",
    "Store below 30°C. Keep the tube tightly closed.": "30°C க்கு கீழே சேமிக்கவும். டியூப்பை நன்றாக மூடி வைக்கவும்.",
    "Minor cuts": "சிறிய வெட்டுகள்",
    "Wounds": "காயங்கள்",
    "Burns": "தீக்காயங்கள்",
    "Skin infections": "தோல் தொற்றுகள்",
    "Apply a thin layer to the affected area 2–3 times daily.": "பாதிக்கப்பட்ட இடத்தில் தினமும் 2-3 முறை மெலிதாக தடவவும்.",
    "Apply sparingly; consult a doctor for infants.": "குறைந்தளவில் தடவவும்; குழந்தைகளுக்கு மருத்துவரை அணுகவும்.",
    "Not applicable — apply as needed.": "தேவைக்கேற்ப தடவலாம்.",
    "Not applicable for topical use; avoid ingestion.": "வெளிப்புறப் பயன்பாட்டிற்கு மட்டுமே; விழுங்குவதைத் தவிர்க்கவும்.",
    "Mild skin irritation": "மிதமான தோல் எரிச்சல்",
    "Allergic contact dermatitis": "ஒவ்வாமை தோல் தடிப்பு",
    "Use with caution — consult your doctor for large areas.": "பெரிய காயங்களுக்கு மருத்துவரை அணுகவும்.",
    "Avoid applying near the breast area.": "மார்பகப் பகுதியில் தடவுவதைத் தவிர்க்கவும்.",
    "Avoid prolonged use on large wounds.": "பெரிய காயங்களில் தொடர்ந்து பயன்படுத்துவதைத் தவிர்க்கவும்.",
    "Generally safe for topical use.": "வெளிப்புறப் பயன்பாட்டிற்கு பாதுகாப்பானது.",
    "No interaction.": "பாதிப்பில்லை.",
    "Other topical antiseptics (avoid combining)": "பிற வெளிப்புற கிருமிநாசினிகளுடன் கலப்பதைத் தவிர்க்கவும்",
    "Not applicable.": "பொருந்தாது."
  },

  hi: {
    "Paracetamol is a widely used pain reliever and fever reducer, suitable for mild to moderate pain and fever in adults and children.": "पैरासिटामोल एक व्यापक रूप से इस्तेमाल की जाने वाली दर्द निवारक और बुखार कम करने वाली दवा है।",
    "Store below 30°C in a dry place, away from direct sunlight.": "सीधे धूप से दूर, 30°C से नीचे सूखी जगह पर स्टोर करें।",
    "Fever": "बुखार",
    "Headache": "सिरदर्द",
    "Body ache": "बदन दर्द",
    "Toothache": "दांत दर्द",
    "Cold-related pain": "सर्दी का दर्द",
    "1–2 tablets (500–1000mg) every 4–6 hours. Do not exceed 4g/day.": "हर 4-6 घंटे में 1-2 गोलियां (500-1000 मिग्रा)। प्रति दिन 4 ग्राम से अधिक न लें।",
    "As advised by a pediatrician based on body weight.": "शरीर के वजन के आधार पर बाल रोग विशेषज्ञ की सलाह के अनुसार।",
    "Take as soon as you remember. Skip if it's almost time for the next dose.": "याद आते ही लें। यदि अगली खुराक का समय हो गया है तो छोड़ दें।",
    "Seek emergency medical attention immediately — overdose can cause liver damage.": "तुरंत आपातकालीन सहायता लें — ओवरडोज से लीवर खराब हो सकता है।",
    "Nausea": "जी मिचलाना",
    "Stomach upset": "पेट खराब होना",
    "Skin rash": "त्वचा पर चकत्ते",
    "Allergic reaction": "एलर्जिक रिएक्शन",
    "Liver damage (with overdose)": "लीवर की क्षति (ओवरडोज के साथ)",
    "Considered safe at recommended doses — consult your doctor.": "अनुशंसित खुराक में सुरक्षित माना जाता है — अपने डॉक्टर से परामर्श करें।",
    "Generally considered safe.": "सामान्यतः सुरक्षित माना जाता है।",
    "Use with caution; consult your doctor.": "सावधानी से उपयोग करें; अपने डॉक्टर से परामर्श करें।",
    "Avoid or use only under medical supervision.": "बचें या केवल चिकित्सीय देखरेख में उपयोग करें।",
    "Avoid regular alcohol use — increases liver damage risk.": "नियमित शराब के सेवन से बचें — लीवर क्षति का खतरा बढ़ता है।",
    "Does not typically impair driving ability.": "आमतौर पर ड्राइविंग क्षमता को प्रभावित नहीं करता है।",
    "Warfarin": "वारफेरिन",
    "Alcohol": "अल्कोहल",
    "Other paracetamol-containing products": "अन्य पैरासिटामोल युक्त उत्पाद",
    "Can be taken before or after food.": "भोजन से पहले या बाद में लिया जा सकता है।",
    "Preferred if you have a sensitive stomach.": "संवेदनशील पेट होने पर भोजन के बाद बेहतर।",
    "A higher-strength paracetamol formulation commonly used for fever and moderate pain relief.": "बुखार और मध्यम दर्द से राहत के लिए पैरासिटामोल दवा।",
    "Store below 30°C, away from moisture and sunlight.": "नमी और धूप से दूर 30°C से नीचे स्टोर करें।",
    "1 tablet (650mg) every 6–8 hours. Do not exceed 3 tablets/day.": "हर 6-8 घंटे में 1 गोली (650 मिग्रा)। प्रति दिन 3 गोलियों से अधिक न लें।",
    "Not recommended below 12 years without medical advice.": "चिकित्सकीय सलाह के बिना 12 साल से कम उम्र में अनुशंसित नहीं।",
    "Take as soon as you remember; skip if close to the next dose.": "याद आते ही लें; यदि अगली खुराक का समय निकट है तो छोड़ दें।",
    "Seek emergency medical attention immediately.": "तुरंत आपातकालीन चिकित्सा सहायता लें।",
    "Consult your doctor before use.": "उपयोग करने से पहले अपने डॉक्टर से परामर्श करें।",
    "Use with caution.": "सावधानी से उपयोग करें।",
    "Avoid regular alcohol use.": "नियमित शराब के सेवन से बचें।",
    "Either.": "भोजन से पहले या बाद में ले सकते हैं।",
    "Preferred for sensitive stomachs.": "संवेदनशील पेट के लिए बेहतर।",
    "A trusted paracetamol brand for fever and pain relief, available in tablet and syrup forms.": "बुखार और दर्द से राहत के लिए एक विश्वसनीय ब्रांड।",
    "Store in a cool, dry place below 30°C.": "30°C से नीचे ठंडी, सूखी जगह पर स्टोर करें।",
    "Mild pain": "हल्का दर्द",
    "1–2 tablets every 4–6 hours. Max 4g/day.": "हर 4-6 घंटे में 1-2 गोलियां। अधिकतम 4 ग्राम/दिन।",
    "Pediatric syrup dosage as per body weight — consult a doctor.": "शरीर के वजन के अनुसार सीरप की खुराक — डॉक्टर से सलाह लें।",
    "Take as soon as remembered.": "याद आने पर लें।",
    "Rash": "चकत्ते",
    "Liver damage (overdose)": "लीवर क्षति (ओवरडोज)",
    "Considered safe at recommended doses.": "अनुशंसित खुराक में सुरक्षित।",
    "Generally safe.": "सामान्यतः सुरक्षित।",
    "Avoid without medical supervision.": "चिकित्सीय देखरेख के बिना बचें।",
    "Avoid regular use.": "नियमित उपयोग से बचें।",
    "No typical impairment.": "कोई प्रभाव नहीं।",
    "Preferred.": "अनुशंसित।",
    "An antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes.": "छींकने और बहती नाक जैसी एलर्जी से राहत दिलाने वाली दवा।",
    "Store below 25°C, protect from light.": "प्रकाश से बचाकर 25°C से नीचे स्टोर करें।",
    "Allergic rhinitis": "एलर्जिक राइनाइटिस",
    "Sneezing": "छींकना",
    "Runny nose": "बहती नाक",
    "Itchy/watery eyes": "खुजली/पानी भरी आंखें",
    "1 tablet (10mg) once daily.": "दिन में एक बार 1 गोली (10 मिग्रा)।",
    "Half dose for children 6–12 years, under medical advice.": "6-12 वर्ष के बच्चों के लिए आधी खुराक।",
    "Take as soon as remembered; skip if close to next dose.": "याद आने पर लें; यदि अगली खुराक का समय हो तो छोड़ दें।",
    "May cause drowsiness or restlessness — consult a doctor.": "सुस्ती हो सकती है — डॉक्टर से सलाह लें।",
    "Drowsiness": "सुस्ती/नींद आना",
    "Dry mouth": "सूखा मुंह",
    "Blurred vision": "धुंधली दृष्टि",
    "Rapid heartbeat": "तेज दिल की धड़कन",
    "Use only if advised by a doctor.": "केवल डॉक्टर की सलाह पर उपयोग करें।",
    "Consult your doctor.": "अपने डॉक्टर से परामर्श करें।",
    "Dose adjustment may be needed.": "खुराक में बदलाव की आवश्यकता हो सकती है।",
    "Avoid — may increase drowsiness.": "बचें — सुस्ती बढ़ सकती है।",
    "May cause drowsiness — avoid driving until you know how it affects you.": "सुस्ती हो सकती है — ड्राइविंग से बचें।",
    "Sedatives": "शामक दवाएं",
    "Theophylline": "थियोफिलाइन",
    "Oral rehydration salts used to restore fluids and electrolytes lost due to dehydration, diarrhea, or vomiting.": "निर्जलीकरण और दस्त के कारण खोए हुए तरल पदार्थों को बहाल करने वाला ओआरएस घोल।",
    "Store the prepared solution in a fridge and discard after 24 hours.": "तैयार घोल को फ्रिज में रखें और 24 घंटे बाद फेंक दें।",
    "Dehydration": "निर्जलीकरण",
    "Diarrhea": "दस्त",
    "Heat exhaustion": "गर्मी की थकान",
    "Vomiting": "उल्टी",
    "1 sachet dissolved in 1 liter of clean water; sip throughout the day.": "1 पाउच 1 लीटर साफ पानी में घोलकर दिन भर पीएं।",
    "As advised by a pediatrician based on dehydration severity.": "निर्जलीकरण की गंभीरता के आधार पर बाल रोग विशेषज्ञ की सलाह के अनुसार।",
    "Not applicable — take as needed.": "आवश्यकतानुसार लें।",
    "Excess intake may cause electrolyte imbalance — consult a doctor if unwell.": "अत्यधिक सेवन से इलेक्ट्रोलाइट असंतुलन हो सकता है।",
    "Mild bloating": "हल्का पेट फूलना",
    "Vomiting if taken too concentrated": "गाढ़ा घोल लेने पर उल्टी हो सकती है",
    "Safe to use.": "उपयोग के लिए सुरक्षित।",
    "Use with medical guidance.": "चिकित्सीय मार्गदर्शन के साथ उपयोग करें।",
    "No known interaction.": "कोई ज्ञात प्रभाव नहीं।",
    "No impairment.": "कोई प्रभाव नहीं।",
    "A chewable Vitamin C supplement that supports immunity and skin health.": "रोग प्रतिरोधक क्षमता बढ़ाने वाला विटामिन सी सप्लीमेंट।",
    "Store in a cool, dry place.": "ठंडी, सूखी जगह पर स्टोर करें।",
    "Vitamin C deficiency": "विटामिन सी की कमी",
    "Immunity support": "प्रतिरोधक क्षमता सहायता",
    "Antioxidant supplementation": "एंटीऑक्सीडेंट पूरक",
    "1 tablet daily, or as directed by a physician.": "रोजाना 1 गोली, या चिकित्सक के निर्देशानुसार।",
    "As advised by a pediatrician.": "बाल रोग विशेषज्ञ की सलाह के अनुसार।",
    "High doses may cause stomach upset or diarrhea.": "उच्च खुराक से पेट खराब हो सकता है।",
    "Mild stomach upset": "हल्का पेट खराब होना",
    "Kidney stones with prolonged high doses": "लंबे समय तक उच्च खुराक से गुर्दे की पथरी हो सकती है",
    "Safe within recommended doses.": "अनुशंसित खुराक में सुरक्षित।",
    "Use with caution — consult your doctor.": "सावधानी से उपयोग करें — डॉक्टर से परामर्श लें।",
    "Iron supplements (increases absorption)": "आयरन सप्लीमेंट्स",
    "An antacid gel that relieves acidity, heartburn, and gas.": "एसिडिटी, सीने में जलन और गैस से राहत देने वाला एंटासिड जेल।",
    "Store below 30°C. Shake well before use.": "30°C से नीचे स्टोर करें। उपयोग से पहले अच्छी तरह हिलाएं।",
    "Acidity": "एसिडिटी",
    "Heartburn": "सीने में जलन",
    "Gas/bloating": "गैस/पेट फूलना",
    "Indigestion": "अपच",
    "1–2 teaspoons (5–10ml) after meals and at bedtime.": "भोजन के बाद और सोते समय 1-2 चम्मच (5-10 मि.ली.)।",
    "Not recommended without medical advice.": "बिना डॉक्टरी सलाह के अनुशंसित नहीं।",
    "Take when needed; not a scheduled medication.": "आवश्यकता पड़ने पर लें।",
    "Excess use may cause diarrhea or electrolyte imbalance.": "अत्यधिक उपयोग से दस्त हो सकते हैं।",
    "Mild diarrhea": "हल्का दस्त",
    "Constipation": "कब्ज",
    "Generally considered safe — consult your doctor.": "सामान्यतः सुरक्षित — अपने डॉक्टर से सलाह लें।",
    "No major interaction.": "कोई बड़ा प्रभाव नहीं।",
    "Tetracycline antibiotics": "टेट्रासाइक्लिन एंटीबायोटिक्स",
    "Iron supplements": "आयरन सप्लीमेंट्स",
    "Not typical.": "कोई प्रभाव नहीं।",
    "Take after meals.": "भोजन के बाद लें।",
    "An antacid suspension for fast relief from acidity and heartburn.": "एसिडिटी से तुरंत राहत के लिए एंटासिड सिरप।",
    "1–2 teaspoons after meals and at bedtime.": "भोजन के बाद और सोते समय 1-2 चम्मच।",
    "Take when needed.": "आवश्यकतानुसार लें।",
    "Excess use may cause bowel disturbances.": "अत्यधिक उपयोग से पेट खराब हो सकता है।",
    "Mild constipation": "हल्की कब्ज",
    "A penicillin-based antibiotic used to treat a wide range of bacterial infections. Requires a valid prescription.": "बैक्टीरियल संक्रमण के इलाज के लिए एंटीबायोटिक दवा। पर्चा आवश्यक है।",
    "Store below 25°C in a dry place.": "25°C से नीचे सूखी जगह पर रखें।",
    "Bacterial infections": "बैक्टीरियल संक्रमण",
    "Respiratory tract infections": "श्वसन पथ के संक्रमण",
    "Urinary tract infections": "मूत्र मार्ग के संक्रमण",
    "As prescribed by your doctor — typically 500mg every 8 hours.": "डॉक्टर के निर्देशानुसार — आमतौर पर हर 8 घंटे में 500 मिग्रा।",
    "Dose calculated by body weight — prescription only.": "शरीर के वजन के आधार पर — केवल पर्चे पर।",
    "Take as soon as remembered; do not double dose.": "याद आने पर लें; दोहरी खुराक न लें।",
    "Seek medical attention immediately.": "तुरंत चिकित्सा सहायता लें।",
    "Use only if prescribed by your doctor.": "डॉक्टर द्वारा लिखे जाने पर ही उपयोग करें।",
    "Dose adjustment may be required.": "खुराक समायोजन की आवश्यकता हो सकती है।",
    "Generally avoid during the course.": "कोर्स के दौरान शराब से बचें।",
    "Oral contraceptives": "गर्भनिरोधक गोलियां",
    "Methotrexate": "मेथोट्रेक्सेट",
    "An oral medication used to control blood sugar levels in type 2 diabetes. Requires a valid prescription.": "टाइप 2 मधुमेह में ब्लड शुगर नियंत्रित करने की दवा। पर्चा आवश्यक।",
    "Store below 30°C in a dry place.": "30°C से नीचे सूखी जगह पर रखें।",
    "Type 2 diabetes management": "टाइप 2 मधुमेह प्रबंधन",
    "Blood sugar control": "ब्लड शुगर नियंत्रण",
    "As prescribed — typically 500mg 1–2 times daily with meals.": "निर्देशानुसार — भोजन के साथ दिन में 1-2 बार 500 मिग्रा।",
    "Prescription only, under specialist supervision.": "केवल विशेषज्ञ की देखरेख में।",
    "Take with the next meal; do not double dose.": "अगले भोजन के साथ लें; दोहरी खुराक न लें।",
    "Can cause dangerously low blood sugar — seek emergency help.": "ब्लड शुगर बहुत कम कर सकता है — आपातकालीन सहायता लें।",
    "Lactic acidosis (rare but serious)": "लैक्टिक एसिडोसिस (दुर्लभ लेकिन गंभीर)",
    "Use only under specialist supervision.": "केवल विशेषज्ञ की देखरेख में उपयोग करें।",
    "Contraindicated in severe kidney disease.": "गंभीर गुर्दे की बीमारी में वर्जित।",
    "Avoid — increases risk of lactic acidosis.": "बचें — लैक्टिक एसिडोसिस का खतरा बढ़ता है।",
    "May cause low blood sugar — monitor before driving.": "ब्लड शुगर कम हो सकता है — ड्राइविंग से पहले जांचें।",
    "Contrast dye (imaging)": "कंट्रास्ट डाई",
    "Diuretics": "मूत्रवर्धक",
    "Take with meals to reduce stomach upset.": "पेट खराब होने से बचाने के लिए भोजन के साथ लें।",
    "Excess alcohol": "अत्यधिक शराब",
    "An antiseptic ointment used to prevent infection in minor cuts, wounds, and burns.": "कटे और घाव में संक्रमण रोकने वाली एंटीसेप्टिक क्रीम।",
    "Store below 30°C. Keep the tube tightly closed.": "30°C से नीचे रखें। ट्यूब को कसकर बंद रखें।",
    "Minor cuts": "छोटे कट",
    "Wounds": "घाव",
    "Burns": "जलन",
    "Skin infections": "त्वचा संक्रमण",
    "Apply a thin layer to the affected area 2–3 times daily.": "प्रभावित क्षेत्र पर दिन में 2-3 बार पतली परत लगाएं।",
    "Apply sparingly; consult a doctor for infants.": "कम मात्रा में लगाएं; शिशुओं के लिए डॉक्टर से सलाह लें।",
    "Not applicable — apply as needed.": "आवश्यकतानुसार लगाएं।",
    "Not applicable for topical use; avoid ingestion.": "केवल बाहरी उपयोग के लिए।",
    "Mild skin irritation": "हल्की त्वचा की जलन",
    "Allergic contact dermatitis": "एलर्जिक कांटेक्ट डर्मेटाइटिस",
    "Use with caution — consult your doctor for large areas.": "बड़े घावों के लिए डॉक्टर से सलाह लें।",
    "Avoid applying near the breast area.": "स्तन क्षेत्र के पास लगाने से बचें।",
    "Avoid prolonged use on large wounds.": "बड़े घावों पर लंबे समय तक उपयोग से बचें।",
    "Generally safe for topical use.": "बाहरी उपयोग के लिए सुरक्षित।",
    "No interaction.": "कोई प्रभाव नहीं।",
    "Other topical antiseptics (avoid combining)": "अन्य बाहरी एंटीसेप्टिक्स से मिलाएं नहीं",
    "Not applicable.": "लागू नहीं।"
  },

  te: {
    "Paracetamol is a widely used pain reliever and fever reducer, suitable for mild to moderate pain and fever in adults and children.": "పారాసిటమాల్ జ్వరం మరియు నొప్పుల నివారణకు ఉపయోగించే సురక్షితమైన ఔషధం.",
    "Store below 30°C in a dry place, away from direct sunlight.": "ఎండ తగలకుండా 30°C కంటే తక్కువ ఉష్ణోగ్రత వద్ద ఎండిన ప్రదేశంలో నిల్వ చేయండి.",
    "Fever": "జ్వరం",
    "Headache": "తలనొప్పి",
    "Body ache": "ఒళ్ళు నొప్పులు",
    "Toothache": "పంటి నొప్పి",
    "Cold-related pain": "జలుబు సంబంధిత నొప్పి",
    "1–2 tablets (500–1000mg) every 4–6 hours. Do not exceed 4g/day.": "ప్రతి 4-6 గంటలకు 1-2 టాబ్లెట్లు (500-1000 మి.గ్రా). రోజుకు 4 గ్రాములు మించకూడదు.",
    "As advised by a pediatrician based on body weight.": "పిల్లల వైద్యుని సలహా మేరకు శరీర బరువు ఆధారంగా ఇవ్వండి.",
    "Take as soon as you remember. Skip if it's almost time for the next dose.": "గుర్తుకు వచ్చిన వెంటనే తీసుకోండి. తదుపరి మోతాదు సమయం అయితే వదిలేయండి.",
    "Seek emergency medical attention immediately — overdose can cause liver damage.": "వెంటనే అత్యవసర వైద్య సహాయం పొందండి — పరిమితికి మించితే కాలేయం దెబ్బతింటుంది.",
    "Nausea": "వాంతులు వచ్చే భావన",
    "Stomach upset": "కడుపు కలత",
    "Skin rash": "చర్మంపై దద్దుర్లు",
    "Allergic reaction": "అలెర్జిక్ ప్రతిచర్య",
    "Liver damage (with overdose)": "కాలేయ నష్టం (అధిక మోతాదుతో)",
    "Considered safe at recommended doses — consult your doctor.": "సూచించిన మోతాదులో సురక్షితం — వైద్యుడిని సంప్రదించండి.",
    "Generally considered safe.": "సాధారణంగా సురక్షితమైనదిగా పరిగణించబడుతుంది.",
    "Use with caution; consult your doctor.": "జాగ్రత్తగా ఉపయోగించండి; వైద్యుడిని సంప్రదించండి.",
    "Avoid or use only under medical supervision.": "వైద్య పర్యవేక్షణలో మాత్రమే ఉపయోగించండి.",
    "Avoid regular alcohol use — increases liver damage risk.": "క్రమం తప్పకుండా మద్యం సేవించడం నివారించండి — కాలేయ నష్టం ప్రమాదాన్ని పెంచుతుంది.",
    "Does not typically impair driving ability.": "సాధారణంగా డ్రైవింగ్ సామర్థ్యాన్ని ప్రభావితం చేయదు.",
    "Warfarin": "వార్ఫరిన్",
    "Alcohol": "ఆల్కహాల్",
    "Other paracetamol-containing products": "ఇతర పారాసిటమాల్ కలిగిన ఉత్పత్తులు",
    "Can be taken before or after food.": "ఆహారానికి ముందు లేదా తరువాత తీసుకోవచ్చు.",
    "Preferred if you have a sensitive stomach.": "కడుపు అసౌకర్యం ఉంటే ఆహారం తర్వాత శ్రేయస్కరం.",
    "A higher-strength paracetamol formulation commonly used for fever and moderate pain relief.": "జ్వరం మరియు తీవ్రమైన నొప్పుల నివారణకు ఉపయోగించే పారాసిటమాల్ ఔషధం.",
    "Store below 30°C, away from moisture and sunlight.": "తేమ మరియు సూర్యరశ్మికి దూరంగా 30°C కంటే తక్కువ ఉష్ణోగ్రత వద్ద నిల్వ చేయండి.",
    "1 tablet (650mg) every 6–8 hours. Do not exceed 3 tablets/day.": "ప్రతి 6-8 గంటలకు 1 టాబ్లెట్ (650 మి.గ్రా). రోజుకు 3 టాబ్లెట్లు మించకూడదు.",
    "Not recommended below 12 years without medical advice.": "వైద్యుని సలహా లేకుండా 12 సంవత్సరాల కంటే తక్కువ వయస్సు ఉన్నవారికి సిఫార్సు చేయబడదు.",
    "Take as soon as you remember; skip if close to the next dose.": "గుర్తుకు వచ్చిన వెంటనే తీసుకోండి; తదుపరి మోతాదు దగ్గరగా ఉంటే వదిలేయండి.",
    "Seek emergency medical attention immediately.": "వెంటనే అత్యవసర వైద్య సహాయం పొందండి.",
    "Consult your doctor before use.": "ఉపయోగించే ముందు మీ వైద్యుడిని సంప్రదించండి.",
    "Use with caution.": "జాగ్రత్తగా ఉపయోగించండి.",
    "Avoid regular alcohol use.": "క్రమం తప్పకుండా మద్యం సేవించడం నివారించండి.",
    "Either.": "ఆహారానికి ముందు లేదా తరువాత.",
    "Preferred for sensitive stomachs.": "కడుపు అసౌకర్యం ఉన్నవారికి ఆహారం తర్వాత మంచిది.",
    "A trusted paracetamol brand for fever and pain relief, available in tablet and syrup forms.": "జ్వరం మరియు నొప్పి నివారణకు నమ్మకమైన పారాసిటమాల్ బ్రాండ్.",
    "Store in a cool, dry place below 30°C.": "30°C కంటే తక్కువ చల్లని, పొడి ప్రదేశంలో నిల్వ చేయండి.",
    "Mild pain": "లేలిత నొప్పి",
    "1–2 tablets every 4–6 hours. Max 4g/day.": "ప్రతి 4-6 గంటలకు 1-2 టాబ్లెట్లు. గరిష్టంగా 4 గ్రాములు/రోజు.",
    "Pediatric syrup dosage as per body weight — consult a doctor.": "శరీర బరువు ఆధారంగా పిల్లల సిరప్ మోతాదు — వైద్యుడిని సంప్రదించండి.",
    "Take as soon as remembered.": "గుర్తుకు వచ్చిన వెంటనే తీసుకోండి.",
    "Rash": "దద్దుర్లు",
    "Liver damage (overdose)": "కాలేయ నష్టం (అధిక మోతాదు)",
    "Considered safe at recommended doses.": "సూచించిన మోతాదులో సురక్షితం.",
    "Generally safe.": "సాధారణంగా సురక్షితం.",
    "Avoid without medical supervision.": "వైద్య పర్యవేక్షణ లేకుండా నివారించండి.",
    "Avoid regular use.": "క్రమబద్ధమైన వాడకం నివారించండి.",
    "No typical impairment.": "ప్రభావం లేదు.",
    "Preferred.": "సిఫార్సు చేయబడింది.",
    "An antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes.": "అలెర్జీ లక్షణాల నివారణకు ఉపయోగించే యాంటీహిస్టమైన్ ఔషధం.",
    "Store below 25°C, protect from light.": "వెలుతురు పడకుండా 25°C కంటే తక్కువ వద్ద నిల్వ చేయండి.",
    "Allergic rhinitis": "అలెర్జిక్ రైనైటిస్",
    "Sneezing": "తుమ్ములు",
    "Runny nose": "ముక్కు కారడం",
    "Itchy/watery eyes": "కళ్ళు దురద/నీరు కారడం",
    "1 tablet (10mg) once daily.": "రోజుకు ఒకసారి 1 టాబ్లెట్ (10 మి.గ్రా).",
    "Half dose for children 6–12 years, under medical advice.": "6-12 సంవత్సరాల పిల్లలకు సగం మోతాదు.",
    "Take as soon as remembered; skip if close to next dose.": "గుర్తుకు వచ్చిన వెంటనే తీసుకోండి; తదుపరి మోతాదు దగ్గరగా ఉంటే వదిలేయండి.",
    "May cause drowsiness or restlessness — consult a doctor.": "మత్తు కలిగించవచ్చు — వైద్యుడిని సంప్రదించండి.",
    "Drowsiness": "మత్తు",
    "Dry mouth": "నోరు ఎండిపోవడం",
    "Blurred vision": "మసక బారిన చూపు",
    "Rapid heartbeat": "వేగవంతమైన గుండె స్పందన",
    "Use only if advised by a doctor.": "వైద్యుని సలహా మేరకు మాత్రమే ఉపయోగించండి.",
    "Consult your doctor.": "మీ వైద్యుడిని సంప్రదించండి.",
    "Dose adjustment may be needed.": "మోతాదు మార్పు అవసరం కావచ్చు.",
    "Avoid — may increase drowsiness.": "నివారించండి — మత్తు పెరుగుతుంది.",
    "May cause drowsiness — avoid driving until you know how it affects you.": "మత్తు కలిగించవచ్చు — డ్రైవింగ్ నివారించండి.",
    "Sedatives": "నిద్ర మాత్రలు",
    "Theophylline": "థియోఫిలైన్",
    "Oral rehydration salts used to restore fluids and electrolytes lost due to dehydration, diarrhea, or vomiting.": "డీహైడ్రేషన్ వల్ల కోల్పోయిన నీటిని తిరిగి పొందేందుకు ఉపయోగించే ఓఆర్‌ఎస్ ద్రావణం.",
    "Store the prepared solution in a fridge and discard after 24 hours.": "తయారుచేసిన ద్రావణాన్ని ఫ్రిజ్‌లో ఉంచి 24 గంటల తర్వాత పారవేయండి.",
    "Dehydration": "డీహైడ్రేషన్ (నీరిజప్పు)",
    "Diarrhea": "విరేచనాలు",
    "Heat exhaustion": "ఎండ దెబ్బ సూర్యాఘాతం",
    "Vomiting": "వాంతులు",
    "1 sachet dissolved in 1 liter of clean water; sip throughout the day.": "1 ప్యాకెట్‌ను 1 లీటరు పరిశుభ్రమైన నీటిలో కలిపి రోజు మొత్తం తాగండి.",
    "As advised by a pediatrician based on dehydration severity.": "డీహైడ్రేషన్ తీవ్రతను బట్టి పిల్లల వైద్యుని సలహా మేరకు ఇవ్వండి.",
    "Not applicable — take as needed.": "అవసరమైనప్పుడు తీసుకోండి.",
    "Excess intake may cause electrolyte imbalance — consult a doctor if unwell.": "అధికంగా తీసుకోవడం వల్ల ఎలక్ట్రోలైట్ అసమతుల్యత ఏర్పడవచ్చు.",
    "Mild bloating": "లేలిత కడుపు ఉబ్బరం",
    "Vomiting if taken too concentrated": "చిక్కగా తీసుకుంటే వాంతులు రావచ్చు",
    "Safe to use.": "వాడటానికి సురక్షితం.",
    "Use with medical guidance.": "వైద్య మార్గదర్శకత్వంలో ఉపయోగించండి.",
    "No known interaction.": "ఎలాంటి దుష్ప్రభావాలు లేవు.",
    "No impairment.": "ప్రభావం లేదు.",
    "A chewable Vitamin C supplement that supports immunity and skin health.": "రోగనిరోధక శక్తిని పెంచే విటమిన్ సి ఔషధం.",
    "Store in a cool, dry place.": "చల్లని, పొడి ప్రదేశంలో నిల్వ చేయండి.",
    "Vitamin C deficiency": "విటమిన్ సి లోపం",
    "Immunity support": "రోగనిరోధక మద్దతు",
    "Antioxidant supplementation": "యాంటీఆక్సిడెంట్ సప్లిమెంట్",
    "1 tablet daily, or as directed by a physician.": "రోజుకు 1 టాబ్లెట్, లేదా వైద్యుని సలహా మేరకు.",
    "As advised by a pediatrician.": "పిల్లల వైద్యుని సలహా ప్రకారం.",
    "High doses may cause stomach upset or diarrhea.": "అధిక మోతాదు వల్ల కడుపు కలత రావచ్చు.",
    "Mild stomach upset": "లేలిత కడుపు కలత",
    "Kidney stones with prolonged high doses": "దీర్ఘకాలం అధిక మోతాదు తీసుకుంటే మూత్రపిండాల్లో రాళ్ళు రావచ్చు",
    "Safe within recommended doses.": "సూచించిన మోతాదులో సురక్షితం.",
    "Use with caution — consult your doctor.": "జాగ్రత్తగా ఉపయోగించండి — వైద్యుడిని సంప్రదించండి.",
    "Iron supplements (increases absorption)": "ఐరన్ సప్లిమెంట్లు",
    "An antacid gel that relieves acidity, heartburn, and gas.": "యాసిడిటీ మరియు గ్యాస్ నుండి ఉపశమనం కలిగించే యాంటాసిడ్ జెల్.",
    "Store below 30°C. Shake well before use.": "30°C కంటే తక్కువ వద్ద నిల్వ చేయండి. ఉపయోగించే ముందు బాగా కలపండి.",
    "Acidity": "యాసిడిటీ",
    "Heartburn": "ఛాతీలో మంట",
    "Gas/bloating": "గ్యాస్/కడుపు ఉబ్బరం",
    "Indigestion": "అజీర్ణం",
    "1–2 teaspoons (5–10ml) after meals and at bedtime.": "భోజనం తర్వాత మరియు నిద్రపోయే ముందు 1-2 టీస్పూన్లు (5-10 మి.లీ).",
    "Not recommended without medical advice.": "వైద్యుని సలహా లేకుండా సిఫార్సు చేయబడదు.",
    "Take when needed; not a scheduled medication.": "అవసరమైనప్పుడు తీసుకోండి.",
    "Excess use may cause diarrhea or electrolyte imbalance.": "అధిక వాడకం వల్ల విరేచనాలు రావచ్చు.",
    "Mild diarrhea": "లేలిత విరేచనాలు",
    "Constipation": "మలబద్ధకం",
    "Generally considered safe — consult your doctor.": "సాధారణంగా సురక్షితం — వైద్యుడిని సంప్రదించండి.",
    "No major interaction.": "ప్రధాన దుష్ప్రభావాలు లేవు.",
    "Tetracycline antibiotics": "టెట్రాసైక్లిన్ యాంటీబయాటిక్స్",
    "Iron supplements": "ఐరన్ సప్లిమెంట్లు",
    "Not typical.": "ప్రభావం లేదు.",
    "Take after meals.": "భోజనం తర్వాత తీసుకోండి.",
    "An antacid suspension for fast relief from acidity and heartburn.": "యాసిడిటీ నుండి తక్షణ ఉపశమనం ఇచ్చే యాంటాసిడ్ లిక్విడ్.",
    "1–2 teaspoons after meals and at bedtime.": "భోజనం తర్వాత మరియు నిద్రపోయే ముందు 1-2 టీస్పూన్లు.",
    "Take when needed.": "అవసరమైనప్పుడు తీసుకోండి.",
    "Excess use may cause bowel disturbances.": "అధిక వాడకం వల్ల జీర్ణ సమస్యలు రావచ్చు.",
    "Mild constipation": "లేలిత మలబద్ధకం",
    "A penicillin-based antibiotic used to treat a wide range of bacterial infections. Requires a valid prescription.": "బాక్టీరియల్ ఇన్ఫెక్షన్ల చికిత్సకు ఉపయోగించే యాంటీబయాటిక్. ప్రిస్క్రిప్షన్ అవసరం.",
    "Store below 25°C in a dry place.": "25°C కంటే తక్కువ ఉష్ణోగ్రత వద్ద పొడి ప్రదేశంలో నిల్వ చేయండి.",
    "Bacterial infections": "బాక్టీరియల్ ఇన్ఫెక్షన్లు",
    "Respiratory tract infections": "శ్వాసకోశ ఇన్ఫెక్షన్లు",
    "Urinary tract infections": "మూత్రనాళ ఇన్ఫెక్షన్లు",
    "As prescribed by your doctor — typically 500mg every 8 hours.": "వైద్యుని సలహా ప్రకారం — ప్రతి 8 గంటలకు 500 మి.గ్రా.",
    "Dose calculated by body weight — prescription only.": "శరీర బరువు ఆధారంగా — ప్రిస్క్రిప్షన్ మాత్రమే.",
    "Take as soon as remembered; do not double dose.": "గుర్తుకు వచ్చిన వెంటనే తీసుకోండి; రెట్టింపు మోతాదు తీసుకోకండి.",
    "Seek medical attention immediately.": "వెంటనే వైద్య సహాయం పొందండి.",
    "Use only if prescribed by your doctor.": "వైద్యుడు సూచిస్తేనే ఉపయోగించండి.",
    "Dose adjustment may be required.": "మోతాదు మార్పు అవసరం కావచ్చు.",
    "Generally avoid during the course.": "కోర్సు సమయంలో మద్యం నివారించండి.",
    "Oral contraceptives": "గర్భనిరోధక మాత్రలు",
    "Methotrexate": "మెథోట్రెక్సేట్",
    "An oral medication used to control blood sugar levels in type 2 diabetes. Requires a valid prescription.": "టైప్ 2 మధుమేహంలో బ్లడ్ షుగర్ నియంత్రించే ఔషధం. ప్రిస్క్రిప్షన్ అవసరం.",
    "Store below 30°C in a dry place.": "30°C కంటే తక్కువ పొడి ప్రదేశంలో నిల్వ చేయండి.",
    "Type 2 diabetes management": "టైప్ 2 మధుమేహ నిర్వహణ",
    "Blood sugar control": "బ్లడ్ షుగర్ నియంత్రణ",
    "As prescribed — typically 500mg 1–2 times daily with meals.": "వైద్యుని సలహా ప్రకారం — ఆహారంతో పాటు రోజుకు 1-2 సార్లు 500 మి.గ్రా.",
    "Prescription only, under specialist supervision.": "నిపుణుల పర్యవేక్షణలో మాత్రమే.",
    "Take with the next meal; do not double dose.": "తదుపరి ఆహారంతో తీసుకోండి; రెట్టింపు మోతాదు తీసుకోకండి.",
    "Can cause dangerously low blood sugar — seek emergency help.": "షుగర్ చాలా తగ్గించవచ్చు — అత్యవసర సహాయం పొందండి.",
    "Lactic acidosis (rare but serious)": "లాక్టిక్ అసిడోసిస్ (అరుదైనది కానీ తీవ్రమైనది)",
    "Use only under specialist supervision.": "నిపుణుల పర్యవేక్షణలో మాత్రమే ఉపయోగించండి.",
    "Contraindicated in severe kidney disease.": "తీవ్రమైన మూత్రపిండాల వ్యాధిలో వాడకూడదు.",
    "Avoid — increases risk of lactic acidosis.": "నివారించండి — ప్రమాదం పెరుగుతుంది.",
    "May cause low blood sugar — monitor before driving.": "షుగర్ తగ్గే అవకాశం ఉంది — డ్రైవింగ్ చేసేముందు గమనించండి.",
    "Contrast dye (imaging)": "కాంట్రాస్ట్ డై",
    "Diuretics": "డైయూరెటిక్స్",
    "Take with meals to reduce stomach upset.": "కడుపు కలత తగ్గించడానికి ఆహారంతో తీసుకోండి.",
    "Excess alcohol": "అధిక ఆల్కహాల్",
    "An antiseptic ointment used to prevent infection in minor cuts, wounds, and burns.": "గాయాలు మరియు బొబ్బల్లో ఇన్ఫెక్షన్ రాకుండా నిరోధించే యాంటీసెప్టిక్ క్రీమ్.",
    "Store below 30°C. Keep the tube tightly closed.": "30°C కంటే తక్కువ వద్ద నిల్వ చేయండి. ట్యూబ్‌ను గట్టిగా మూసి ఉంచండి.",
    "Minor cuts": "చిన్న గాయాలు",
    "Wounds": "గాయాలు",
    "Burns": "బొబ్బలు/కాల్చిన గాయాలు",
    "Skin infections": "చర్మ ఇన్ఫెక్షన్లు",
    "Apply a thin layer to the affected area 2–3 times daily.": "బాధిత ప్రాంతంలో రోజుకు 2-3 సార్లు సన్నగా రాయండి.",
    "Apply sparingly; consult a doctor for infants.": "తక్కువగా రాయండి; శిశువుల కోసం వైద్యుడిని సంప్రదించండి.",
    "Not applicable — apply as needed.": "అవసరమైనప్పుడు రాయండి.",
    "Not applicable for topical use; avoid ingestion.": "బాహ్య ఉపయోగానికి మాత్రమే.",
    "Mild skin irritation": "లేలిత చర్మపు మంట",
    "Allergic contact dermatitis": "అలెర్జిక్ కాంటాక్ట్ డెర్మటైటిస్",
    "Use with caution — consult your doctor for large areas.": "పెద్ద గాయాలకు వైద్యుడిని సంప్రదించండి.",
    "Avoid applying near the breast area.": "ఛాతీ భాగం దగ్గర రాయడం నివారించండి.",
    "Avoid prolonged use on large wounds.": "పెద్ద గాయాలపై దీర్ఘకాలిక వాడకం నివారించండి.",
    "Generally safe for topical use.": "బాహ్య ఉపయోగానికి సురక్షితం.",
    "No interaction.": "ప్రభావం లేదు.",
    "Other topical antiseptics (avoid combining)": "ఇతర బాహ్య యాంటీసెప్టిక్‌లతో కలపవద్దు",
    "Not applicable.": "వర్తించదు."
  },

  ml: {
    "Paracetamol is a widely used pain reliever and fever reducer, suitable for mild to moderate pain and fever in adults and children.": "പനിക്കും വേദനയ്ക്കും ആശ്വാസം നൽകുന്ന സുരക്ഷിതമായ മരുന്നാണ് പാരാസിറ്റമോൾ.",
    "Store below 30°C in a dry place, away from direct sunlight.": "നേരിട്ടുള്ള സൂര്യപ്രകാശത്തിൽ നിന്ന് മാറി 30°C ന് താഴെ ഉണങ്ങിയ സ്ഥലത്ത് സൂക്ഷിക്കുക.",
    "Fever": "പനി",
    "Headache": "തലവേദന",
    "Body ache": "ശരീരവേദന",
    "Toothache": "പല്ലുവേദന",
    "Cold-related pain": "ജലദോഷം മൂലമുള്ള വേദന",
    "1–2 tablets (500–1000mg) every 4–6 hours. Do not exceed 4g/day.": "4-6 മണിക്കൂർ ഇടവിട്ട് 1-2 ഗുളികകൾ (500-1000 മില്ലിഗ്രാം). പ്രതിദിനം 4 ഗ്രാമിൽ കൂടരുത്.",
    "As advised by a pediatrician based on body weight.": "ശരീരഭാരം അനുസരിച്ച് കുട്ടികളുടെ ഡോക്ടറുടെ നിർദ്ദേശപ്രകാരം നൽകുക.",
    "Take as soon as you remember. Skip if it's almost time for the next dose.": "ഓർമ്മ വരുമ്പോൾ കഴിക്കുക. അടുത്ത ഡോസിന് സമയമായെങ്കിൽ ഒഴിവാക്കുക.",
    "Seek emergency medical attention immediately — overdose can cause liver damage.": "ഉടൻ തന്നെ വൈദ്യസഹായം തേടുക — അമിത അളവ് കരളിനെ ബാധിക്കും.",
    "Nausea": "ഛർദ്ദി തോനൽ",
    "Stomach upset": "വയറുവേദന/അസ്വസ്ഥത",
    "Skin rash": "ചർമ്മത്തിൽ തടുപ്പ്",
    "Allergic reaction": "അലർജി പ്രകടനങ്ങൾ",
    "Liver damage (with overdose)": "കരൾ തരാർ (അമിത അളവിൽ കഴിച്ചാൽ)",
    "Considered safe at recommended doses — consult your doctor.": "നിർദ്ദേശിച്ച അളവിൽ സുരക്ഷിതമാണ് — ഡോക്ടറെ കാണുക.",
    "Generally considered safe.": "പൊതുവെ സുരക്ഷിതമായി കരുതപ്പെടുന്നു.",
    "Use with caution; consult your doctor.": "ശ്രദ്ധയോടെ ഉപയോഗിക്കുക; ഡോക്ടറെ കാണുക.",
    "Avoid or use only under medical supervision.": "ഒഴിവാക്കുക അല്ലെങ്കിൽ ഡോക്ടറുടെ മേൽനോട്ടത്തിൽ മാത്രം ഉപയോഗിക്കുക.",
    "Avoid regular alcohol use — increases liver damage risk.": "മദ്യപാനം ഒഴിവാക്കുക — കരൾ തരാർ സാധ്യത വർദ്ധിപ്പിക്കുന്നു.",
    "Does not typically impair driving ability.": "ഡ്രൈവിംഗിനെ ബാധിക്കാറില്ല.",
    "Warfarin": "വാർഫറിൻ",
    "Alcohol": "മദ്യം",
    "Other paracetamol-containing products": "പാരാസിറ്റമോൾ അടങ്ങിയ മറ്റ് മരുന്നുകൾ",
    "Can be taken before or after food.": "ഭക്ഷണത്തിന് മുമ്പോ ശേഷമോ കഴിക്കാം.",
    "Preferred if you have a sensitive stomach.": "വയറിന് അസ്വസ്ഥതയുണ്ടെങ്കിൽ ഭക്ഷണത്തിന് ശേഷം കഴിക്കുന്നതാണ് നല്ലത്.",
    "A higher-strength paracetamol formulation commonly used for fever and moderate pain relief.": "കഠിനമായ പനിക്കും വേദനയ്ക്കും ഉപയോഗിക്കുന്ന വീര്യം കൂടിയ പാരാസിറ്റമോൾ.",
    "Store below 30°C, away from moisture and sunlight.": "ഈർപ്പവും സൂര്യപ്രകാശവും തട്ടാതെ 30°C ന് താഴെ സൂക്ഷിക്കുക.",
    "1 tablet (650mg) every 6–8 hours. Do not exceed 3 tablets/day.": "6-8 മണിക്കൂർ ഇടവിട്ട് 1 ഗുളിക (650 മില്ലിഗ്രാം). ദിവസത്തിൽ 3 ഗുളികയിൽ കൂടരുത്.",
    "Not recommended below 12 years without medical advice.": "12 വയസ്സിന് താഴെയുള്ള കുട്ടികൾക്ക് ഡോക്ടറുടെ നിർദ്ദേശമില്ലാതെ നൽകരുത്.",
    "Take as soon as you remember; skip if close to the next dose.": "ഓർമ്മ വരുമ്പോൾ കഴിക്കുക; അടുത്ത ഡോസിന് സമയമായെങ്കിൽ ഒഴിവാക്കുക.",
    "Seek emergency medical attention immediately.": "ഉടൻ തന്നെ വൈദ്യസഹായം തേടുക.",
    "Consult your doctor before use.": "ഉപയോഗിക്കുന്നതിന് മുൻപ് ഡോക്ടറെ കാണുക.",
    "Use with caution.": "ശ്രദ്ധയോടെ ഉപയോഗിക്കുക.",
    "Avoid regular alcohol use.": "മദ്യപാനം ഒഴിവാക്കുക.",
    "Either.": "ഭക്ഷണത്തിന് മുമ്പോ ശേഷമോ.",
    "Preferred for sensitive stomachs.": "വയറിന് അസ്വസ്ഥതയുള്ളവർക്ക് ഭക്ഷണത്തിന് ശേഷം നല്ലതാണ്.",
    "A trusted paracetamol brand for fever and pain relief, available in tablet and syrup forms.": "പനിക്കും വേദനയ്ക്കും വിശ്വസിക്കാവുന്ന പാരാസിറ്റമോൾ ബ്രാൻഡ്.",
    "Store in a cool, dry place below 30°C.": "30°C ന് താഴെ തണുത്ത ഉണങ്ങിയ സ്ഥലത്ത് സൂക്ഷിക്കുക.",
    "Mild pain": "ലഘുവായ വേദന",
    "1–2 tablets every 4–6 hours. Max 4g/day.": "4-6 മണിക്കൂർ ഇടവിട്ട് 1-2 ഗുളികകൾ. പരമാവധി 4 ഗ്രാം/ദിവസം.",
    "Pediatric syrup dosage as per body weight — consult a doctor.": "ശരീരഭാരം അനുസരിച്ചുള്ള സിറപ്പ് ഡോസ് — ഡോക്ടറെ കാണുക.",
    "Take as soon as remembered.": "ഓർമ്മ വരുമ്പോൾ കഴിക്കുക.",
    "Rash": "തടുപ്പ്",
    "Liver damage (overdose)": "കരൾ തരാർ (അമിത അളവ്)",
    "Considered safe at recommended doses.": "നിർദ്ദേശിച്ച അളവിൽ സുരക്ഷിതമാണ്.",
    "Generally safe.": "പൊതുവെ സുരക്ഷിതം.",
    "Avoid without medical supervision.": "ഡോക്ടറുടെ നിർദ്ദേശമില്ലാതെ കഴിക്കരുത്.",
    "Avoid regular use.": "തുടർച്ചയായ ഉപയോഗം ഒഴിവാക്കുക.",
    "No typical impairment.": "ബാധിക്കാറില്ല.",
    "Preferred.": "നല്ലത്.",
    "An antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes.": "അലർജി, തുമ്മൽ, മൂക്കൊലിപ്പ് എന്നിവയ്ക്ക് ആശ്വാസം നൽകുന്ന ആന്റിഹിസ്റ്റാമൈൻ.",
    "Store below 25°C, protect from light.": "വെളിച്ചം തട്ടാതെ 25°C ന് താഴെ സൂക്ഷിക്കുക.",
    "Allergic rhinitis": "അലർജി മൂക്കൊലിപ്പ്",
    "Sneezing": "തുമ്മൽ",
    "Runny nose": "മൂക്കൊലിപ്പ്",
    "Itchy/watery eyes": "കണ്ണിലെ ചൊറിച്ചിൽ/വെള്ളം വരൽ",
    "1 tablet (10mg) once daily.": "ദിവസത്തിൽ ഒരിക്കൽ 1 ഗുളിക (10 മില്ലിഗ്രാം).",
    "Half dose for children 6–12 years, under medical advice.": "6-12 വയസ്സുള്ള കുട്ടികൾക്ക് പകുതി ഡോസ്.",
    "Take as soon as remembered; skip if close to next dose.": "ഓർമ്മ വരുമ്പോൾ കഴിക്കുക; അടുത്ത ഡോസിന് സമയമായെങ്കിൽ ഒഴിവാക്കുക.",
    "May cause drowsiness or restlessness — consult a doctor.": "ഉറക്കം തൂങ്ങൽ ഉണ്ടാക്കാം — ഡോക്ടറെ കാണുക.",
    "Drowsiness": "ഉറക്കം തൂങ്ങൽ",
    "Dry mouth": "വ്യാ വറളൽ",
    "Blurred vision": "മങ്ങിയ കാഴ്ച",
    "Rapid heartbeat": "വേഗത്തിലുള്ള നെഞ്ചിടിപ്പ്",
    "Use only if advised by a doctor.": "ഡോക്ടർ നിർദ്ദേശിച്ചാൽ മാത്രം കഴിക്കുക.",
    "Consult your doctor.": "ഡോക്ടറെ കാണുക.",
    "Dose adjustment may be needed.": "ഡോസിൽ മാറ്റം വരുത്തേണ്ടി വരാം.",
    "Avoid — may increase drowsiness.": "ഒഴിവാക്കുക — ഉറക്കം തൂങ്ങൽ കൂടും.",
    "May cause drowsiness — avoid driving until you know how it affects you.": "ഉറക്കം തൂങ്ങൽ ഉണ്ടാക്കാം — ഡ്രൈവിംഗ് ഒഴിവാക്കുക.",
    "Sedatives": "ഉറക്കമരുന്നുകൾ",
    "Theophylline": "തിയോഫിലിൻ",
    "Oral rehydration salts used to restore fluids and electrolytes lost due to dehydration, diarrhea, or vomiting.": "നിർജ്ജലീകരണവും വയറിളക്കവും മൂലം നഷ്ടപ്പെടുന്ന ലവണങ്ങൾ വീണ്ടെടുക്കാനുള്ള ഒആർഎസ് ലായനി.",
    "Store the prepared solution in a fridge and discard after 24 hours.": "തയ്യാറാക്കിയ ലായനി ഫ്രിഡ്ജിൽ വെച്ച് 24 മണിക്കൂറിന് ശേഷം കളയുക.",
    "Dehydration": "നിർജ്ജലീകരണം",
    "Diarrhea": "വയറിളക്കം",
    "Heat exhaustion": "ചൂട് മൂലമുള്ള തളർച്ച",
    "Vomiting": "ഛർദ്ദി",
    "1 sachet dissolved in 1 liter of clean water; sip throughout the day.": "1 പാക്കറ്റ് 1 ലിറ്റർ വെള്ളത്തിൽ കലക്കി ദിവസം മുഴുവൻ കുടിക്കുക.",
    "As advised by a pediatrician based on dehydration severity.": "കുട്ടികളുടെ ഡോക്ടറുടെ നിർദ്ദേശപ്രകാരം നൽകുക.",
    "Not applicable — take as needed.": "ആവശ്യാനുസരണം കഴിക്കുക.",
    "Excess intake may cause electrolyte imbalance — consult a doctor if unwell.": "അമിത അളവ് ലവണ അസന്തുലിതാവസ്ഥ ഉണ്ടാക്കാം.",
    "Mild bloating": "വയറ് വീർക്കൽ",
    "Vomiting if taken too concentrated": "കട്ടിയിൽ കുടിച്ചാൽ ഛർദ്ദിക്കാം",
    "Safe to use.": "ഉപയോഗിക്കാൻ സുരക്ഷിതം.",
    "Use with medical guidance.": "വൈദ്യനിർദ്ദേശത്തോടെ ഉപയോഗിക്കുക.",
    "No known interaction.": "പാർശ്വഫലങ്ങളില്ല.",
    "No impairment.": "ബാധിക്കില്ല.",
    "A chewable Vitamin C supplement that supports immunity and skin health.": "പ്രതിരോധശേഷിയും ചർമ്മ സംരക്ഷണവും നൽകുന്ന വിറ്റാമിൻ സി മരുന്ന്.",
    "Store in a cool, dry place.": "തണുത്ത ഉണങ്ങിയ സ്ഥലത്ത് സൂക്ഷിക്കുക.",
    "Vitamin C deficiency": "വിറ്റാമിൻ സി കുറവ്",
    "Immunity support": "പ്രതിരോധശേഷി വർദ്ധിപ്പിക്കൽ",
    "Antioxidant supplementation": "ആന്റിഓക്സിഡന്റ് പോഷണം",
    "1 tablet daily, or as directed by a physician.": "ദിവസവും 1 ഗുളിക, അല്ലെങ്കിൽ ഡോക്ടറുടെ നിർദ്ദേശപ്രകാരം.",
    "As advised by a pediatrician.": "കുട്ടികളുടെ ഡോക്ടറുടെ നിർദ്ദേശപ്രകാരം.",
    "High doses may cause stomach upset or diarrhea.": "കൂടുതൽ ഡോസ് വയറളക്കത്തിന് കാരണമാകാം.",
    "Mild stomach upset": "ലഘുവായ വയറുവേദന",
    "Kidney stones with prolonged high doses": "തുടർച്ചയായി ഉയർന്ന ഡോസ് കഴിച്ചാൽ വൃക്കയിൽ കല്ല് വരാം",
    "Safe within recommended doses.": "നിർദ്ദേശിച്ച അളവിൽ സുരക്ഷിതമാണ്.",
    "Use with caution — consult your doctor.": "ശ്രദ്ധയോടെ ഉപയോഗിക്കുക — ഡോക്ടറെ കാണുക.",
    "Iron supplements (increases absorption)": "അയൺ സപ്ലിമെന്റുകൾ",
    "An antacid gel that relieves acidity, heartburn, and gas.": "അസിഡിറ്റിയും നെഞ്ചെരിച്ചിലും മാറ്റുന്ന ആന്റാസിഡ് ജെൽ.",
    "Store below 30°C. Shake well before use.": "30°C ന് താഴെ സൂക്ഷിക്കുക. ഉപയോഗിക്കുന്നതിന് മുൻപ് നന്നായി കുലുക്കുക.",
    "Acidity": "അസിഡിറ്റി",
    "Heartburn": "നെഞ്ചെരിച്ചിൽ",
    "Gas/bloating": "ഗ്യാസ്/വയറ് വീർക്കൽ",
    "Indigestion": "അജീർണ്ണം",
    "1–2 teaspoons (5–10ml) after meals and at bedtime.": "ഭക്ഷണത്തിന് ശേഷവും കിടക്കുന്നതിന് മുൻപും 1-2 ടീസ്പൂൺ (5-10 മി.ലി).",
    "Not recommended without medical advice.": "ഡോക്ടറുടെ ഉപദേശമില്ലാതെ കഴിക്കരുത്.",
    "Take when needed; not a scheduled medication.": "ആവശ്യമുള്ളപ്പോൾ കഴിക്കുക.",
    "Excess use may cause diarrhea or electrolyte imbalance.": "അമിത ഉപയോഗം വയറിളക്കത്തിന് കാരണമാകാം.",
    "Mild diarrhea": "ലഘുവായ വയറിളക്കം",
    "Constipation": "മലബന്ധം",
    "Generally considered safe — consult your doctor.": "പൊതുവെ സുരക്ഷിതം — ഡോക്ടറെ കാണുക.",
    "No major interaction.": "പാർശ്വഫലങ്ങളില്ല.",
    "Tetracycline antibiotics": "ടെട്രാസൈക്ലിൻ ആന്റിബയോട്ടിക്കുകൾ",
    "Iron supplements": "അയൺ സപ്ലിമെന്റുകൾ",
    "Not typical.": "ബാധിക്കില്ല.",
    "Take after meals.": "ഭക്ഷണത്തിന് ശേഷം കഴിക്കുക.",
    "An antacid suspension for fast relief from acidity and heartburn.": "അസിഡിറ്റിക്ക് പെട്ടെന്ന് ആശ്വാസം തരുന്ന ആന്റാസിഡ് ലിക്വിഡ്.",
    "1–2 teaspoons after meals and at bedtime.": "ഭക്ഷണത്തിന് ശേഷവും കിടക്കുന്നതിന് മുൻപും 1-2 ടീസ്പൂൺ.",
    "Take when needed.": "ആവശ്യമുള്ളപ്പോൾ കഴിക്കുക.",
    "Excess use may cause bowel disturbances.": "അമിത ഉപയോഗം വയറിന് ബുദ്ധിമുട്ടുണ്ടാക്കാം.",
    "Mild constipation": "ലഘുവായ മലബന്ധം",
    "A penicillin-based antibiotic used to treat a wide range of bacterial infections. Requires a valid prescription.": "ബാക്ടീരിയൽ അണുബാധകൾക്ക് ചികിത്സിക്കുന്ന ആന്റിബയോട്ടിക് മരുന്ന്. കുറിപ്പടി വേണം.",
    "Store below 25°C in a dry place.": "25°C ന് താഴെ ഉണങ്ങിയ സ്ഥലത്ത് സൂക്ഷിക്കുക.",
    "Bacterial infections": "ബാക്ടീരിയൽ അണുബാധകൾ",
    "Respiratory tract infections": "ശ്വാസകോശ അണുബാധകൾ",
    "Urinary tract infections": "മൂത്രശയ അണുബാധകൾ",
    "As prescribed by your doctor — typically 500mg every 8 hours.": "ഡോക്ടർ നിർദ്ദേശിച്ചതുപോലെ — 8 മണിക്കൂർ ഇടവിട്ട് 500 മില്ലിഗ്രാം.",
    "Dose calculated by body weight — prescription only.": "ശരീരഭാരം അനുസരിച്ച് — കുറിപ്പടി മാത്രം.",
    "Take as soon as remembered; do not double dose.": "ഓർമ്മ വരുമ്പോൾ കഴിക്കുക; രണ്ട് ഡോസ് ഒരുമിച്ച് കഴിക്കരുത്.",
    "Seek medical attention immediately.": "ഉടൻ തന്നെ വൈദ്യസഹായം തേടുക.",
    "Use only if prescribed by your doctor.": "ഡോക്ടർ നിർദ്ദേശിച്ചാൽ മാത്രം കഴിക്കുക.",
    "Dose adjustment may be required.": "ഡോസിൽ മാറ്റം വരുത്തേണ്ടി വരാം.",
    "Generally avoid during the course.": "മരുന്നിന്റെ കൂടെ മദ്യപിക്കരുത്.",
    "Oral contraceptives": "ഗർഭനിരോധന ഗുളികകൾ",
    "Methotrexate": "മെത്തോട്രെക്സേറ്റ്",
    "An oral medication used to control blood sugar levels in type 2 diabetes. Requires a valid prescription.": "ടൈപ്പ് 2 പ്രമേഹത്തിൽ രക്തത്തിലെ പഞ്ചസാര നിയന്ത്രിക്കുന്ന മരുന്ന്. കുറിപ്പടി വേണം.",
    "Store below 30°C in a dry place.": "30°C ന് താഴെ ഉണങ്ങിയ സ്ഥലത്ത് സൂക്ഷിക്കുക.",
    "Type 2 diabetes management": "ടൈപ്പ് 2 പ്രമേഹ നിയന്ത്രണം",
    "Blood sugar control": "ഷുഗർ നിയന്ത്രണം",
    "As prescribed — typically 500mg 1–2 times daily with meals.": "ഡോക്ടർ നിർദ്ദേശിച്ചതുപോലെ — ഭക്ഷണത്തോടൊപ്പം ദിവസവും 1-2 തവണ 500 മില്ലിഗ്രാം.",
    "Prescription only, under specialist supervision.": "വിദഗ്ദ്ധ ഡോക്ടറുടെ മേൽനോട്ടത്തിൽ മാത്രം.",
    "Take with the next meal; do not double dose.": "അടുത്ത ഭക്ഷണത്തോടൊപ്പം കഴിക്കുക; രണ്ട് ഡോസ് കഴിക്കരുത്.",
    "Can cause dangerously low blood sugar — seek emergency help.": "ഷുഗർ വളരെ കുറയാൻ ഇടയാക്കാം — ഉടൻ വൈദ്യസഹായം തേടുക.",
    "Lactic acidosis (rare but serious)": "ലാക്റ്റിക് അസിഡോസിസ് (അപൂർവ്വം എന്നാൽ ഗൗരവമുള്ളത്)",
    "Use only under specialist supervision.": "വിദഗ്ദ്ധ മേൽനോട്ടത്തിൽ മാത്രം കഴിക്കുക.",
    "Contraindicated in severe kidney disease.": "ഗുരുതരമായ വൃക്കരോഗമുള്ളവർ കഴിക്കരുത്.",
    "Avoid — increases risk of lactic acidosis.": "ഒഴിവാക്കുക — അപകടസാധ്യത കൂടും.",
    "May cause low blood sugar — monitor before driving.": "ഷുഗർ കുറയാം — ഡ്രൈവിംഗിന് മുൻപ് ശ്രദ്ധിക്കുക.",
    "Contrast dye (imaging)": "കോൺട്രാസ്റ്റ് ഡൈ",
    "Diuretics": "ഡൈയൂററ്റിക്സ്",
    "Take with meals to reduce stomach upset.": "വയറിന് അസ്വസ്ഥത കുറയ്ക്കാൻ ഭക്ഷണത്തോടൊപ്പം കഴിക്കുക.",
    "Excess alcohol": "അമിത മദ്യപാനം",
    "An antiseptic ointment used to prevent infection in minor cuts, wounds, and burns.": "മുറിവുകളിലും പൊള്ളലുകളിലും അണുബാധ തടയുന്ന ആന്റിസെപ്റ്റിക് ക്രീം.",
    "Store below 30°C. Keep the tube tightly closed.": "30°C ന് താഴെ സൂക്ഷിക്കുക. ട്യൂബ് നന്നായി അടച്ച് വെക്കുക.",
    "Minor cuts": "ചെറിയ മുറിവുകൾ",
    "Wounds": "മുറിവുകൾ",
    "Burns": "പൊള്ളലുകൾ",
    "Skin infections": "ചർമ്മ അണുബാധകൾ",
    "Apply a thin layer to the affected area 2–3 times daily.": "മുറിവുള്ള ഭാഗത്ത് ദിവസത്തിൽ 2-3 തവണ നേർത്ത രീതിയിൽ പുരട്ടുക.",
    "Apply sparingly; consult a doctor for infants.": "കുഞ്ഞുങ്ങൾക്ക് ഡോക്ടറെ കാണിച്ച ശേഷം മാത്രം പുരട്ടുക.",
    "Not applicable — apply as needed.": "ആവശ്യാനുസരണം പുരട്ടുക.",
    "Not applicable for topical use; avoid ingestion.": "പുറമെ പുരട്ടാൻ മാത്രം.",
    "Mild skin irritation": "ലഘുവായ ചർമ്മ അസ്വസ്ഥത",
    "Allergic contact dermatitis": "അലർജി ചർമ്മ തടുപ്പ്",
    "Use with caution — consult your doctor for large areas.": "വലിയ മുറിവുകൾക്ക് ഡോക്ടറെ കാണുക.",
    "Avoid applying near the breast area.": "സ്തനങ്ങൾക്ക് സമീപം പുരട്ടരുത്.",
    "Avoid prolonged use on large wounds.": "വലിയ മുറിവുകളിൽ തുടർച്ചയായി പുരട്ടരുത്.",
    "Generally safe for topical use.": "പുറമെ പുരട്ടാൻ സുരക്ഷിതം.",
    "No interaction.": "ബാധിക്കില്ല.",
    "Other topical antiseptics (avoid combining)": "മറ്റ് ക്രീമുകളുമായി കലർത്തരുത്",
    "Not applicable.": "ബാധകമല്ല."
  },

  kn: {
    "Paracetamol is a widely used pain reliever and fever reducer, suitable for mild to moderate pain and fever in adults and children.": "ಪ್ಯಾರಾಸಿಟಮಾಲ್ ಜ್ವರ ಮತ್ತು ನೋವು ನಿವಾರಣೆಗೆ ಬಳಸಲಾಗುವ ಸುರಕ್ಷಿತ ಔಷಧಿಯಾಗಿದೆ.",
    "Store below 30°C in a dry place, away from direct sunlight.": "ನೇರ ಸೂರ್ಯನ ಬೆಳಕಿನಿಂದ ದೂರವಿಟ್ಟು, 30°C ಗಿಂತ ಕಡಿಮೆ ತಾಪಮಾನದಲ್ಲಿ ಒಣ ಸ್ಥಳದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ.",
    "Fever": "ಜ್ವರ",
    "Headache": "ತಲೆನೋವು",
    "Body ache": "ಮೈ ಕೈ ನೋವು",
    "Toothache": "ಹಲ್ಲು ನೋವು",
    "Cold-related pain": "ನೆಗಡಿ ಸಂಬಂಧಿತ ನೋವು",
    "1–2 tablets (500–1000mg) every 4–6 hours. Do not exceed 4g/day.": "ಪ್ರತಿ 4-6 ಗಂಟೆಗಳಿಗೆ 1-2 ಮಾತ್ರೆಗಳು (500-1000 ಮಿ.ಗ್ರಾಂ). ದಿನಕ್ಕೆ 4 ಗ್ರಾಂ ಗಿಂತ ಹೆಚ್ಚಾಗಬಾರದು.",
    "As advised by a pediatrician based on body weight.": "ಮಕ್ಕಳ ವೈದ್ಯರ ಸಲಹೆಯಂತೆ ದೇಹದ ತೂಕಕ್ಕೆ ಅನುಗುಣವಾಗಿ ನೀಡಿ.",
    "Take as soon as you remember. Skip if it's almost time for the next dose.": "ನೆನಪಾದ ತಕ್ಷಣ ತೆಗೆದುಕೊಳ್ಳಿ. ಮುಂದಿನ ಪ್ರಮಾಣಕ್ಕೆ ಸಮಯವಾಗಿದ್ದರೆ ಬಿಟ್ಟುಬಿಡಿ.",
    "Seek emergency medical attention immediately — overdose can cause liver damage.": "ತಕ್ಷಣವೇ ವೈದ್ಯಕೀಯ ನೆರವು ಪಡೆಯಿರಿ — ಅಧಿಕ ಪ್ರಮಾಣವು ಲಿವರ್ ಹಾನಿಗೆ ಕಾರಣವಾಗಬಹುದು.",
    "Nausea": "ವಾಕರಿಕೆ",
    "Stomach upset": "ಹೊಟ್ಟೆ ತೊಂದರೆ",
    "Skin rash": "ಚರ್ಮದ ದದ್ದು",
    "Allergic reaction": "ಅಲರ್ಜಿ ಪ್ರತಿಕ್ರಿಯೆ",
    "Liver damage (with overdose)": "ಲಿವರ್ ಹಾನಿ (ಅಧಿಕ ಪ್ರಮಾಣ ಸೇವಿಸಿದರೆ)",
    "Considered safe at recommended doses — consult your doctor.": "ಶಿಫಾರಸು ಮಾಡಿದ ಪ್ರಮಾಣದಲ್ಲಿ ಸುರಕ್ಷಿತ — ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Generally considered safe.": "ಸಾಮಾನ್ಯವಾಗಿ ಸುರಕ್ಷಿತವೆಂದು ಪರಿಗಣಿಸಲಾಗಿದೆ.",
    "Use with caution; consult your doctor.": "ಎಚ್ಚರಿಕೆಯಿಂದ ಬಳಸಿ; ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Avoid or use only under medical supervision.": "ವೈದ್ಯಕೀಯ ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿ ಮಾತ್ರ ಬಳಸಿ.",
    "Avoid regular alcohol use — increases liver damage risk.": "ಮದ್ಯಪಾನವನ್ನು ತಪ್ಪಿಸಿ — ಲಿವರ್ ಹಾನಿಯ ಅಪಾಯವನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ.",
    "Does not typically impair driving ability.": "ಚಾಲನಾ ಸಾಮರ್ಥ್ಯದ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರಲ್ಲ.",
    "Warfarin": "ವಾರ್ಫರಿನ್",
    "Alcohol": "ಮದ್ಯಪಾನ",
    "Other paracetamol-containing products": "ಇತರ ಪ್ಯಾರಾಸಿಟಮಾಲ್ ಹೊಂದಿರುವ ಉತ್ಪನ್ನಗಳು",
    "Can be taken before or after food.": "ಊಟಕ್ಕೆ ಮೊದಲು ಅಥವಾ ನಂತರ ತೆಗೆದುಕೊಳ್ಳಬಹುದು.",
    "Preferred if you have a sensitive stomach.": "ಜಠರಗಾತ್ರದ ಅಸ್ವಸ್ಥತೆ ಇದ್ದರೆ ಊಟದ ನಂತರ ತೆಗೆದುಕೊಳ್ಳಿ.",
    "A higher-strength paracetamol formulation commonly used for fever and moderate pain relief.": "ಹೆಚ್ಚಿನ ಪ್ರಮಾಣದ ಜ್ವರ ಮತ್ತು ನೋವು ನಿವಾರಣೆಗೆ ಬಳಸಲಾಗುವ ಪ್ಯಾರಾಸಿಟಮಾಲ್.",
    "Store below 30°C, away from moisture and sunlight.": "ತೇವಾಂಶ మరియు ಸೂರ್ಯನ ಬೆಳಕಿನಿಂದ ದೂರವಿಟ್ಟು 30°C ಗಿಂತ ಕಡಿಮೆ ತಾಪಮಾನದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ.",
    "1 tablet (650mg) every 6–8 hours. Do not exceed 3 tablets/day.": "ಪ್ರತಿ 6-8 ಗಂಟೆಗಳಿಗೆ 1 ಮಾತ್ರೆ (650 ಮಿ.ಗ್ರಾಂ). ದಿನಕ್ಕೆ 3 ಮಾತ್ರೆಗಳಿಗಿಂತ ಹೆಚ್ಚು ಸೇವಿಸಬೇಡಿ.",
    "Not recommended below 12 years without medical advice.": "ವೈದ್ಯರ ಸಲಹೆಯಿಲ್ಲದೆ 12 ವರ್ಷಕ್ಕಿಂತ ಕೆಳಗಿನ ಮಕ್ಕಳಿಗೆ ನೀಡಬೇಡಿ.",
    "Take as soon as you remember; skip if close to the next dose.": "ನೆನಪಾದ ತಕ್ಷಣ ತೆಗೆದುಕೊಳ್ಳಿ; ಮುಂದಿನ ಪ್ರಮಾಣಕ್ಕೆ ಹತ್ತಿರವಿದ್ದರೆ ಬಿಟ್ಟುಬಿಡಿ.",
    "Seek emergency medical attention immediately.": "ತಕ್ಷಣವೇ ತುರ್ತು ವೈದ್ಯಕೀಯ ನೆರವು ಪಡೆಯಿರಿ.",
    "Consult your doctor before use.": "ಬಳಸುವ ಮೊದಲು ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Use with caution.": "ಎಚ್ಚರಿಕೆಯಿಂದ ಬಳಸಿ.",
    "Avoid regular alcohol use.": "ಮದ್ಯಪಾನ ಸೇವನೆಯನ್ನು ತಪ್ಪಿಸಿ.",
    "Either.": "ಊಟದ ಮೊದಲು ಅಥವಾ ನಂತರ.",
    "Preferred for sensitive stomachs.": "ಹೊಟ್ಟೆಯ ತೊಂದರೆ ಇದ್ದರೆ ಊಟದ ನಂತರ ಉತ್ತಮ.",
    "A trusted paracetamol brand for fever and pain relief, available in tablet and syrup forms.": "ಜ್ವರ ಮತ್ತು ನೋವು ನಿವಾರಣೆಗೆ ನಂಬಿಕಸ್ಥ ಪ್ಯಾರಾಸಿಟಮಾಲ್ ಬ್ರಾಂಡ್.",
    "Store in a cool, dry place below 30°C.": "30°C ಗಿಂತ ಕಡಿಮೆ ತಾಪಮಾನದಲ್ಲಿ ತಂಪಾದ ಒಣ স্থানে ಸಂಗ್ರಹಿಸಿ.",
    "Mild pain": "ಸೌಮ್ಯ ನೋವು",
    "1–2 tablets every 4–6 hours. Max 4g/day.": "4-6 ಗಂಟೆಗಳಿಗೆ 1-2 ಮಾತ್ರೆಗಳು. ಗರಿಷ್ಠ 4 ಗ್ರಾಂ/ದಿನ.",
    "Pediatric syrup dosage as per body weight — consult a doctor.": "ದೇಹದ ತೂಕದ ಆಧಾರದ ಮೇಲೆ ಸಿರಪ್ ಪ್ರಮಾಣ — ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Take as soon as remembered.": "ನೆನಪಾದ ತಕ್ಷಣ ತೆಗೆದುಕೊಳ್ಳಿ.",
    "Rash": "ದದ್ದುಗಳು",
    "Liver damage (overdose)": "ಲಿವರ್ ಹಾನಿ (ಅಧಿಕ ಪ್ರಮಾಣ)",
    "Considered safe at recommended doses.": "ಶಿಫಾರಸು ಮಾಡಿದ ಪ್ರಮಾಣದಲ್ಲಿ ಸುರಕ್ಷಿತ.",
    "Generally safe.": "ಸಾಮಾನ್ಯವಾಗಿ ಸುರಕ್ಷಿತ.",
    "Avoid without medical supervision.": "ವೈದ್ಯಕೀಯ ಮೇಲ್ವಿಚಾರಣೆಯಿಲ್ಲದೆ ಸೇವಿಸಬೇಡಿ.",
    "Avoid regular use.": "ನಿಯಮಿತ ಬಳಕೆಯನ್ನು ತಪ್ಪಿಸಿ.",
    "No typical impairment.": "ಯಾವುದೇ ಪರಿಣಾಮವಿಲ್ಲ.",
    "Preferred.": "ಉತ್ತಮ.",
    "An antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes.": "ಅಲರ್ಜಿ, ಸೀನು ಮತ್ತು ಮೂಗು ಒழுகುವಿಕೆಗೆ ಆಶಾದಾಯಕ ಆಂಟಿಹಿಸ್ಟಮೈನ್.",
    "Store below 25°C, protect from light.": "ಬೆಳಕಿನಿಂದ ರಕ್ಷಿಸಿ 25°C ಗಿಂತ ಕಡಿಮೆ ತಾಪಮಾನದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ.",
    "Allergic rhinitis": "ಅಲರ್ಜಿ ಮೂಗು ಕಟ್ಟುವುದು",
    "Sneezing": "ಸೀನುವುದು",
    "Runny nose": "ಮೂಗು ಒழுகுவது",
    "Itchy/watery eyes": "ಕಣ್ಣಿನಲ್ಲಿ ತುರಿಕೆ/ನೀರು ಬರುವುದು",
    "1 tablet (10mg) once daily.": "ದಿನಕ್ಕೆ ಒಮ್ಮೆ 1 ಮಾತ್ರೆ (10 ಮಿ.ಗ್ರಾಂ).",
    "Half dose for children 6–12 years, under medical advice.": "6-12 ವರ್ಷದ ಮಕ್ಕಳಿಗೆ ಅರ್ಧ ಪ್ರಮಾಣ.",
    "Take as soon as remembered; skip if close to next dose.": "ನೆನಪಾದ ತಕ್ಷಣ ತೆಗೆದುಕೊಳ್ಳಿ; ಮುಂದಿನ ಪ್ರಮಾಣಕ್ಕೆ ಹತ್ತಿರವಿದ್ದರೆ ಬಿಟ್ಟುಬಿಡಿ.",
    "May cause drowsiness or restlessness — consult a doctor.": "ನಿದ್ರೆ ಮಂಜು ಉಂಟುಮಾಡಬಹುದು — ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Drowsiness": "ನಿದ್ರೆ ಮಂಜು",
    "Dry mouth": "ಒಣ ಬಾಯಿ",
    "Blurred vision": "ಮಂಜು ದೃಷ್ಟಿ",
    "Rapid heartbeat": "ವೇಗದ ಹೃದಯ ಬಡಿತ",
    "Use only if advised by a doctor.": "ವೈದ್ಯರ ಸಲಹೆಯಿದ್ದರೆ ಮಾತ್ರ ಬಳಸಿ.",
    "Consult your doctor.": "ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Dose adjustment may be needed.": "ಪ್ರಮಾಣ ಬದಲಾವಣೆ ಅಗತ್ಯವಿರಬಹುದು.",
    "Avoid — may increase drowsiness.": "ತಪ್ಪಿಸಿ — ನಿದ್ರೆ ಮಂಜು ಹೆಚ್ಚಾಗಬಹುದು.",
    "May cause drowsiness — avoid driving until you know how it affects you.": "ನಿದ್ರೆ ಮಂಜು ಉಂಟುಮಾಡಬಹುದು — ಚಾಲನೆಯನ್ನು ತಪ್ಪಿಸಿ.",
    "Sedatives": "ನಿದ್ರೆ ಮದ್ದುಗಳು",
    "Theophylline": "ಥಿಯೋಫಿಲಿನ್",
    "Oral rehydration salts used to restore fluids and electrolytes lost due to dehydration, diarrhea, or vomiting.": "ನಿರ್ಜಲೀಕರಣ మరియు ಭೇದಿಯಿಂದ ಕಳೆದುಕೊಂಡ ದ್ರವವನ್ನು ಮರಳಿ ಪಡೆಯಲು ಓಆರ್‌ಎಸ್ ದ್ರಾವಣ.",
    "Store the prepared solution in a fridge and discard after 24 hours.": "ತಯಾರಿಸಿದ ದ್ರಾವಣವನ್ನು ಫ್ರಿಡ್ಜ್‌ನಲ್ಲಿಟ್ಟು 24 ಗಂಟೆಗಳ ನಂತರ ಚೆಲ್ಲಿ.",
    "Dehydration": "ನಿರ್ಜಲೀಕರಣ",
    "Diarrhea": "ಭೇದಿ (ಅತಿಸಾರ)",
    "Heat exhaustion": "ಬಿಸಿಲಿನ ಆಯಾಸ",
    "Vomiting": "ವಾಂತಿ",
    "1 sachet dissolved in 1 liter of clean water; sip throughout the day.": "1 ಪಾಕೆಟ್ ಅನ್ನು 1 ಲೀಟರ್ ಶುದ್ಧ ನೀರಿನಲ್ಲಿ ಕರಗಿಸಿ ದಿನವಿಡೀ കുಡಿಯಿರಿ.",
    "As advised by a pediatrician based on dehydration severity.": "ಮಕ್ಕಳ ವೈದ್ಯರ ಸಲಹೆಯಂತೆ ನೀಡಿ.",
    "Not applicable — take as needed.": "ಅಗತ್ಯವಿರುವಾಗ ತೆಗೆದುಕೊಳ್ಳಿ.",
    "Excess intake may cause electrolyte imbalance — consult a doctor if unwell.": "ಹೆಚ್ಚು ಸೇವನೆಯು ಎಲೆಕ್ಟ್ರೋಲೈಟ್ ಅಸಮತೋಲನಕ್ಕೆ ಕಾರಣವಾಗಬಹುದು.",
    "Mild bloating": "ಸೌಮ್ಯ ಹೊಟ್ಟೆ ಉಬ್ಬರ",
    "Vomiting if taken too concentrated": "ಹೆಚ್ಚು ಗಟ್ಟಿಯಾಗಿ ಕುಡಿದರೆ ವಾಂತಿ ಬರಬಹುದು",
    "Safe to use.": "ಬಳಸಲು ಸುರಕ್ಷಿತ.",
    "Use with medical guidance.": "ವೈದ್ಯಕೀಯ ಮಾರ್ಗದರ್ಶನದೊಂದಿಗೆ ಬಳಸಿ.",
    "No known interaction.": "ಯಾವುದೇ ಅಡ್ಡಪರಿಣಾಮವಿಲ್ಲ.",
    "No impairment.": "ಪರಿಣಾಮವಿಲ್ಲ.",
    "A chewable Vitamin C supplement that supports immunity and skin health.": "ರೋಗನಿರೋಧಕ ಶಕ್ತಿಯನ್ನು ಹೆಚ್ಚಿಸುವ ವಿಟಮಿನ್ ಸಿ ಮಾತ್ರೆ.",
    "Store in a cool, dry place.": "ತಂಪಾದ, ಒಣ ಸ್ಥಳದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ.",
    "Vitamin C deficiency": "ವಿಟಮಿನ್ ಸಿ ಕೊರತೆ",
    "Immunity support": "ರೋಗನಿರೋಧಕ ಬೆಂಬಲ",
    "Antioxidant supplementation": "ಆಂಟಿಆಕ್ಸಿಡೆಂಟ್ ಪೂರಕ",
    "1 tablet daily, or as directed by a physician.": "ದಿನಕ್ಕೆ 1 ಮಾತ್ರೆ, ಅಥವಾ ವೈದ್ಯರ ಸೂಚನೆಯಂತೆ.",
    "As advised by a pediatrician.": "ಮಕ್ಕಳ ವೈದ್ಯರ ಸಲಹೆಯಂತೆ.",
    "High doses may cause stomach upset or diarrhea.": "ಹೆಚ್ಚಿನ ಪ್ರಮಾಣವು ಹೊಟ್ಟೆ ತೊಂದರೆಗೆ ಕಾರಣವಾಗಬಹುದು.",
    "Mild stomach upset": "ಸೌಮ್ಯ ಹೊಟ್ಟೆ ಕಿರಿಕಿರಿ",
    "Kidney stones with prolonged high doses": "ದೀರ್ಘಕಾಲ ಹೆಚ್ಚಿನ ಪ್ರಮಾಣ ಸೇವಿಸಿದರೆ ಮೂತ್ರಪಿಂಡದ ಕಲ್ಲು ಬರಬಹುದು",
    "Safe within recommended doses.": "ಶಿಫಾರಸು ಮಾಡಿದ ಪ್ರಮಾಣದಲ್ಲಿ ಸುರಕ್ಷಿತ.",
    "Use with caution — consult your doctor.": "ಎಚ್ಚರಿಕೆಯಿಂದ ಬಳಸಿ — ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Iron supplements (increases absorption)": "ಕಬ್ಬಿಣದ ಪೂರಕಗಳು",
    "An antacid gel that relieves acidity, heartburn, and gas.": "ಅಸಿಡಿಟಿ ಮತ್ತು ಗ್ಯಾಸ್‌ನಿಂದ ಶಮನ ನೀಡುವ ಆಂಟಾಸಿಡ್ ಜೆಲ್.",
    "Store below 30°C. Shake well before use.": "30°C ಗಿಂತ ಕಡಿಮೆ ತಾಪಮಾನದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿ. ಬಳಸುವ ಮೊದಲು ಚೆನ್ನಾಗಿ ಕಲಕಿ.",
    "Acidity": "ಅಸಿಡಿಟಿ",
    "Heartburn": "ಎದೆ ಉರಿ",
    "Gas/bloating": "ಗ್ಯಾಸ್/ಹೊಟ್ಟೆ ಉಬ್ಬರ",
    "Indigestion": "ಅಜೀರ್ಣ",
    "1–2 teaspoons (5–10ml) after meals and at bedtime.": "ಊಟದ ನಂತರ ಮತ್ತು ಮಲಗುವ ಮುನ್ನ 1-2 ಚಮಚ (5-10 ಮಿ.ಲೀ).",
    "Not recommended without medical advice.": "ವೈದ್ಯರ ಸಲಹೆಯಿಲ್ಲದೆ ಬಳಸಬೇಡಿ.",
    "Take when needed; not a scheduled medication.": "ಅಗತ್ಯವಿದ್ದಾಗ ತೆಗೆದುಕೊಳ್ಳಿ.",
    "Excess use may cause diarrhea or electrolyte imbalance.": "ಹೆಚ್ಚು ಬಳಸಿದರೆ ಭೇದಿಯಾಗಬಹುದು.",
    "Mild diarrhea": "ಸೌಮ್ಯ ಅತಿಸಾರ",
    "Constipation": "ಮಲಬದ್ಧತೆ",
    "Generally considered safe — consult your doctor.": "ಸಾಮಾನ್ಯವಾಗಿ ಸುರಕ್ಷಿತ — ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "No major interaction.": "ಯಾವುದೇ ಅಡ್ಡಪರಿಣಾಮವಿಲ್ಲ.",
    "Tetracycline antibiotics": "ಟೆಟ್ರಾಸೈಕ್ಲಿನ್ ಆಂಟಿಬಯೋಟಿಕ್ಸ್",
    "Iron supplements": "ಕಬ್ಬಿಣದ ಪೂರಕಗಳು",
    "Not typical.": "ಪರಿಣಾಮವಿಲ್ಲ.",
    "Take after meals.": "ಊಟದ ನಂತರ ತೆಗೆದುಕೊಳ್ಳಿ.",
    "An antacid suspension for fast relief from acidity and heartburn.": "ಅಸಿಡಿಟಿಯಿಂದ ತಕ್ಷಣದ ಶಮನ ನೀಡುವ ಆಂಟಾಸಿಡ್ ದ್ರವ.",
    "1–2 teaspoons after meals and at bedtime.": "ಊಟದ ನಂತರ ಮತ್ತು ಮಲಗುವ ಮುನ್ನ 1-2 ಚಮಚ.",
    "Take when needed.": "ಅಗತ್ಯವಿದ್ದಾಗ ತೆಗೆದುಕೊಳ್ಳಿ.",
    "Excess use may cause bowel disturbances.": "ಹೆಚ್ಚಿನ ಬಳಕೆಯು ಜಠರದ ತೊಂದರೆಗೆ ಕಾರಣವಾಗಬಹುದು.",
    "Mild constipation": "ಸೌಮ್ಯ ಮಲಬದ್ಧತೆ",
    "A penicillin-based antibiotic used to treat a wide range of bacterial infections. Requires a valid prescription.": "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಸೋಂಕುಗಳಿಗೆ ಚಿಕಿತ್ಸೆ ನೀಡುವ ಆಂಟಿಬಯೋಟಿಕ್. ವೈದ್ಯರ ಚೀಟಿ ಅಗತ್ಯ.",
    "Store below 25°C in a dry place.": "25°C ಗಿಂತ ಕಡಿಮೆ ತಾಪಮಾನದಲ್ಲಿ ಒಣ ಸ್ಥಳದಲ್ಲಿ ಇರಿಸಿ.",
    "Bacterial infections": "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಸೋಂಕುಗಳು",
    "Respiratory tract infections": "ಉಸಿರಾಟದ ಸೋಂಕುಗಳು",
    "Urinary tract infections": "ಮೂತ್ರನಾಳದ ಸೋಂಕುಗಳು",
    "As prescribed by your doctor — typically 500mg every 8 hours.": "ವೈದ್ಯರ ಸೂಚನೆಯಂತೆ — ಸಾಮಾನ್ಯವಾಗಿ ಪ್ರತಿ 8 ಗಂಟೆಗೆ 500 ಮಿ.ಗ್ರಾಂ.",
    "Dose calculated by body weight — prescription only.": "ದೇಹದ ತೂಕದ ಆಧಾರದ ಮೇಲೆ — ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಮಾತ್ರ.",
    "Take as soon as remembered; do not double dose.": "ನೆನಪಾದ ತಕ್ಷಣ ತೆಗೆದುಕೊಳ್ಳಿ; ದುಪ್ಪಟ್ಟು ಪ್ರಮಾಣ ಸೇವಿಸಬೇಡಿ.",
    "Seek medical attention immediately.": "ತಕ್ಷಣವೇ ವೈದ್ಯಕೀಯ ನೆರವು ಪಡೆಯಿರಿ.",
    "Use only if prescribed by your doctor.": "ವೈದ್ಯರು ಸೂಚಿಸಿದರೆ ಮಾತ್ರ ಬಳಸಿ.",
    "Dose adjustment may be required.": "ಪ್ರಮಾಣ ಬದಲಾವಣೆ ಅಗತ್ಯವಿರಬಹುದು.",
    "Generally avoid during the course.": "ಕೋರ್ಸ್ ಸಮಯದಲ್ಲಿ ಮದ್ಯಪಾನ ತಪ್ಪಿಸಿ.",
    "Oral contraceptives": "ಗರ್ಭನಿರೋಧಕ ಮಾತ್ರೆಗಳು",
    "Methotrexate": "ಮೆಥೋಟ್ರೆಕ್ಸೇಟ್",
    "An oral medication used to control blood sugar levels in type 2 diabetes. Requires a valid prescription.": "ಟೈಪ್ 2 ಮಧುಮೇಹದಲ್ಲಿ ರಕ್ತದ ಸಕ್ಕರೆಯನ್ನು ನಿಯಂತ್ರಿಸುವ ಮಾತ್ರೆ. ಚೀಟಿ ಅಗತ್ಯ.",
    "Store below 30°C in a dry place.": "30°C ಗಿಂತ ಕಡಿಮೆ ಒಣ স্থানে ಇರಿಸಿ.",
    "Type 2 diabetes management": "ಟೈಪ್ 2 ಮಧುಮೇಹ ನಿರ್ವಹಣೆ",
    "Blood sugar control": "ರಕ್ತದ ಸಕ್ಕರೆ ನಿಯಂತ್ರಣ",
    "As prescribed — typically 500mg 1–2 times daily with meals.": "ವೈದ್ಯರ ಸೂಚನೆಯಂತೆ — ಊಟದ ಜೊತೆಗೆ ದಿನಕ್ಕೆ 1-2 ಬಾರಿ 500 ಮಿ.ಗ್ರಾಂ.",
    "Prescription only, under specialist supervision.": "ತಜ್ಞರ ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿ ಮಾತ್ರ.",
    "Take with the next meal; do not double dose.": "ಮುಂದಿನ ಊಟದ ಜೊತೆ ತೆಗೆದುಕೊಳ್ಳಿ; ದುಪ್ಪಟ್ಟು ಸೇವಿಸಬೇಡಿ.",
    "Can cause dangerously low blood sugar — seek emergency help.": "ಸಕ್ಕರೆ ಪ್ರಮಾಣ ಅಪಾಯಕಾರಿಯಾಗಿ ಕಡಿಮೆಯಾಗಬಹುದು — ತುರ್ತು ನೆರವು ಪಡೆಯಿರಿ.",
    "Lactic acidosis (rare but serious)": "ಲ್ಯಾಕ್ಟಿಕ್ ಆಸಿಡೋಸಿಸ್ (ಅಪರೂಪ ಆದರೆ ಗಂಭೀರ)",
    "Use only under specialist supervision.": "ತಜ್ಞರ ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿ ಮಾತ್ರ ಬಳಸಿ.",
    "Contraindicated in severe kidney disease.": "ತೀವ್ರ ಮೂತ್ರಪಿಂಡ ರೋಗದಲ್ಲಿ ನಿಷೇಧಿಸಲಾಗಿದೆ.",
    "Avoid — increases risk of lactic acidosis.": "ತಪ್ಪಿಸಿ — ಅಪಾಯ ಹೆಚ್ಚಾಗುತ್ತದೆ.",
    "May cause low blood sugar — monitor before driving.": "ಸಕ್ಕರೆ ಮಟ್ಟ ಕಡಿಮೆಯಾಗಬಹುದು — ಚಾಲನೆ ಮಾಡುವ ಮೊದಲು ಗಮನಿಸಿ.",
    "Contrast dye (imaging)": "ಕಾంట್ರಾಸ್ಟ್ ಡೈ",
    "Diuretics": "ಡೈಯೂರೆಟಿಕ್ಸ್",
    "Take with meals to reduce stomach upset.": "ಹೊಟ್ಟೆ ತೊಂದರೆ ತಪ್ಪಿಸಲು ಊಟದ ಜೊತೆ ತೆಗೆದುಕೊಳ್ಳಿ.",
    "Excess alcohol": "ಅತಿಯಾದ ಮದ್ಯಪಾನ",
    "An antiseptic ointment used to prevent infection in minor cuts, wounds, and burns.": "ಗಾಯಗಳಲ್ಲಿ ಸೋಂಕು ತಡೆಯುವ ಆಂಟಿಸೆಪ್ಟಿಕ್ ಮುಲಾಮು.",
    "Store below 30°C. Keep the tube tightly closed.": "30°C ಗಿಂತ ಕಡಿಮೆ ತಾಪಮಾನದಲ್ಲಿ ಇರಿಸಿ. ಟ್ಯೂಬ್ ಅನ್ನು ಬಿಗಿಯಾಗಿ ಮುಚ್ಚಿ.",
    "Minor cuts": "ಚಿಕ್ಕ ಗಾಯಗಳು",
    "Wounds": "ಗಾಯಗಳು",
    "Burns": "ಸುಟ್ಟಗಾಯಗಳು",
    "Skin infections": "ಚರ್ಮದ ಸೋಂಕುಗಳು",
    "Apply a thin layer to the affected area 2–3 times daily.": "ಗಾಯವಾದ ಸ್ಥಳಕ್ಕೆ ದಿನಕ್ಕೆ 2-3 ಬಾರಿ ಸಣ್ಣದಾಗಿ ಹಚ್ಚಿ.",
    "Apply sparingly; consult a doctor for infants.": "ಸಣ್ಣ ಪ್ರಮಾಣದಲ್ಲಿ ಹಚ್ಚಿ; ಶಿಶುಗಳಿಗೆ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Not applicable — apply as needed.": "ಅಗತ್ಯವಿರುವಾಗ ಹಚ್ಚಿ.",
    "Not applicable for topical use; avoid ingestion.": "ಹೊರಗಿನ ಬಳಕೆಗೆ ಮಾತ್ರ.",
    "Mild skin irritation": "ಸೌಮ್ಯ ಚರ್ಮದ ಉರಿ",
    "Allergic contact dermatitis": "ಅಲರ್ಜಿ ಚರ್ಮದ ದದ್ದು",
    "Use with caution — consult your doctor for large areas.": "ದೊಡ್ಡ ಗಾಯಗಳಿಗೆ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "Avoid applying near the breast area.": "ಎದೆ ಭಾಗದ ಹತ್ತಿರ ಹಚ್ಚಬೇಡಿ.",
    "Avoid prolonged use on large wounds.": "ದೊಡ್ಡ ಗಾಯಗಳ ಮೇಲೆ ದೀರ್ಘಕಾಲ ಬಳಸಬೇಡಿ.",
    "Generally safe for topical use.": "ಹೊರಗಿನ ಬಳಕೆಗೆ ಸುರಕ್ಷಿತ.",
    "No interaction.": "ಪರಿಣಾಮವಿಲ್ಲ.",
    "Other topical antiseptics (avoid combining)": "ಇತರ ಮುಲಾಮುಗಳೊಂದಿಗೆ ಬೆರೆಸಬೇಡಿ",
    "Not applicable.": "ಅನ್ವಯಿಸುವುದಿಲ್ಲ."
  }
};

module.exports = { ALL_SENTENCE_MAPS };
