const COMMON_WORD_MAPS = {
  ta: {
    "Powder": "பவுடர்",
    "Fruit Salt": "ஃப்ரூட் சால்ட்",
    "Lemon": "எலுமிச்சை",
    "Regular": "ரெகுலர்",
    "Orange": "ஆரஞ்சு",
    "Cream": "கிரீம்",
    "Spray": "ஸ்ப்ரே",
    "Inhaler": "இன்ஹேலர்",
    "Forte": "ஃபோர்ட்டே",
    "Advance": "அட்வான்ஸ்",
    "Plus": "பிளஸ்",
    "Duo": "டுயோ",
    "Limited": "லிமிடெட்",
    "Laboratories": "லேபாரட்டரீஸ்",
    "Pharmaceuticals": "பார்மாசிட்டிகல்ஸ்",
    "Pharma": "பார்மா",
    "Healthcare": "ஹெல்த்கேர்",
    "Private": "பிரைவேட்",
    "Pvt": "பிரைவேட்",
    "Ltd": "லிமிடெட்",
    "Strip": "துண்டு",
    "tablets": "மாத்திரைகள்",
    "capsules": "கேப்சூல்கள்",
    "sachets": "சாச்செட்டுகள்",
    "bottle": "பாட்டில்",
    "tube": "டியூப்",
    "doses": "அளவுகள்",
    "Pack": "பாக்கெட்",
    "Box": "பெட்டி",
  },
  hi: {
    "Powder": "पाउडर",
    "Fruit Salt": "फ्रूट साल्ट",
    "Lemon": "लेमन",
    "Regular": "रेगुलर",
    "Orange": "ऑरेंज",
    "Cream": "क्रीम",
    "Spray": "स्प्रे",
    "Inhaler": "इनहेलर",
    "Forte": "फोर्ट",
    "Advance": "एडवांस",
    "Plus": "प्लस",
    "Duo": "डुओ",
    "Limited": "लिमिटेड",
    "Laboratories": "लेबोरेटरीज",
    "Pharmaceuticals": "फार्मास्यूटिकल्स",
    "Pharma": "फार्मा",
    "Healthcare": "हेल्थकेयर",
    "Private": "प्राइवेट",
    "Pvt": "प्राइवेट",
    "Ltd": "लिमिटेड",
    "Strip": "स्ट्रिप",
    "tablets": "गोलियां",
    "capsules": "कैप्सूल",
    "sachets": "पाउच",
    "bottle": "बोतल",
    "tube": "ट्यूब",
    "doses": "खुराक",
    "Pack": "पैक",
    "Box": "बॉक्स",
  },
  te: {
    "Powder": "పౌడర్",
    "Fruit Salt": "ఫ్రూట్ సాల్ట్",
    "Lemon": "నిమ్మ",
    "Regular": "రెగ్యులర్",
    "Orange": "ఆరంజ్",
    "Cream": "క్రీమ్",
    "Spray": "స్ప్రే",
    "Inhaler": "ఇన్హేలర్",
    "Forte": "ఫోర్టే",
    "Advance": "అడ్వాన్స్",
    "Plus": "ప్లస్",
    "Duo": "డుయో",
    "Limited": "లిమిటెడ్",
    "Laboratories": "ల్యాబొరేటరీస్",
    "Pharmaceuticals": "ఫార్మాస్యూటికల్స్",
    "Pharma": "ఫార్మా",
    "Healthcare": "హెల్త్‌కేర్",
    "Private": "ప్రైవేట్",
    "Pvt": "ప్రైవేట్",
    "Ltd": "లిమిటెడ్",
    "Strip": "స్ట్రిప్",
    "tablets": "టాబ్లెట్లు",
    "capsules": "క్యాప్సూల్స్",
    "sachets": "ప్యాకెట్లు",
    "bottle": "బాటిల్",
    "tube": "ట్యూబ్",
    "doses": "డోసులు",
    "Pack": "ప్యాక్",
    "Box": "బాక్స్",
  },
  ml: {
    "Powder": "പൗഡർ",
    "Fruit Salt": "ഫ്രൂട്ട് സാൾട്ട്",
    "Lemon": "ലമൺ",
    "Regular": "റെഗുലർ",
    "Orange": "ഓറഞ്ച്",
    "Cream": "ക്രീം",
    "Spray": "സ്പ്രേ",
    "Inhaler": "ഇൻഹേലർ",
    "Forte": "ഫോർട്ട്",
    "Advance": "അഡ്വാൻസ്",
    "Plus": "പ്ലസ്",
    "Duo": "ഡ്യുവോ",
    "Limited": "ലിമിറ്റഡ്",
    "Laboratories": "ലാബറട്ടറീസ്",
    "Pharmaceuticals": "ഫാർമസ്യൂട്ടിക്കൽസ്",
    "Pharma": "ഫാർമ",
    "Healthcare": "ഹെൽത്ത്കെയർ",
    "Private": "പ്രൈവറ്റ്",
    "Pvt": "പ്രൈവറ്റ്",
    "Ltd": "ലിമിറ്റഡ്",
    "Strip": "സ്ട്രിപ്പ്",
    "tablets": "ഗുളികകൾ",
    "capsules": "ക്യാപ്സ്യൂളുകൾ",
    "sachets": "സാച്ചെറ്റുകൾ",
    "bottle": "ബോട്ടിൽ",
    "tube": "ട്യൂബ്",
    "doses": "ഡോസുകൾ",
    "Pack": "പാക്ക്",
    "Box": "ബോക്സ്",
  },
  kn: {
    "Powder": "ಪೌಡರ್",
    "Fruit Salt": "ಫ್ರೂಟ್ ಸಾಲ್ಟ್",
    "Lemon": "ಲೆಮನ್",
    "Regular": "ರೆಗ್ಯುಲರ್",
    "Orange": "ಆರೆಂಜ್",
    "Cream": "ಕ್ರೀಮ್",
    "Spray": "ಸ್ಪ್ರೇ",
    "Inhaler": "ಇನ್‌ಹೇಲರ್",
    "Forte": "ಫೋರ್ಟೆ",
    "Advance": "ಅಡ್ವಾನ್ಸ್",
    "Plus": "ಪ್ಲಸ್",
    "Duo": "ಡ್ಯುಯೊ",
    "Limited": "ಲಿಮಿಟೆಡ್",
    "Laboratories": "ಲ್ಯಾಬೊರೇಟರೀಸ್",
    "Pharmaceuticals": "ಫಾರ್ಮಾಸ್ಯುಟಿಕಲ್ಸ್",
    "Pharma": "ಫಾರ್ಮಾ",
    "Healthcare": "ಹೆಲ್ತ್‌ಕೇರ್",
    "Private": "ಪ್ರೈವೇಟ್",
    "Pvt": "ಪ್ರೈವೇಟ್",
    "Ltd": "ಲಿಮಿಟೆಡ್",
    "Strip": "ಸ್ಟ್ರಿಪ್",
    "tablets": "ಮಾತ್ರೆಗಳು",
    "capsules": "ಕ್ಯಾಪ್ಸುಲ್ಗಳು",
    "sachets": "ಪಾಕೆಟ್‌ಗಳು",
    "bottle": "ಬಾಟಲ್",
    "tube": "ಟ್ಯೂಬ್",
    "doses": "ಡೋಸ್‌ಗಳು",
    "Pack": "ಪ್ಯಾಕ್",
    "Box": "ಬಾಕ್ಸ್",
  }
};

function applyWordReplacements(text, langCode) {
  if (!text || langCode === "en") return text;
  const wordMap = COMMON_WORD_MAPS[langCode];
  if (!wordMap) return text;
  let result = text;
  const sortedKeys = Object.keys(wordMap).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    const regex = new RegExp(`\\b${key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "gi");
    result = result.replace(regex, wordMap[key]);
  }
  return result;
}

// Test word replacement
console.log("Electral Powder (ta):", applyWordReplacements("Electral Powder", "ta"));
console.log("Electral Powder (te):", applyWordReplacements("Electral Powder", "te"));
console.log("FDC Limited (ta):", applyWordReplacements("FDC Limited", "ta"));
console.log("Pack of 5 sachets (kn):", applyWordReplacements("Pack of 5 sachets", "kn"));
